// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extinfo.proto

package wechat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FPFresh struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	SessKey              []byte       `protobuf:"bytes,2,opt,name=SessKey" json:"SessKey,omitempty"`
	Ztdata               *ZTData      `protobuf:"bytes,3,opt,name=Ztdata" json:"Ztdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FPFresh) Reset()         { *m = FPFresh{} }
func (m *FPFresh) String() string { return proto.CompactTextString(m) }
func (*FPFresh) ProtoMessage()    {}
func (*FPFresh) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{0}
}

func (m *FPFresh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FPFresh.Unmarshal(m, b)
}
func (m *FPFresh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FPFresh.Marshal(b, m, deterministic)
}
func (m *FPFresh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FPFresh.Merge(m, src)
}
func (m *FPFresh) XXX_Size() int {
	return xxx_messageInfo_FPFresh.Size(m)
}
func (m *FPFresh) XXX_DiscardUnknown() {
	xxx_messageInfo_FPFresh.DiscardUnknown(m)
}

var xxx_messageInfo_FPFresh proto.InternalMessageInfo

func (m *FPFresh) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *FPFresh) GetSessKey() []byte {
	if m != nil {
		return m.SessKey
	}
	return nil
}

func (m *FPFresh) GetZtdata() *ZTData {
	if m != nil {
		return m.Ztdata
	}
	return nil
}

type SaeInfoAndroid struct {
	Ver                  *string  `protobuf:"bytes,1,opt,name=Ver" json:"Ver,omitempty"`
	InitKey              []byte   `protobuf:"bytes,2,opt,name=InitKey" json:"InitKey,omitempty"`
	TotalSize            *int32   `protobuf:"varint,3,opt,name=TotalSize" json:"TotalSize,omitempty"`
	XorKey1              []byte   `protobuf:"bytes,9,opt,name=XorKey1" json:"XorKey1,omitempty"`
	Key1                 []byte   `protobuf:"bytes,10,opt,name=Key1" json:"Key1,omitempty"`
	XorKey2              []byte   `protobuf:"bytes,11,opt,name=XorKey2" json:"XorKey2,omitempty"`
	Key2                 []byte   `protobuf:"bytes,12,opt,name=Key2" json:"Key2,omitempty"`
	Key3                 []byte   `protobuf:"bytes,18,opt,name=Key3" json:"Key3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaeInfoAndroid) Reset()         { *m = SaeInfoAndroid{} }
func (m *SaeInfoAndroid) String() string { return proto.CompactTextString(m) }
func (*SaeInfoAndroid) ProtoMessage()    {}
func (*SaeInfoAndroid) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{1}
}

func (m *SaeInfoAndroid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaeInfoAndroid.Unmarshal(m, b)
}
func (m *SaeInfoAndroid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaeInfoAndroid.Marshal(b, m, deterministic)
}
func (m *SaeInfoAndroid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaeInfoAndroid.Merge(m, src)
}
func (m *SaeInfoAndroid) XXX_Size() int {
	return xxx_messageInfo_SaeInfoAndroid.Size(m)
}
func (m *SaeInfoAndroid) XXX_DiscardUnknown() {
	xxx_messageInfo_SaeInfoAndroid.DiscardUnknown(m)
}

var xxx_messageInfo_SaeInfoAndroid proto.InternalMessageInfo

func (m *SaeInfoAndroid) GetVer() string {
	if m != nil && m.Ver != nil {
		return *m.Ver
	}
	return ""
}

func (m *SaeInfoAndroid) GetInitKey() []byte {
	if m != nil {
		return m.InitKey
	}
	return nil
}

func (m *SaeInfoAndroid) GetTotalSize() int32 {
	if m != nil && m.TotalSize != nil {
		return *m.TotalSize
	}
	return 0
}

func (m *SaeInfoAndroid) GetXorKey1() []byte {
	if m != nil {
		return m.XorKey1
	}
	return nil
}

func (m *SaeInfoAndroid) GetKey1() []byte {
	if m != nil {
		return m.Key1
	}
	return nil
}

func (m *SaeInfoAndroid) GetXorKey2() []byte {
	if m != nil {
		return m.XorKey2
	}
	return nil
}

func (m *SaeInfoAndroid) GetKey2() []byte {
	if m != nil {
		return m.Key2
	}
	return nil
}

func (m *SaeInfoAndroid) GetKey3() []byte {
	if m != nil {
		return m.Key3
	}
	return nil
}

type ZTData struct {
	Version              []byte   `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Encrypted            *uint64  `protobuf:"varint,2,opt,name=Encrypted" json:"Encrypted,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data" json:"Data,omitempty"`
	TimeStamp            *int64   `protobuf:"varint,4,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	OpType               *uint64  `protobuf:"varint,5,opt,name=OpType" json:"OpType,omitempty"`
	Uin                  *uint64  `protobuf:"varint,6,opt,name=Uin" json:"Uin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZTData) Reset()         { *m = ZTData{} }
func (m *ZTData) String() string { return proto.CompactTextString(m) }
func (*ZTData) ProtoMessage()    {}
func (*ZTData) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{2}
}

func (m *ZTData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZTData.Unmarshal(m, b)
}
func (m *ZTData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZTData.Marshal(b, m, deterministic)
}
func (m *ZTData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZTData.Merge(m, src)
}
func (m *ZTData) XXX_Size() int {
	return xxx_messageInfo_ZTData.Size(m)
}
func (m *ZTData) XXX_DiscardUnknown() {
	xxx_messageInfo_ZTData.DiscardUnknown(m)
}

var xxx_messageInfo_ZTData proto.InternalMessageInfo

func (m *ZTData) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ZTData) GetEncrypted() uint64 {
	if m != nil && m.Encrypted != nil {
		return *m.Encrypted
	}
	return 0
}

func (m *ZTData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ZTData) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *ZTData) GetOpType() uint64 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

func (m *ZTData) GetUin() uint64 {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return 0
}

type DeviceRunningInfos struct {
	Version              []byte   `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Type                 *int64   `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	EncryptData          []byte   `protobuf:"bytes,3,opt,name=EncryptData" json:"EncryptData,omitempty"`
	TimeStamp            *int64   `protobuf:"varint,4,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	Unknown5             *uint64  `protobuf:"varint,5,opt,name=Unknown5" json:"Unknown5,omitempty"`
	Unknown6             *uint64  `protobuf:"varint,6,opt,name=Unknown6" json:"Unknown6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceRunningInfos) Reset()         { *m = DeviceRunningInfos{} }
func (m *DeviceRunningInfos) String() string { return proto.CompactTextString(m) }
func (*DeviceRunningInfos) ProtoMessage()    {}
func (*DeviceRunningInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{3}
}

func (m *DeviceRunningInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceRunningInfos.Unmarshal(m, b)
}
func (m *DeviceRunningInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceRunningInfos.Marshal(b, m, deterministic)
}
func (m *DeviceRunningInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceRunningInfos.Merge(m, src)
}
func (m *DeviceRunningInfos) XXX_Size() int {
	return xxx_messageInfo_DeviceRunningInfos.Size(m)
}
func (m *DeviceRunningInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceRunningInfos.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceRunningInfos proto.InternalMessageInfo

func (m *DeviceRunningInfos) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *DeviceRunningInfos) GetType() int64 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *DeviceRunningInfos) GetEncryptData() []byte {
	if m != nil {
		return m.EncryptData
	}
	return nil
}

func (m *DeviceRunningInfos) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *DeviceRunningInfos) GetUnknown5() uint64 {
	if m != nil && m.Unknown5 != nil {
		return *m.Unknown5
	}
	return 0
}

func (m *DeviceRunningInfos) GetUnknown6() uint64 {
	if m != nil && m.Unknown6 != nil {
		return *m.Unknown6
	}
	return 0
}

type TrustDeviceInfo struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=Val" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustDeviceInfo) Reset()         { *m = TrustDeviceInfo{} }
func (m *TrustDeviceInfo) String() string { return proto.CompactTextString(m) }
func (*TrustDeviceInfo) ProtoMessage()    {}
func (*TrustDeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{4}
}

func (m *TrustDeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustDeviceInfo.Unmarshal(m, b)
}
func (m *TrustDeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustDeviceInfo.Marshal(b, m, deterministic)
}
func (m *TrustDeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustDeviceInfo.Merge(m, src)
}
func (m *TrustDeviceInfo) XXX_Size() int {
	return xxx_messageInfo_TrustDeviceInfo.Size(m)
}
func (m *TrustDeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustDeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TrustDeviceInfo proto.InternalMessageInfo

func (m *TrustDeviceInfo) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *TrustDeviceInfo) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type TrustReq struct {
	Td                   *TrustData `protobuf:"bytes,1,opt,name=Td" json:"Td,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrustReq) Reset()         { *m = TrustReq{} }
func (m *TrustReq) String() string { return proto.CompactTextString(m) }
func (*TrustReq) ProtoMessage()    {}
func (*TrustReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{5}
}

func (m *TrustReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustReq.Unmarshal(m, b)
}
func (m *TrustReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustReq.Marshal(b, m, deterministic)
}
func (m *TrustReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustReq.Merge(m, src)
}
func (m *TrustReq) XXX_Size() int {
	return xxx_messageInfo_TrustReq.Size(m)
}
func (m *TrustReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustReq.DiscardUnknown(m)
}

var xxx_messageInfo_TrustReq proto.InternalMessageInfo

func (m *TrustReq) GetTd() *TrustData {
	if m != nil {
		return m.Td
	}
	return nil
}

type TrustData struct {
	Tdi                  []*TrustDeviceInfo `protobuf:"bytes,1,rep,name=Tdi" json:"Tdi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TrustData) Reset()         { *m = TrustData{} }
func (m *TrustData) String() string { return proto.CompactTextString(m) }
func (*TrustData) ProtoMessage()    {}
func (*TrustData) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{6}
}

func (m *TrustData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustData.Unmarshal(m, b)
}
func (m *TrustData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustData.Marshal(b, m, deterministic)
}
func (m *TrustData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustData.Merge(m, src)
}
func (m *TrustData) XXX_Size() int {
	return xxx_messageInfo_TrustData.Size(m)
}
func (m *TrustData) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustData.DiscardUnknown(m)
}

var xxx_messageInfo_TrustData proto.InternalMessageInfo

func (m *TrustData) GetTdi() []*TrustDeviceInfo {
	if m != nil {
		return m.Tdi
	}
	return nil
}

type TrustRequest struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,req,name=BaseRequest" json:"BaseRequest,omitempty"`
	RandomKey            []byte       `protobuf:"bytes,2,opt,name=RandomKey" json:"RandomKey,omitempty"`
	SpamBuff             []byte       `protobuf:"bytes,3,opt,name=spamBuff" json:"spamBuff,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TrustRequest) Reset()         { *m = TrustRequest{} }
func (m *TrustRequest) String() string { return proto.CompactTextString(m) }
func (*TrustRequest) ProtoMessage()    {}
func (*TrustRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{7}
}

func (m *TrustRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustRequest.Unmarshal(m, b)
}
func (m *TrustRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustRequest.Marshal(b, m, deterministic)
}
func (m *TrustRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustRequest.Merge(m, src)
}
func (m *TrustRequest) XXX_Size() int {
	return xxx_messageInfo_TrustRequest.Size(m)
}
func (m *TrustRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrustRequest proto.InternalMessageInfo

func (m *TrustRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *TrustRequest) GetRandomKey() []byte {
	if m != nil {
		return m.RandomKey
	}
	return nil
}

func (m *TrustRequest) GetSpamBuff() []byte {
	if m != nil {
		return m.SpamBuff
	}
	return nil
}

type TrustResp struct {
	BaseResponse         *BaseResponse      `protobuf:"bytes,1,req,name=BaseResponse" json:"BaseResponse,omitempty"`
	TrustResponseData    *TrustResponseData `protobuf:"bytes,2,opt,name=TrustResponseData" json:"TrustResponseData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TrustResp) Reset()         { *m = TrustResp{} }
func (m *TrustResp) String() string { return proto.CompactTextString(m) }
func (*TrustResp) ProtoMessage()    {}
func (*TrustResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{8}
}

func (m *TrustResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustResp.Unmarshal(m, b)
}
func (m *TrustResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustResp.Marshal(b, m, deterministic)
}
func (m *TrustResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustResp.Merge(m, src)
}
func (m *TrustResp) XXX_Size() int {
	return xxx_messageInfo_TrustResp.Size(m)
}
func (m *TrustResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustResp.DiscardUnknown(m)
}

var xxx_messageInfo_TrustResp proto.InternalMessageInfo

func (m *TrustResp) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *TrustResp) GetTrustResponseData() *TrustResponseData {
	if m != nil {
		return m.TrustResponseData
	}
	return nil
}

type TrustResponseData struct {
	SoftData             *TrustSoftData `protobuf:"bytes,2,opt,name=SoftData" json:"SoftData,omitempty"`
	DeviceToken          *string        `protobuf:"bytes,3,opt,name=DeviceToken" json:"DeviceToken,omitempty"`
	Timestamp            *uint64        `protobuf:"varint,4,opt,name=Timestamp" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TrustResponseData) Reset()         { *m = TrustResponseData{} }
func (m *TrustResponseData) String() string { return proto.CompactTextString(m) }
func (*TrustResponseData) ProtoMessage()    {}
func (*TrustResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{9}
}

func (m *TrustResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustResponseData.Unmarshal(m, b)
}
func (m *TrustResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustResponseData.Marshal(b, m, deterministic)
}
func (m *TrustResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustResponseData.Merge(m, src)
}
func (m *TrustResponseData) XXX_Size() int {
	return xxx_messageInfo_TrustResponseData.Size(m)
}
func (m *TrustResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_TrustResponseData proto.InternalMessageInfo

func (m *TrustResponseData) GetSoftData() *TrustSoftData {
	if m != nil {
		return m.SoftData
	}
	return nil
}

func (m *TrustResponseData) GetDeviceToken() string {
	if m != nil && m.DeviceToken != nil {
		return *m.DeviceToken
	}
	return ""
}

func (m *TrustResponseData) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type TrustSoftData struct {
	SoftConfig           *string  `protobuf:"bytes,1,opt,name=SoftConfig" json:"SoftConfig,omitempty"`
	SoftData             []byte   `protobuf:"bytes,2,opt,name=SoftData" json:"SoftData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustSoftData) Reset()         { *m = TrustSoftData{} }
func (m *TrustSoftData) String() string { return proto.CompactTextString(m) }
func (*TrustSoftData) ProtoMessage()    {}
func (*TrustSoftData) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{10}
}

func (m *TrustSoftData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustSoftData.Unmarshal(m, b)
}
func (m *TrustSoftData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustSoftData.Marshal(b, m, deterministic)
}
func (m *TrustSoftData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustSoftData.Merge(m, src)
}
func (m *TrustSoftData) XXX_Size() int {
	return xxx_messageInfo_TrustSoftData.Size(m)
}
func (m *TrustSoftData) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustSoftData.DiscardUnknown(m)
}

var xxx_messageInfo_TrustSoftData proto.InternalMessageInfo

func (m *TrustSoftData) GetSoftConfig() string {
	if m != nil && m.SoftConfig != nil {
		return *m.SoftConfig
	}
	return ""
}

func (m *TrustSoftData) GetSoftData() []byte {
	if m != nil {
		return m.SoftData
	}
	return nil
}

type SendPatRequest struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,req,name=BaseRequest" json:"BaseRequest,omitempty"`
	FromUsername         *string      `protobuf:"bytes,2,opt,name=fromUsername" json:"fromUsername,omitempty"`
	ChatUsername         *string      `protobuf:"bytes,3,opt,name=chatUsername" json:"chatUsername,omitempty"`
	PattedUsername       *string      `protobuf:"bytes,4,opt,name=pattedUsername" json:"pattedUsername,omitempty"`
	ClientMsgId          *string      `protobuf:"bytes,5,opt,name=clientMsgId" json:"clientMsgId,omitempty"`
	Scene                *int64       `protobuf:"varint,6,opt,name=scene" json:"scene,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendPatRequest) Reset()         { *m = SendPatRequest{} }
func (m *SendPatRequest) String() string { return proto.CompactTextString(m) }
func (*SendPatRequest) ProtoMessage()    {}
func (*SendPatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{11}
}

func (m *SendPatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPatRequest.Unmarshal(m, b)
}
func (m *SendPatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPatRequest.Marshal(b, m, deterministic)
}
func (m *SendPatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPatRequest.Merge(m, src)
}
func (m *SendPatRequest) XXX_Size() int {
	return xxx_messageInfo_SendPatRequest.Size(m)
}
func (m *SendPatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPatRequest proto.InternalMessageInfo

func (m *SendPatRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *SendPatRequest) GetFromUsername() string {
	if m != nil && m.FromUsername != nil {
		return *m.FromUsername
	}
	return ""
}

func (m *SendPatRequest) GetChatUsername() string {
	if m != nil && m.ChatUsername != nil {
		return *m.ChatUsername
	}
	return ""
}

func (m *SendPatRequest) GetPattedUsername() string {
	if m != nil && m.PattedUsername != nil {
		return *m.PattedUsername
	}
	return ""
}

func (m *SendPatRequest) GetClientMsgId() string {
	if m != nil && m.ClientMsgId != nil {
		return *m.ClientMsgId
	}
	return ""
}

func (m *SendPatRequest) GetScene() int64 {
	if m != nil && m.Scene != nil {
		return *m.Scene
	}
	return 0
}

type SendPatResponse struct {
	BaseResponse         *BaseResponse `protobuf:"bytes,1,req,name=BaseResponse" json:"BaseResponse,omitempty"`
	PatSuffix            *string       `protobuf:"bytes,4,opt,name=patSuffix" json:"patSuffix,omitempty"`
	SelfMsg              *string       `protobuf:"bytes,3,opt,name=selfMsg" json:"selfMsg,omitempty"`
	MsgId                *int64        `protobuf:"varint,5,opt,name=msgId" json:"msgId,omitempty"`
	PatSuffixVersion     *int64        `protobuf:"varint,6,opt,name=patSuffixVersion" json:"patSuffixVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendPatResponse) Reset()         { *m = SendPatResponse{} }
func (m *SendPatResponse) String() string { return proto.CompactTextString(m) }
func (*SendPatResponse) ProtoMessage()    {}
func (*SendPatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{12}
}

func (m *SendPatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPatResponse.Unmarshal(m, b)
}
func (m *SendPatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPatResponse.Marshal(b, m, deterministic)
}
func (m *SendPatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPatResponse.Merge(m, src)
}
func (m *SendPatResponse) XXX_Size() int {
	return xxx_messageInfo_SendPatResponse.Size(m)
}
func (m *SendPatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendPatResponse proto.InternalMessageInfo

func (m *SendPatResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *SendPatResponse) GetPatSuffix() string {
	if m != nil && m.PatSuffix != nil {
		return *m.PatSuffix
	}
	return ""
}

func (m *SendPatResponse) GetSelfMsg() string {
	if m != nil && m.SelfMsg != nil {
		return *m.SelfMsg
	}
	return ""
}

func (m *SendPatResponse) GetMsgId() int64 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *SendPatResponse) GetPatSuffixVersion() int64 {
	if m != nil && m.PatSuffixVersion != nil {
		return *m.PatSuffixVersion
	}
	return 0
}

type SendPatSetRequest struct {
	Cmd                  *int64   `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	SetPat               *SetPat  `protobuf:"bytes,2,opt,name=setPat" json:"setPat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPatSetRequest) Reset()         { *m = SendPatSetRequest{} }
func (m *SendPatSetRequest) String() string { return proto.CompactTextString(m) }
func (*SendPatSetRequest) ProtoMessage()    {}
func (*SendPatSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{13}
}

func (m *SendPatSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPatSetRequest.Unmarshal(m, b)
}
func (m *SendPatSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPatSetRequest.Marshal(b, m, deterministic)
}
func (m *SendPatSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPatSetRequest.Merge(m, src)
}
func (m *SendPatSetRequest) XXX_Size() int {
	return xxx_messageInfo_SendPatSetRequest.Size(m)
}
func (m *SendPatSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPatSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPatSetRequest proto.InternalMessageInfo

func (m *SendPatSetRequest) GetCmd() int64 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *SendPatSetRequest) GetSetPat() *SetPat {
	if m != nil {
		return m.SetPat
	}
	return nil
}

type SetPat struct {
	CmId                 *int64   `protobuf:"varint,1,opt,name=cmId" json:"cmId,omitempty"`
	PatMod               *PatMod  `protobuf:"bytes,2,opt,name=patMod" json:"patMod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPat) Reset()         { *m = SetPat{} }
func (m *SetPat) String() string { return proto.CompactTextString(m) }
func (*SetPat) ProtoMessage()    {}
func (*SetPat) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{14}
}

func (m *SetPat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPat.Unmarshal(m, b)
}
func (m *SetPat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPat.Marshal(b, m, deterministic)
}
func (m *SetPat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPat.Merge(m, src)
}
func (m *SetPat) XXX_Size() int {
	return xxx_messageInfo_SetPat.Size(m)
}
func (m *SetPat) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPat.DiscardUnknown(m)
}

var xxx_messageInfo_SetPat proto.InternalMessageInfo

func (m *SetPat) GetCmId() int64 {
	if m != nil && m.CmId != nil {
		return *m.CmId
	}
	return 0
}

func (m *SetPat) GetPatMod() *PatMod {
	if m != nil {
		return m.PatMod
	}
	return nil
}

type PatMod struct {
	Value                *int64   `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatMod) Reset()         { *m = PatMod{} }
func (m *PatMod) String() string { return proto.CompactTextString(m) }
func (*PatMod) ProtoMessage()    {}
func (*PatMod) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{15}
}

func (m *PatMod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatMod.Unmarshal(m, b)
}
func (m *PatMod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatMod.Marshal(b, m, deterministic)
}
func (m *PatMod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatMod.Merge(m, src)
}
func (m *PatMod) XXX_Size() int {
	return xxx_messageInfo_PatMod.Size(m)
}
func (m *PatMod) XXX_DiscardUnknown() {
	xxx_messageInfo_PatMod.DiscardUnknown(m)
}

var xxx_messageInfo_PatMod proto.InternalMessageInfo

func (m *PatMod) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *PatMod) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type SnsObjectOpExt struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnsObjectOpExt) Reset()         { *m = SnsObjectOpExt{} }
func (m *SnsObjectOpExt) String() string { return proto.CompactTextString(m) }
func (*SnsObjectOpExt) ProtoMessage()    {}
func (*SnsObjectOpExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_65322053f6e72012, []int{16}
}

func (m *SnsObjectOpExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnsObjectOpExt.Unmarshal(m, b)
}
func (m *SnsObjectOpExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnsObjectOpExt.Marshal(b, m, deterministic)
}
func (m *SnsObjectOpExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnsObjectOpExt.Merge(m, src)
}
func (m *SnsObjectOpExt) XXX_Size() int {
	return xxx_messageInfo_SnsObjectOpExt.Size(m)
}
func (m *SnsObjectOpExt) XXX_DiscardUnknown() {
	xxx_messageInfo_SnsObjectOpExt.DiscardUnknown(m)
}

var xxx_messageInfo_SnsObjectOpExt proto.InternalMessageInfo

func (m *SnsObjectOpExt) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*FPFresh)(nil), "wechat_proto.FPFresh")
	proto.RegisterType((*SaeInfoAndroid)(nil), "wechat_proto.SaeInfoAndroid")
	proto.RegisterType((*ZTData)(nil), "wechat_proto.ZTData")
	proto.RegisterType((*DeviceRunningInfos)(nil), "wechat_proto.DeviceRunningInfos")
	proto.RegisterType((*TrustDeviceInfo)(nil), "wechat_proto.TrustDeviceInfo")
	proto.RegisterType((*TrustReq)(nil), "wechat_proto.TrustReq")
	proto.RegisterType((*TrustData)(nil), "wechat_proto.TrustData")
	proto.RegisterType((*TrustRequest)(nil), "wechat_proto.TrustRequest")
	proto.RegisterType((*TrustResp)(nil), "wechat_proto.TrustResp")
	proto.RegisterType((*TrustResponseData)(nil), "wechat_proto.TrustResponseData")
	proto.RegisterType((*TrustSoftData)(nil), "wechat_proto.TrustSoftData")
	proto.RegisterType((*SendPatRequest)(nil), "wechat_proto.SendPatRequest")
	proto.RegisterType((*SendPatResponse)(nil), "wechat_proto.SendPatResponse")
	proto.RegisterType((*SendPatSetRequest)(nil), "wechat_proto.SendPatSetRequest")
	proto.RegisterType((*SetPat)(nil), "wechat_proto.SetPat")
	proto.RegisterType((*PatMod)(nil), "wechat_proto.PatMod")
	proto.RegisterType((*SnsObjectOpExt)(nil), "wechat_proto.SnsObjectOpExt")
}

func init() { proto.RegisterFile("extinfo.proto", fileDescriptor_65322053f6e72012) }

var fileDescriptor_65322053f6e72012 = []byte{
	// 887 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xdc, 0x44,
	0x14, 0x95, 0x77, 0x37, 0xdb, 0xec, 0x5d, 0x27, 0x4d, 0x47, 0x15, 0x98, 0x50, 0x60, 0x35, 0x0f,
	0x10, 0x21, 0x94, 0x8a, 0x8d, 0x0a, 0x0f, 0x45, 0x48, 0x84, 0xb4, 0x52, 0x88, 0xa2, 0x44, 0xe3,
	0x4d, 0x85, 0xf2, 0x82, 0xa6, 0xeb, 0xeb, 0xd4, 0x74, 0x3d, 0x76, 0x3d, 0xb3, 0x6d, 0xc2, 0x3b,
	0x6f, 0x88, 0x1f, 0x80, 0xf8, 0x25, 0xfc, 0x04, 0xf8, 0x3d, 0xbc, 0xa3, 0x3b, 0x33, 0xfe, 0xd8,
	0x76, 0x45, 0x1f, 0xe0, 0x6d, 0xee, 0xf1, 0x99, 0x33, 0xe7, 0x5e, 0x1f, 0x8f, 0x61, 0x0b, 0xaf,
	0x4d, 0xa6, 0xd2, 0x62, 0xbf, 0xac, 0x0a, 0x53, 0xb0, 0xf0, 0x15, 0xce, 0x9f, 0x49, 0xf3, 0x83,
	0xad, 0x76, 0x7d, 0xe5, 0x9e, 0xf1, 0x5f, 0x03, 0xb8, 0xf5, 0xf8, 0xfc, 0x71, 0x85, 0xfa, 0x19,
	0x7b, 0x08, 0xe3, 0xa7, 0x52, 0xa3, 0xc0, 0x17, 0x4b, 0xd4, 0x26, 0x0a, 0x26, 0xc1, 0xde, 0x78,
	0xfa, 0xde, 0x7e, 0x77, 0xf7, 0xfe, 0x61, 0x4b, 0x10, 0x5d, 0x36, 0x8b, 0xe0, 0x56, 0x8c, 0x5a,
	0x9f, 0xe0, 0x4d, 0xd4, 0x9b, 0x04, 0x7b, 0xa1, 0xa8, 0x4b, 0xf6, 0x19, 0x0c, 0x2f, 0x4d, 0x22,
	0x8d, 0x8c, 0xfa, 0x56, 0xf1, 0xee, 0xaa, 0xe2, 0xe5, 0xec, 0x48, 0x1a, 0x29, 0x3c, 0x87, 0xff,
	0x19, 0xc0, 0x76, 0x2c, 0xf1, 0x58, 0xa5, 0xc5, 0x37, 0x2a, 0xa9, 0x8a, 0x2c, 0x61, 0x3b, 0xd0,
	0x7f, 0x82, 0x95, 0xf5, 0x33, 0x12, 0xb4, 0xa4, 0xc3, 0x8e, 0x55, 0x66, 0x3a, 0x87, 0xf9, 0x92,
	0xdd, 0x83, 0xd1, 0xac, 0x30, 0x72, 0x11, 0x67, 0x3f, 0xa1, 0x3d, 0x6f, 0x43, 0xb4, 0x00, 0xed,
	0xfb, 0xbe, 0xa8, 0x4e, 0xf0, 0xe6, 0xf3, 0x68, 0xe4, 0xf6, 0xf9, 0x92, 0x31, 0x18, 0x58, 0x18,
	0x2c, 0x6c, 0xd7, 0x2d, 0x7b, 0x1a, 0x8d, 0xbb, 0xec, 0xa9, 0x67, 0x4f, 0xa3, 0xb0, 0x61, 0xd7,
	0xd8, 0x41, 0xc4, 0x1a, 0xec, 0x80, 0xff, 0x1e, 0xc0, 0xd0, 0xf5, 0x47, 0x62, 0x4f, 0xb0, 0xd2,
	0x59, 0xa1, 0x6c, 0x23, 0xa1, 0xa8, 0x4b, 0xb2, 0xfc, 0x48, 0xcd, 0xab, 0x9b, 0xd2, 0x60, 0x62,
	0xdb, 0x19, 0x88, 0x16, 0x20, 0xd9, 0xa3, 0x7a, 0x76, 0xa1, 0xb0, 0x6b, 0xdb, 0x64, 0x96, 0x63,
	0x6c, 0x64, 0x5e, 0x46, 0x83, 0x49, 0xb0, 0xd7, 0x17, 0x2d, 0xc0, 0xde, 0x81, 0xe1, 0x59, 0x39,
	0xbb, 0x29, 0x31, 0xda, 0xb0, 0x62, 0xbe, 0xa2, 0x31, 0x5e, 0x64, 0x2a, 0x1a, 0x5a, 0x90, 0x96,
	0xfc, 0x8f, 0x00, 0xd8, 0x11, 0xbe, 0xcc, 0xe6, 0x28, 0x96, 0x4a, 0x65, 0xea, 0x8a, 0xa6, 0xae,
	0xff, 0xc5, 0x2a, 0x83, 0x81, 0x15, 0xee, 0xd9, 0x33, 0xed, 0x9a, 0x4d, 0x60, 0xec, 0xdd, 0x76,
	0x7c, 0x76, 0xa1, 0xb7, 0xd8, 0xdd, 0x85, 0xcd, 0x0b, 0xf5, 0x5c, 0x15, 0xaf, 0xd4, 0x03, 0x6f,
	0xb8, 0xa9, 0x3b, 0xcf, 0xbe, 0xf0, 0xbe, 0x9b, 0x9a, 0x3f, 0x80, 0xdb, 0xb3, 0x6a, 0xa9, 0x8d,
	0x6b, 0x80, 0x9c, 0x53, 0x87, 0x14, 0x09, 0x1f, 0x14, 0x8a, 0x03, 0x45, 0x47, 0x2e, 0xac, 0x5f,
	0x8a, 0x8e, 0x5c, 0xf0, 0x03, 0xd8, 0xb4, 0xdb, 0x04, 0xbe, 0x60, 0x9f, 0x40, 0x6f, 0x96, 0xf8,
	0x9c, 0xbf, 0xbb, 0x9a, 0x4a, 0x27, 0x4d, 0xc1, 0xec, 0xcd, 0x12, 0xfe, 0x15, 0x8c, 0x1a, 0x80,
	0xdd, 0x87, 0xfe, 0x2c, 0xc9, 0xa2, 0x60, 0xd2, 0xdf, 0x1b, 0x4f, 0x3f, 0x58, 0xb7, 0xad, 0x71,
	0x24, 0x88, 0xc9, 0x7f, 0x0e, 0x20, 0xac, 0xcf, 0xb4, 0xdf, 0xca, 0x43, 0x18, 0x1f, 0xae, 0x7c,
	0x68, 0xbd, 0xb7, 0x7c, 0x68, 0x9d, 0x82, 0xa6, 0x29, 0xa4, 0x4a, 0x8a, 0xbc, 0x4d, 0x7f, 0x0b,
	0xd0, 0xc4, 0x74, 0x29, 0xf3, 0xc3, 0x65, 0x9a, 0xfa, 0x57, 0xd1, 0xd4, 0xfc, 0xb7, 0xc0, 0xb7,
	0x21, 0x50, 0x97, 0xec, 0x6b, 0x08, 0x9d, 0xac, 0x2e, 0x0b, 0xa5, 0xd1, 0xbb, 0xd8, 0x5d, 0xe7,
	0xc2, 0x31, 0xc4, 0x0a, 0x9f, 0x9d, 0xc2, 0x9d, 0x46, 0x8c, 0x00, 0xfb, 0xf6, 0x7b, 0x76, 0x96,
	0x1f, 0xad, 0x19, 0x4a, 0x97, 0x26, 0xde, 0xdc, 0xc9, 0x7f, 0x09, 0xd6, 0xe8, 0xb1, 0x2f, 0x61,
	0x33, 0x2e, 0x52, 0xd3, 0xd1, 0x7e, 0x7f, 0x8d, 0x76, 0x4d, 0x11, 0x0d, 0x99, 0x52, 0xe9, 0x5e,
	0xc3, 0xac, 0x78, 0x8e, 0xca, 0x8e, 0x62, 0x24, 0xba, 0x50, 0x9d, 0x4a, 0xdd, 0xa4, 0x72, 0x20,
	0x5a, 0x80, 0x9f, 0xc0, 0xd6, 0x8a, 0x34, 0xfb, 0x10, 0x80, 0xd6, 0xdf, 0x16, 0x2a, 0xcd, 0xae,
	0x7c, 0xc4, 0x3a, 0x08, 0x0d, 0x7e, 0xc5, 0x69, 0xd8, 0x9a, 0xe1, 0x7f, 0xd3, 0x9d, 0x86, 0x2a,
	0x39, 0x97, 0xff, 0x4f, 0x04, 0x38, 0x84, 0x69, 0x55, 0xe4, 0x17, 0x1a, 0x2b, 0x25, 0x73, 0xf4,
	0xf1, 0x5e, 0xc1, 0x88, 0x43, 0x52, 0x0d, 0xc7, 0x4d, 0x60, 0x05, 0x63, 0x1f, 0xc3, 0x76, 0x29,
	0x8d, 0xc1, 0xa4, 0x61, 0x0d, 0x2c, 0xeb, 0x35, 0x94, 0x86, 0x39, 0x5f, 0x64, 0xa8, 0xcc, 0xa9,
	0xbe, 0x3a, 0x4e, 0xec, 0x57, 0x3a, 0x12, 0x5d, 0x88, 0xdd, 0x85, 0x0d, 0x3d, 0x47, 0x85, 0xf6,
	0x2b, 0xed, 0x0b, 0x57, 0xf0, 0xbf, 0x02, 0xb8, 0xdd, 0xf4, 0xed, 0x63, 0xf3, 0x5f, 0x63, 0x77,
	0x0f, 0x46, 0xa5, 0x34, 0xf1, 0x32, 0x4d, 0xb3, 0x6b, 0x6f, 0xb7, 0x05, 0xe8, 0xea, 0xd2, 0xb8,
	0x48, 0x4f, 0xf5, 0x95, 0x6f, 0xb8, 0x2e, 0xc9, 0x61, 0xde, 0xb8, 0xef, 0x0b, 0x57, 0xb0, 0x4f,
	0x61, 0xa7, 0xd9, 0x5c, 0xdf, 0x79, 0xae, 0x85, 0x37, 0x70, 0x1e, 0xc3, 0x1d, 0xdf, 0x4c, 0x8c,
	0xcd, 0x7b, 0xdc, 0x81, 0xfe, 0x3c, 0x77, 0x77, 0x48, 0x5f, 0xd0, 0x92, 0x7e, 0x77, 0x1a, 0xcd,
	0xb9, 0x34, 0x3e, 0xb0, 0xaf, 0xfd, 0xee, 0x62, 0xfb, 0x4c, 0x78, 0x0e, 0xff, 0x0e, 0x86, 0x0e,
	0xa1, 0xbb, 0x75, 0x9e, 0x1f, 0xd7, 0x52, 0x76, 0x4d, 0x5a, 0xa5, 0x34, 0xa7, 0x45, 0xb2, 0x5e,
	0xeb, 0xdc, 0x3e, 0x13, 0x9e, 0xc3, 0xa7, 0x30, 0x74, 0x08, 0x35, 0xfb, 0x52, 0x2e, 0x96, 0xe8,
	0xc5, 0x5c, 0x41, 0x27, 0x74, 0xe2, 0x62, 0xd7, 0x7c, 0x02, 0xdb, 0xb1, 0xd2, 0x67, 0x4f, 0x7f,
	0xc4, 0xb9, 0x39, 0x2b, 0x1f, 0x5d, 0x1b, 0xb6, 0x0d, 0xbd, 0xcc, 0xb9, 0xd8, 0x12, 0xbd, 0x2c,
	0x39, 0x1c, 0x5f, 0x8e, 0xf6, 0xf7, 0xef, 0xbb, 0x73, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe8,
	0xea, 0xa3, 0x99, 0x5a, 0x08, 0x00, 0x00,
}
