// Code generated by protoc-gen-go. DO NOT EDIT.
// source: favitem.proto

package wechat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FavSyncRequest struct {
	Selector             *uint32           `protobuf:"varint,1,opt,name=selector" json:"selector,omitempty"`
	KeyBuf               *SKBuiltinString_ `protobuf:"bytes,3,opt,name=keyBuf" json:"keyBuf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FavSyncRequest) Reset()         { *m = FavSyncRequest{} }
func (m *FavSyncRequest) String() string { return proto.CompactTextString(m) }
func (*FavSyncRequest) ProtoMessage()    {}
func (*FavSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{0}
}

func (m *FavSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavSyncRequest.Unmarshal(m, b)
}
func (m *FavSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavSyncRequest.Marshal(b, m, deterministic)
}
func (m *FavSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavSyncRequest.Merge(m, src)
}
func (m *FavSyncRequest) XXX_Size() int {
	return xxx_messageInfo_FavSyncRequest.Size(m)
}
func (m *FavSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FavSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FavSyncRequest proto.InternalMessageInfo

func (m *FavSyncRequest) GetSelector() uint32 {
	if m != nil && m.Selector != nil {
		return *m.Selector
	}
	return 0
}

func (m *FavSyncRequest) GetKeyBuf() *SKBuiltinString_ {
	if m != nil {
		return m.KeyBuf
	}
	return nil
}

type SyncResponse struct {
	Ret    int32
	List   []AddFavItem
	KeyBuf SKBuiltinString_
}

type FavSyncResponse struct {
	Ret                  *int32            `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	CmdList              *CmdList          `protobuf:"bytes,2,opt,name=cmdList" json:"cmdList,omitempty"`
	KeyBuf               *SKBuiltinString_ `protobuf:"bytes,3,opt,name=keyBuf" json:"keyBuf,omitempty"`
	ContinueFlag         *uint32           `protobuf:"varint,4,opt,name=continueFlag" json:"continueFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FavSyncResponse) Reset()         { *m = FavSyncResponse{} }
func (m *FavSyncResponse) String() string { return proto.CompactTextString(m) }
func (*FavSyncResponse) ProtoMessage()    {}
func (*FavSyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{1}
}

func (m *FavSyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavSyncResponse.Unmarshal(m, b)
}
func (m *FavSyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavSyncResponse.Marshal(b, m, deterministic)
}
func (m *FavSyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavSyncResponse.Merge(m, src)
}
func (m *FavSyncResponse) XXX_Size() int {
	return xxx_messageInfo_FavSyncResponse.Size(m)
}
func (m *FavSyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FavSyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FavSyncResponse proto.InternalMessageInfo

func (m *FavSyncResponse) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *FavSyncResponse) GetCmdList() *CmdList {
	if m != nil {
		return m.CmdList
	}
	return nil
}

func (m *FavSyncResponse) GetKeyBuf() *SKBuiltinString_ {
	if m != nil {
		return m.KeyBuf
	}
	return nil
}

func (m *FavSyncResponse) GetContinueFlag() uint32 {
	if m != nil && m.ContinueFlag != nil {
		return *m.ContinueFlag
	}
	return 0
}

type BatchDelFavItemRequest struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	Count                *uint32      `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	FavIdList            []byte       `protobuf:"bytes,3,opt,name=favIdList" json:"favIdList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BatchDelFavItemRequest) Reset()         { *m = BatchDelFavItemRequest{} }
func (m *BatchDelFavItemRequest) String() string { return proto.CompactTextString(m) }
func (*BatchDelFavItemRequest) ProtoMessage()    {}
func (*BatchDelFavItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{2}
}

func (m *BatchDelFavItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDelFavItemRequest.Unmarshal(m, b)
}
func (m *BatchDelFavItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDelFavItemRequest.Marshal(b, m, deterministic)
}
func (m *BatchDelFavItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDelFavItemRequest.Merge(m, src)
}
func (m *BatchDelFavItemRequest) XXX_Size() int {
	return xxx_messageInfo_BatchDelFavItemRequest.Size(m)
}
func (m *BatchDelFavItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDelFavItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDelFavItemRequest proto.InternalMessageInfo

func (m *BatchDelFavItemRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *BatchDelFavItemRequest) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *BatchDelFavItemRequest) GetFavIdList() []byte {
	if m != nil {
		return m.FavIdList
	}
	return nil
}

type BatchDelFavItemResponse struct {
	BaseResponse         *BaseResponse    `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	Count                *uint32          `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	List                 []*DelFavItemRsp `protobuf:"bytes,3,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BatchDelFavItemResponse) Reset()         { *m = BatchDelFavItemResponse{} }
func (m *BatchDelFavItemResponse) String() string { return proto.CompactTextString(m) }
func (*BatchDelFavItemResponse) ProtoMessage()    {}
func (*BatchDelFavItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{3}
}

func (m *BatchDelFavItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDelFavItemResponse.Unmarshal(m, b)
}
func (m *BatchDelFavItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDelFavItemResponse.Marshal(b, m, deterministic)
}
func (m *BatchDelFavItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDelFavItemResponse.Merge(m, src)
}
func (m *BatchDelFavItemResponse) XXX_Size() int {
	return xxx_messageInfo_BatchDelFavItemResponse.Size(m)
}
func (m *BatchDelFavItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDelFavItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDelFavItemResponse proto.InternalMessageInfo

func (m *BatchDelFavItemResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *BatchDelFavItemResponse) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *BatchDelFavItemResponse) GetList() []*DelFavItemRsp {
	if m != nil {
		return m.List
	}
	return nil
}

type BatchGetFavItemRequest struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	Count                *uint32      `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	FavIdList            []byte       `protobuf:"bytes,3,opt,name=favIdList" json:"favIdList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BatchGetFavItemRequest) Reset()         { *m = BatchGetFavItemRequest{} }
func (m *BatchGetFavItemRequest) String() string { return proto.CompactTextString(m) }
func (*BatchGetFavItemRequest) ProtoMessage()    {}
func (*BatchGetFavItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{4}
}

func (m *BatchGetFavItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetFavItemRequest.Unmarshal(m, b)
}
func (m *BatchGetFavItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetFavItemRequest.Marshal(b, m, deterministic)
}
func (m *BatchGetFavItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetFavItemRequest.Merge(m, src)
}
func (m *BatchGetFavItemRequest) XXX_Size() int {
	return xxx_messageInfo_BatchGetFavItemRequest.Size(m)
}
func (m *BatchGetFavItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetFavItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetFavItemRequest proto.InternalMessageInfo

func (m *BatchGetFavItemRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *BatchGetFavItemRequest) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *BatchGetFavItemRequest) GetFavIdList() []byte {
	if m != nil {
		return m.FavIdList
	}
	return nil
}

type BatchGetFavItemResponse struct {
	BaseResponse         *BaseResponse `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	Count                *uint32       `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	ObjectList           []*FavObject  `protobuf:"bytes,3,rep,name=objectList" json:"objectList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BatchGetFavItemResponse) Reset()         { *m = BatchGetFavItemResponse{} }
func (m *BatchGetFavItemResponse) String() string { return proto.CompactTextString(m) }
func (*BatchGetFavItemResponse) ProtoMessage()    {}
func (*BatchGetFavItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{5}
}

func (m *BatchGetFavItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetFavItemResponse.Unmarshal(m, b)
}
func (m *BatchGetFavItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetFavItemResponse.Marshal(b, m, deterministic)
}
func (m *BatchGetFavItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetFavItemResponse.Merge(m, src)
}
func (m *BatchGetFavItemResponse) XXX_Size() int {
	return xxx_messageInfo_BatchGetFavItemResponse.Size(m)
}
func (m *BatchGetFavItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetFavItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetFavItemResponse proto.InternalMessageInfo

func (m *BatchGetFavItemResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *BatchGetFavItemResponse) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *BatchGetFavItemResponse) GetObjectList() []*FavObject {
	if m != nil {
		return m.ObjectList
	}
	return nil
}

type AddFavItem struct {
	FavId                *uint32  `protobuf:"varint,1,opt,name=favId" json:"favId,omitempty"`
	Type                 *uint32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Flag                 *uint32  `protobuf:"varint,3,opt,name=flag" json:"flag,omitempty"`
	UpdateTime           *uint32  `protobuf:"varint,4,opt,name=updateTime" json:"updateTime,omitempty"`
	UpdateSeq            *uint32  `protobuf:"varint,5,opt,name=updateSeq" json:"updateSeq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFavItem) Reset()         { *m = AddFavItem{} }
func (m *AddFavItem) String() string { return proto.CompactTextString(m) }
func (*AddFavItem) ProtoMessage()    {}
func (*AddFavItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{6}
}

func (m *AddFavItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFavItem.Unmarshal(m, b)
}
func (m *AddFavItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFavItem.Marshal(b, m, deterministic)
}
func (m *AddFavItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFavItem.Merge(m, src)
}
func (m *AddFavItem) XXX_Size() int {
	return xxx_messageInfo_AddFavItem.Size(m)
}
func (m *AddFavItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFavItem.DiscardUnknown(m)
}

var xxx_messageInfo_AddFavItem proto.InternalMessageInfo

func (m *AddFavItem) GetFavId() uint32 {
	if m != nil && m.FavId != nil {
		return *m.FavId
	}
	return 0
}

func (m *AddFavItem) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AddFavItem) GetFlag() uint32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *AddFavItem) GetUpdateTime() uint32 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *AddFavItem) GetUpdateSeq() uint32 {
	if m != nil && m.UpdateSeq != nil {
		return *m.UpdateSeq
	}
	return 0
}

type GetFavInfoRequest struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetFavInfoRequest) Reset()         { *m = GetFavInfoRequest{} }
func (m *GetFavInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetFavInfoRequest) ProtoMessage()    {}
func (*GetFavInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{7}
}

func (m *GetFavInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFavInfoRequest.Unmarshal(m, b)
}
func (m *GetFavInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFavInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetFavInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFavInfoRequest.Merge(m, src)
}
func (m *GetFavInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetFavInfoRequest.Size(m)
}
func (m *GetFavInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFavInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFavInfoRequest proto.InternalMessageInfo

func (m *GetFavInfoRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

type GetFavInfoResponse struct {
	BaseResponse         *BaseResponse `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	UsedSize             *uint64       `protobuf:"varint,2,opt,name=usedSize" json:"usedSize,omitempty"`
	TotalSize            *uint64       `protobuf:"varint,3,opt,name=totalSize" json:"totalSize,omitempty"`
	MxFavFileSize        *uint32       `protobuf:"varint,4,opt,name=mxFavFileSize" json:"mxFavFileSize,omitempty"`
	MxAutoUploadSize     *uint32       `protobuf:"varint,5,opt,name=mxAutoUploadSize" json:"mxAutoUploadSize,omitempty"`
	MxAutoDownloadSize   *uint32       `protobuf:"varint,6,opt,name=mxAutoDownloadSize" json:"mxAutoDownloadSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetFavInfoResponse) Reset()         { *m = GetFavInfoResponse{} }
func (m *GetFavInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetFavInfoResponse) ProtoMessage()    {}
func (*GetFavInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{8}
}

func (m *GetFavInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFavInfoResponse.Unmarshal(m, b)
}
func (m *GetFavInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFavInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetFavInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFavInfoResponse.Merge(m, src)
}
func (m *GetFavInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetFavInfoResponse.Size(m)
}
func (m *GetFavInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFavInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFavInfoResponse proto.InternalMessageInfo

func (m *GetFavInfoResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *GetFavInfoResponse) GetUsedSize() uint64 {
	if m != nil && m.UsedSize != nil {
		return *m.UsedSize
	}
	return 0
}

func (m *GetFavInfoResponse) GetTotalSize() uint64 {
	if m != nil && m.TotalSize != nil {
		return *m.TotalSize
	}
	return 0
}

func (m *GetFavInfoResponse) GetMxFavFileSize() uint32 {
	if m != nil && m.MxFavFileSize != nil {
		return *m.MxFavFileSize
	}
	return 0
}

func (m *GetFavInfoResponse) GetMxAutoUploadSize() uint32 {
	if m != nil && m.MxAutoUploadSize != nil {
		return *m.MxAutoUploadSize
	}
	return 0
}

func (m *GetFavInfoResponse) GetMxAutoDownloadSize() uint32 {
	if m != nil && m.MxAutoDownloadSize != nil {
		return *m.MxAutoDownloadSize
	}
	return 0
}

type AddFavItemRequest struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	ClientId             *string      `protobuf:"bytes,2,opt,name=clientId" json:"clientId,omitempty"`
	Type                 *uint32      `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	SourceType           *uint32      `protobuf:"varint,4,opt,name=sourceType" json:"sourceType,omitempty"`
	SourceId             *string      `protobuf:"bytes,5,opt,name=sourceId" json:"sourceId,omitempty"`
	Object               *string      `protobuf:"bytes,6,opt,name=object" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddFavItemRequest) Reset()         { *m = AddFavItemRequest{} }
func (m *AddFavItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddFavItemRequest) ProtoMessage()    {}
func (*AddFavItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{9}
}

func (m *AddFavItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFavItemRequest.Unmarshal(m, b)
}
func (m *AddFavItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFavItemRequest.Marshal(b, m, deterministic)
}
func (m *AddFavItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFavItemRequest.Merge(m, src)
}
func (m *AddFavItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddFavItemRequest.Size(m)
}
func (m *AddFavItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFavItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFavItemRequest proto.InternalMessageInfo

func (m *AddFavItemRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *AddFavItemRequest) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *AddFavItemRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AddFavItemRequest) GetSourceType() uint32 {
	if m != nil && m.SourceType != nil {
		return *m.SourceType
	}
	return 0
}

func (m *AddFavItemRequest) GetSourceId() string {
	if m != nil && m.SourceId != nil {
		return *m.SourceId
	}
	return ""
}

func (m *AddFavItemRequest) GetObject() string {
	if m != nil && m.Object != nil {
		return *m.Object
	}
	return ""
}

type AddFavItemResponse struct {
	BaseResponse         *BaseResponse `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	FavId                *uint32       `protobuf:"varint,2,opt,name=favId" json:"favId,omitempty"`
	UpdateSeq            *uint32       `protobuf:"varint,3,opt,name=updateSeq" json:"updateSeq,omitempty"`
	UsedSize             *uint64       `protobuf:"varint,4,opt,name=usedSize" json:"usedSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddFavItemResponse) Reset()         { *m = AddFavItemResponse{} }
func (m *AddFavItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddFavItemResponse) ProtoMessage()    {}
func (*AddFavItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{10}
}

func (m *AddFavItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFavItemResponse.Unmarshal(m, b)
}
func (m *AddFavItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFavItemResponse.Marshal(b, m, deterministic)
}
func (m *AddFavItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFavItemResponse.Merge(m, src)
}
func (m *AddFavItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddFavItemResponse.Size(m)
}
func (m *AddFavItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFavItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFavItemResponse proto.InternalMessageInfo

func (m *AddFavItemResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *AddFavItemResponse) GetFavId() uint32 {
	if m != nil && m.FavId != nil {
		return *m.FavId
	}
	return 0
}

func (m *AddFavItemResponse) GetUpdateSeq() uint32 {
	if m != nil && m.UpdateSeq != nil {
		return *m.UpdateSeq
	}
	return 0
}

func (m *AddFavItemResponse) GetUsedSize() uint64 {
	if m != nil && m.UsedSize != nil {
		return *m.UsedSize
	}
	return 0
}

type DelFavItemRsp struct {
	Ret                  *int32   `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	FavId                *uint32  `protobuf:"varint,2,opt,name=favId" json:"favId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelFavItemRsp) Reset()         { *m = DelFavItemRsp{} }
func (m *DelFavItemRsp) String() string { return proto.CompactTextString(m) }
func (*DelFavItemRsp) ProtoMessage()    {}
func (*DelFavItemRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{11}
}

func (m *DelFavItemRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelFavItemRsp.Unmarshal(m, b)
}
func (m *DelFavItemRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelFavItemRsp.Marshal(b, m, deterministic)
}
func (m *DelFavItemRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelFavItemRsp.Merge(m, src)
}
func (m *DelFavItemRsp) XXX_Size() int {
	return xxx_messageInfo_DelFavItemRsp.Size(m)
}
func (m *DelFavItemRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelFavItemRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DelFavItemRsp proto.InternalMessageInfo

func (m *DelFavItemRsp) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *DelFavItemRsp) GetFavId() uint32 {
	if m != nil && m.FavId != nil {
		return *m.FavId
	}
	return 0
}

type FavObject struct {
	FavId                *uint32  `protobuf:"varint,1,opt,name=favId" json:"favId,omitempty"`
	Status               *int32   `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Object               *string  `protobuf:"bytes,3,opt,name=object" json:"object,omitempty"`
	Flag                 *uint32  `protobuf:"varint,4,opt,name=flag" json:"flag,omitempty"`
	UpdateTime           *uint32  `protobuf:"varint,5,opt,name=updateTime" json:"updateTime,omitempty"`
	UpdateSeq            *uint32  `protobuf:"varint,6,opt,name=updateSeq" json:"updateSeq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavObject) Reset()         { *m = FavObject{} }
func (m *FavObject) String() string { return proto.CompactTextString(m) }
func (*FavObject) ProtoMessage()    {}
func (*FavObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_4869785929cd391d, []int{12}
}

func (m *FavObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavObject.Unmarshal(m, b)
}
func (m *FavObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavObject.Marshal(b, m, deterministic)
}
func (m *FavObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavObject.Merge(m, src)
}
func (m *FavObject) XXX_Size() int {
	return xxx_messageInfo_FavObject.Size(m)
}
func (m *FavObject) XXX_DiscardUnknown() {
	xxx_messageInfo_FavObject.DiscardUnknown(m)
}

var xxx_messageInfo_FavObject proto.InternalMessageInfo

func (m *FavObject) GetFavId() uint32 {
	if m != nil && m.FavId != nil {
		return *m.FavId
	}
	return 0
}

func (m *FavObject) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *FavObject) GetObject() string {
	if m != nil && m.Object != nil {
		return *m.Object
	}
	return ""
}

func (m *FavObject) GetFlag() uint32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *FavObject) GetUpdateTime() uint32 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *FavObject) GetUpdateSeq() uint32 {
	if m != nil && m.UpdateSeq != nil {
		return *m.UpdateSeq
	}
	return 0
}

func init() {
	proto.RegisterType((*FavSyncRequest)(nil), "wechat_proto.FavSyncRequest")
	proto.RegisterType((*FavSyncResponse)(nil), "wechat_proto.FavSyncResponse")
	proto.RegisterType((*BatchDelFavItemRequest)(nil), "wechat_proto.BatchDelFavItemRequest")
	proto.RegisterType((*BatchDelFavItemResponse)(nil), "wechat_proto.BatchDelFavItemResponse")
	proto.RegisterType((*BatchGetFavItemRequest)(nil), "wechat_proto.BatchGetFavItemRequest")
	proto.RegisterType((*BatchGetFavItemResponse)(nil), "wechat_proto.BatchGetFavItemResponse")
	proto.RegisterType((*AddFavItem)(nil), "wechat_proto.AddFavItem")
	proto.RegisterType((*GetFavInfoRequest)(nil), "wechat_proto.GetFavInfoRequest")
	proto.RegisterType((*GetFavInfoResponse)(nil), "wechat_proto.GetFavInfoResponse")
	proto.RegisterType((*AddFavItemRequest)(nil), "wechat_proto.AddFavItemRequest")
	proto.RegisterType((*AddFavItemResponse)(nil), "wechat_proto.AddFavItemResponse")
	proto.RegisterType((*DelFavItemRsp)(nil), "wechat_proto.DelFavItemRsp")
	proto.RegisterType((*FavObject)(nil), "wechat_proto.FavObject")
}

func init() { proto.RegisterFile("favitem.proto", fileDescriptor_4869785929cd391d) }

var fileDescriptor_4869785929cd391d = []byte{
	// 674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x96, 0xeb, 0x24, 0x7f, 0x3d, 0x49, 0x7e, 0xda, 0x15, 0xb4, 0x21, 0xa0, 0xaa, 0x5a, 0x71,
	0xa8, 0x38, 0xb8, 0x52, 0x0f, 0xf4, 0x80, 0x84, 0xd4, 0x50, 0x19, 0x45, 0x54, 0x02, 0x6d, 0xca,
	0x85, 0x4b, 0xb5, 0xb5, 0x37, 0xad, 0xc1, 0xf6, 0xba, 0xf1, 0xda, 0x6d, 0x79, 0x02, 0xb8, 0xf1,
	0x08, 0x48, 0x70, 0xe0, 0xc8, 0xc3, 0xf0, 0x40, 0xc8, 0xbb, 0x5b, 0x7b, 0xdd, 0xa6, 0x1c, 0x50,
	0x10, 0x37, 0x7f, 0x33, 0x5f, 0x66, 0xe6, 0xfb, 0x3c, 0xe3, 0x40, 0x7f, 0x4a, 0x8b, 0x50, 0xb0,
	0xd8, 0x4d, 0x67, 0x5c, 0x70, 0xd4, 0x3b, 0x67, 0xfe, 0x29, 0x15, 0x47, 0x12, 0x0d, 0x35, 0x52,
	0x39, 0x1c, 0xc0, 0xff, 0x1e, 0x2d, 0x26, 0x97, 0x89, 0x4f, 0xd8, 0x59, 0xce, 0x32, 0x81, 0x86,
	0xb0, 0x9c, 0xb1, 0x88, 0xf9, 0x82, 0xcf, 0x06, 0xd6, 0xa6, 0xb5, 0xd5, 0x27, 0x15, 0x46, 0x4f,
	0xa0, 0xf3, 0x9e, 0x5d, 0x8e, 0xf2, 0xe9, 0xc0, 0xde, 0xb4, 0xb6, 0xba, 0x3b, 0x1b, 0xae, 0x59,
	0xda, 0x9d, 0xbc, 0x1c, 0xe5, 0x61, 0x24, 0xc2, 0x64, 0x22, 0x66, 0x61, 0x72, 0x72, 0x44, 0x34,
	0x1b, 0xff, 0xb0, 0xe0, 0x4e, 0xd5, 0x26, 0x4b, 0x79, 0x92, 0x31, 0xb4, 0x02, 0xf6, 0x8c, 0x09,
	0xd9, 0xa2, 0x4d, 0xca, 0x47, 0xb4, 0x0d, 0xff, 0xf9, 0x71, 0x70, 0x10, 0x66, 0x62, 0xb0, 0x24,
	0xcb, 0xdf, 0x6b, 0x96, 0x7f, 0xae, 0x92, 0xe4, 0x8a, 0xf5, 0xa7, 0xe3, 0x20, 0x0c, 0x3d, 0x9f,
	0x27, 0x22, 0x4c, 0x72, 0xe6, 0x45, 0xf4, 0x64, 0xd0, 0x92, 0x32, 0x1b, 0x31, 0xfc, 0xc9, 0x82,
	0xb5, 0x11, 0x15, 0xfe, 0xe9, 0x3e, 0x8b, 0x3c, 0x5a, 0x8c, 0x05, 0x8b, 0xaf, 0x1c, 0x7a, 0x0a,
	0xdd, 0x63, 0x9a, 0x31, 0x0d, 0xa5, 0x82, 0xee, 0xce, 0xfd, 0x66, 0xef, 0x51, 0x4d, 0x20, 0x26,
	0x1b, 0xdd, 0x85, 0xb6, 0xcf, 0xf3, 0x44, 0x49, 0xec, 0x13, 0x05, 0xd0, 0x43, 0x70, 0xa6, 0xb4,
	0x18, 0x2b, 0xf1, 0xa5, 0x98, 0x1e, 0xa9, 0x03, 0xf8, 0x8b, 0x05, 0xeb, 0x37, 0x66, 0xd1, 0x36,
	0x3e, 0x83, 0x9e, 0x2a, 0xaf, 0xb0, 0x9e, 0x66, 0x38, 0x6f, 0x1a, 0xc5, 0x20, 0x0d, 0xfe, 0x2d,
	0xf3, 0x6c, 0x43, 0x2b, 0x52, 0xa3, 0xd8, 0x5b, 0xdd, 0x9d, 0x07, 0xcd, 0x6a, 0xc6, 0x14, 0x59,
	0x4a, 0x24, 0xb1, 0xb6, 0xeb, 0x05, 0x13, 0xff, 0xda, 0xae, 0xef, 0x57, 0x76, 0x99, 0xb3, 0xfc,
	0x55, 0xbb, 0x76, 0x01, 0xf8, 0xf1, 0x3b, 0xe6, 0x8b, 0x83, 0xda, 0xb4, 0xf5, 0x66, 0x4d, 0x8f,
	0x16, 0xaf, 0x24, 0x85, 0x18, 0x54, 0xfc, 0xd1, 0x02, 0xd8, 0x0b, 0x02, 0x3d, 0x65, 0x59, 0x5d,
	0xca, 0xd0, 0x87, 0xa7, 0x00, 0x42, 0xd0, 0x12, 0x97, 0x29, 0xd3, 0x2d, 0xe5, 0x73, 0x19, 0x9b,
	0x96, 0xab, 0x6b, 0xab, 0x58, 0xf9, 0x8c, 0x36, 0x00, 0xf2, 0x34, 0xa0, 0x82, 0x1d, 0x86, 0x31,
	0xd3, 0x4b, 0x6d, 0x44, 0x4a, 0xd7, 0x14, 0x9a, 0xb0, 0xb3, 0x41, 0x5b, 0xa6, 0xeb, 0x00, 0x7e,
	0x0d, 0xab, 0xda, 0xaf, 0x64, 0xca, 0x17, 0xf1, 0xee, 0xf0, 0xe7, 0x25, 0x40, 0x66, 0xc9, 0x05,
	0xbd, 0x82, 0x21, 0x2c, 0xe7, 0x19, 0x0b, 0x26, 0xe1, 0x07, 0x65, 0x49, 0x8b, 0x54, 0xb8, 0x94,
	0x28, 0xb8, 0xa0, 0x91, 0x4c, 0xda, 0x32, 0x59, 0x07, 0xd0, 0x23, 0xe8, 0xc7, 0x17, 0x1e, 0x2d,
	0xbc, 0x30, 0x62, 0x92, 0xa1, 0x3c, 0x6a, 0x06, 0xd1, 0x63, 0x58, 0x89, 0x2f, 0xf6, 0x72, 0xc1,
	0xdf, 0xa4, 0x11, 0xa7, 0xaa, 0x8f, 0x72, 0xeb, 0x46, 0x1c, 0xb9, 0x80, 0x54, 0x6c, 0x9f, 0x9f,
	0x27, 0x15, 0xbb, 0x23, 0xd9, 0x73, 0x32, 0xf8, 0xa7, 0x05, 0xab, 0xf5, 0xfb, 0x5e, 0xc8, 0x85,
	0x0c, 0x61, 0xd9, 0x8f, 0x42, 0x96, 0x88, 0x71, 0x20, 0xed, 0x70, 0x48, 0x85, 0xab, 0xcd, 0xb1,
	0x8d, 0xcd, 0xd9, 0x00, 0xc8, 0x78, 0x3e, 0xf3, 0xd9, 0x61, 0x99, 0xd1, 0x5b, 0x52, 0x47, 0xe4,
	0xf7, 0x5f, 0xa2, 0x71, 0x20, 0x65, 0x3b, 0xa4, 0xc2, 0x68, 0x0d, 0x3a, 0x6a, 0x79, 0xa5, 0x44,
	0x87, 0x68, 0x84, 0xbf, 0x59, 0x80, 0x4c, 0x59, 0x8b, 0x3b, 0x36, 0x75, 0x0e, 0x4b, 0xe6, 0x39,
	0x34, 0xd6, 0xd8, 0xbe, 0xb6, 0xc6, 0x8d, 0xed, 0x68, 0x35, 0xb7, 0x03, 0xef, 0x42, 0xbf, 0xf1,
	0xed, 0x9a, 0xf3, 0x1f, 0x34, 0xb7, 0x25, 0xfe, 0x6a, 0x81, 0x53, 0x1d, 0xf0, 0x2d, 0x57, 0xba,
	0x06, 0x9d, 0x4c, 0x50, 0x91, 0x67, 0xf2, 0xa7, 0x6d, 0xa2, 0x91, 0xe1, 0x99, 0x6d, 0x7a, 0x56,
	0x5d, 0x70, 0xeb, 0xd6, 0x0b, 0x6e, 0xff, 0xfe, 0x82, 0x3b, 0xd7, 0xa4, 0x8f, 0xba, 0x6f, 0x1d,
	0xd7, 0xdd, 0x56, 0xe6, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x38, 0x90, 0x5b, 0x04, 0x08,
	0x00, 0x00,
}
