// Code generated by protoc-gen-go. DO NOT EDIT.
// source: findersync.proto

package wechat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FinderSyncRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderSyncRequest) Reset()         { *m = FinderSyncRequest{} }
func (m *FinderSyncRequest) String() string { return proto.CompactTextString(m) }
func (*FinderSyncRequest) ProtoMessage()    {}
func (*FinderSyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{0}
}

func (m *FinderSyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderSyncRequest.Unmarshal(m, b)
}
func (m *FinderSyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderSyncRequest.Marshal(b, m, deterministic)
}
func (m *FinderSyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderSyncRequest.Merge(m, src)
}
func (m *FinderSyncRequest) XXX_Size() int {
	return xxx_messageInfo_FinderSyncRequest.Size(m)
}
func (m *FinderSyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderSyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinderSyncRequest proto.InternalMessageInfo

type FinderStatsReportResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderStatsReportResponse) Reset()         { *m = FinderStatsReportResponse{} }
func (m *FinderStatsReportResponse) String() string { return proto.CompactTextString(m) }
func (*FinderStatsReportResponse) ProtoMessage()    {}
func (*FinderStatsReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{1}
}

func (m *FinderStatsReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderStatsReportResponse.Unmarshal(m, b)
}
func (m *FinderStatsReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderStatsReportResponse.Marshal(b, m, deterministic)
}
func (m *FinderStatsReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderStatsReportResponse.Merge(m, src)
}
func (m *FinderStatsReportResponse) XXX_Size() int {
	return xxx_messageInfo_FinderStatsReportResponse.Size(m)
}
func (m *FinderStatsReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderStatsReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinderStatsReportResponse proto.InternalMessageInfo

type FinderSearchRequest struct {
	BaseRequest          *BaseRequest     `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	UserKey              *string          `protobuf:"bytes,2,opt,name=UserKey" json:"UserKey,omitempty"`
	Offset               *uint32          `protobuf:"varint,3,opt,name=Offset" json:"Offset,omitempty"`
	T                    []byte           `protobuf:"bytes,4,opt,name=T" json:"T,omitempty"`
	Scene                *uint32          `protobuf:"varint,5,opt,name=Scene" json:"Scene,omitempty"`
	Uuid                 *string          `protobuf:"bytes,6,opt,name=QrUuid" json:"QrUuid,omitempty"`
	FinderTxRequest      *FinderTxRequest `protobuf:"bytes,7,opt,name=FinderTxRequest" json:"FinderTxRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FinderSearchRequest) Reset()         { *m = FinderSearchRequest{} }
func (m *FinderSearchRequest) String() string { return proto.CompactTextString(m) }
func (*FinderSearchRequest) ProtoMessage()    {}
func (*FinderSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{2}
}

func (m *FinderSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderSearchRequest.Unmarshal(m, b)
}
func (m *FinderSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderSearchRequest.Marshal(b, m, deterministic)
}
func (m *FinderSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderSearchRequest.Merge(m, src)
}
func (m *FinderSearchRequest) XXX_Size() int {
	return xxx_messageInfo_FinderSearchRequest.Size(m)
}
func (m *FinderSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinderSearchRequest proto.InternalMessageInfo

func (m *FinderSearchRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *FinderSearchRequest) GetUserKey() string {
	if m != nil && m.UserKey != nil {
		return *m.UserKey
	}
	return ""
}

func (m *FinderSearchRequest) GetOffset() uint32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *FinderSearchRequest) GetT() []byte {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *FinderSearchRequest) GetScene() uint32 {
	if m != nil && m.Scene != nil {
		return *m.Scene
	}
	return 0
}

func (m *FinderSearchRequest) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *FinderSearchRequest) GetFinderTxRequest() *FinderTxRequest {
	if m != nil {
		return m.FinderTxRequest
	}
	return nil
}

type FinderTxRequest struct {
	Userver              *int32    `protobuf:"varint,1,opt,name=Userver" json:"Userver,omitempty"`
	Scene                *int32    `protobuf:"varint,2,opt,name=Scene" json:"Scene,omitempty"`
	ExtSpamInfo          []byte    `protobuf:"bytes,3,opt,name=ExtSpamInfo" json:"ExtSpamInfo,omitempty"`
	T                    *int32    `protobuf:"varint,4,opt,name=T" json:"T,omitempty"`
	G                    *FinderZd `protobuf:"bytes,5,opt,name=G" json:"G,omitempty"`
	Tg                   *int64    `protobuf:"varint,6,opt,name=Tg" json:"Tg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FinderTxRequest) Reset()         { *m = FinderTxRequest{} }
func (m *FinderTxRequest) String() string { return proto.CompactTextString(m) }
func (*FinderTxRequest) ProtoMessage()    {}
func (*FinderTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{3}
}

func (m *FinderTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderTxRequest.Unmarshal(m, b)
}
func (m *FinderTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderTxRequest.Marshal(b, m, deterministic)
}
func (m *FinderTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderTxRequest.Merge(m, src)
}
func (m *FinderTxRequest) XXX_Size() int {
	return xxx_messageInfo_FinderTxRequest.Size(m)
}
func (m *FinderTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinderTxRequest proto.InternalMessageInfo

func (m *FinderTxRequest) GetUserver() int32 {
	if m != nil && m.Userver != nil {
		return *m.Userver
	}
	return 0
}

func (m *FinderTxRequest) GetScene() int32 {
	if m != nil && m.Scene != nil {
		return *m.Scene
	}
	return 0
}

func (m *FinderTxRequest) GetExtSpamInfo() []byte {
	if m != nil {
		return m.ExtSpamInfo
	}
	return nil
}

func (m *FinderTxRequest) GetT() int32 {
	if m != nil && m.T != nil {
		return *m.T
	}
	return 0
}

func (m *FinderTxRequest) GetG() *FinderZd {
	if m != nil {
		return m.G
	}
	return nil
}

func (m *FinderTxRequest) GetTg() int64 {
	if m != nil && m.Tg != nil {
		return *m.Tg
	}
	return 0
}

type FinderZd struct {
	G1                   *string  `protobuf:"bytes,1,opt,name=G1" json:"G1,omitempty"`
	G2                   *string  `protobuf:"bytes,2,opt,name=G2" json:"G2,omitempty"`
	G3                   *string  `protobuf:"bytes,3,opt,name=G3" json:"G3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderZd) Reset()         { *m = FinderZd{} }
func (m *FinderZd) String() string { return proto.CompactTextString(m) }
func (*FinderZd) ProtoMessage()    {}
func (*FinderZd) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{4}
}

func (m *FinderZd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderZd.Unmarshal(m, b)
}
func (m *FinderZd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderZd.Marshal(b, m, deterministic)
}
func (m *FinderZd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderZd.Merge(m, src)
}
func (m *FinderZd) XXX_Size() int {
	return xxx_messageInfo_FinderZd.Size(m)
}
func (m *FinderZd) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderZd.DiscardUnknown(m)
}

var xxx_messageInfo_FinderZd proto.InternalMessageInfo

func (m *FinderZd) GetG1() string {
	if m != nil && m.G1 != nil {
		return *m.G1
	}
	return ""
}

func (m *FinderZd) GetG2() string {
	if m != nil && m.G2 != nil {
		return *m.G2
	}
	return ""
}

func (m *FinderZd) GetG3() string {
	if m != nil && m.G3 != nil {
		return *m.G3
	}
	return ""
}

type FinderSearchResponse struct {
	BaseResponse         *BaseResponse `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	Vtm                  []*FinderVtm  `protobuf:"bytes,2,rep,name=Vtm" json:"Vtm,omitempty"`
	Offset               *int32        `protobuf:"varint,3,opt,name=Offset" json:"Offset,omitempty"`
	ContinueFlag         *int32        `protobuf:"varint,4,opt,name=ContinueFlag" json:"ContinueFlag,omitempty"`
	Object               *FinderObject `protobuf:"bytes,5,opt,name=Object" json:"Object,omitempty"`
	T                    []byte        `protobuf:"bytes,6,opt,name=T" json:"T,omitempty"`
	Uuid                 *string       `protobuf:"bytes,7,opt,name=QrUuid" json:"QrUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FinderSearchResponse) Reset()         { *m = FinderSearchResponse{} }
func (m *FinderSearchResponse) String() string { return proto.CompactTextString(m) }
func (*FinderSearchResponse) ProtoMessage()    {}
func (*FinderSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{5}
}

func (m *FinderSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderSearchResponse.Unmarshal(m, b)
}
func (m *FinderSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderSearchResponse.Marshal(b, m, deterministic)
}
func (m *FinderSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderSearchResponse.Merge(m, src)
}
func (m *FinderSearchResponse) XXX_Size() int {
	return xxx_messageInfo_FinderSearchResponse.Size(m)
}
func (m *FinderSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinderSearchResponse proto.InternalMessageInfo

func (m *FinderSearchResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *FinderSearchResponse) GetVtm() []*FinderVtm {
	if m != nil {
		return m.Vtm
	}
	return nil
}

func (m *FinderSearchResponse) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *FinderSearchResponse) GetContinueFlag() int32 {
	if m != nil && m.ContinueFlag != nil {
		return *m.ContinueFlag
	}
	return 0
}

func (m *FinderSearchResponse) GetObject() *FinderObject {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *FinderSearchResponse) GetT() []byte {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *FinderSearchResponse) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

type FinderObject struct {
	Info                 []byte   `protobuf:"bytes,1,opt,name=Info" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderObject) Reset()         { *m = FinderObject{} }
func (m *FinderObject) String() string { return proto.CompactTextString(m) }
func (*FinderObject) ProtoMessage()    {}
func (*FinderObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{6}
}

func (m *FinderObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderObject.Unmarshal(m, b)
}
func (m *FinderObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderObject.Marshal(b, m, deterministic)
}
func (m *FinderObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderObject.Merge(m, src)
}
func (m *FinderObject) XXX_Size() int {
	return xxx_messageInfo_FinderObject.Size(m)
}
func (m *FinderObject) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderObject.DiscardUnknown(m)
}

var xxx_messageInfo_FinderObject proto.InternalMessageInfo

func (m *FinderObject) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

type FinderVtm struct {
	Contact              *FinderContact `protobuf:"bytes,1,opt,name=Contact" json:"Contact,omitempty"`
	Html                 *string        `protobuf:"bytes,2,opt,name=Html" json:"Html,omitempty"`
	Introduc             *string        `protobuf:"bytes,3,opt,name=Introduc" json:"Introduc,omitempty"`
	FansCount            *int32         `protobuf:"varint,4,opt,name=FansCount" json:"FansCount,omitempty"`
	FriendFollow         *int32         `protobuf:"varint,5,opt,name=FriendFollow" json:"FriendFollow,omitempty"`
	GIo                  *string        `protobuf:"bytes,6,opt,name=GIo" json:"GIo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FinderVtm) Reset()         { *m = FinderVtm{} }
func (m *FinderVtm) String() string { return proto.CompactTextString(m) }
func (*FinderVtm) ProtoMessage()    {}
func (*FinderVtm) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{7}
}

func (m *FinderVtm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderVtm.Unmarshal(m, b)
}
func (m *FinderVtm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderVtm.Marshal(b, m, deterministic)
}
func (m *FinderVtm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderVtm.Merge(m, src)
}
func (m *FinderVtm) XXX_Size() int {
	return xxx_messageInfo_FinderVtm.Size(m)
}
func (m *FinderVtm) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderVtm.DiscardUnknown(m)
}

var xxx_messageInfo_FinderVtm proto.InternalMessageInfo

func (m *FinderVtm) GetContact() *FinderContact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *FinderVtm) GetHtml() string {
	if m != nil && m.Html != nil {
		return *m.Html
	}
	return ""
}

func (m *FinderVtm) GetIntroduc() string {
	if m != nil && m.Introduc != nil {
		return *m.Introduc
	}
	return ""
}

func (m *FinderVtm) GetFansCount() int32 {
	if m != nil && m.FansCount != nil {
		return *m.FansCount
	}
	return 0
}

func (m *FinderVtm) GetFriendFollow() int32 {
	if m != nil && m.FriendFollow != nil {
		return *m.FriendFollow
	}
	return 0
}

func (m *FinderVtm) GetGIo() string {
	if m != nil && m.GIo != nil {
		return *m.GIo
	}
	return ""
}

type FinderContact struct {
	Username             *string    `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
	Nickname             *string    `protobuf:"bytes,2,opt,name=Nickname" json:"Nickname,omitempty"`
	HeadUrl              *string    `protobuf:"bytes,3,opt,name=HeadUrl" json:"HeadUrl,omitempty"`
	Seq                  *uint64    `protobuf:"varint,4,opt,name=Seq" json:"Seq,omitempty"`
	Signature            *string    `protobuf:"bytes,5,opt,name=Signature" json:"Signature,omitempty"`
	FollowFlag           *int32     `protobuf:"varint,6,opt,name=FollowFlag" json:"FollowFlag,omitempty"`
	FollowTime           *int32     `protobuf:"varint,7,opt,name=FollowTime" json:"FollowTime,omitempty"`
	AuthInfo             []byte     `protobuf:"bytes,8,opt,name=AuthInfo" json:"AuthInfo,omitempty"`
	CoverImgUrl          *string    `protobuf:"bytes,9,opt,name=CoverImgUrl" json:"CoverImgUrl,omitempty"`
	SpamStatus           *int32     `protobuf:"varint,10,opt,name=SpamStatus" json:"SpamStatus,omitempty"`
	ExtFlag              *int32     `protobuf:"varint,11,opt,name=ExtFlag" json:"ExtFlag,omitempty"`
	ExtInfo              []byte     `protobuf:"bytes,12,opt,name=ExtInfo" json:"ExtInfo,omitempty"`
	OriginalFlag         *int32     `protobuf:"varint,13,opt,name=OriginalFlag" json:"OriginalFlag,omitempty"`
	OriginalInfo         *FinderAqt `protobuf:"bytes,14,opt,name=OriginalInfo" json:"OriginalInfo,omitempty"`
	LiveStatus           *int32     `protobuf:"varint,15,opt,name=LiveStatus" json:"LiveStatus,omitempty"`
	MsgInfo              []byte     `protobuf:"bytes,16,opt,name=MsgInfo" json:"MsgInfo,omitempty"`
	OriginalEntranceFlag *int32     `protobuf:"varint,17,opt,name=OriginalEntranceFlag" json:"OriginalEntranceFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FinderContact) Reset()         { *m = FinderContact{} }
func (m *FinderContact) String() string { return proto.CompactTextString(m) }
func (*FinderContact) ProtoMessage()    {}
func (*FinderContact) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{8}
}

func (m *FinderContact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderContact.Unmarshal(m, b)
}
func (m *FinderContact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderContact.Marshal(b, m, deterministic)
}
func (m *FinderContact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderContact.Merge(m, src)
}
func (m *FinderContact) XXX_Size() int {
	return xxx_messageInfo_FinderContact.Size(m)
}
func (m *FinderContact) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderContact.DiscardUnknown(m)
}

var xxx_messageInfo_FinderContact proto.InternalMessageInfo

func (m *FinderContact) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *FinderContact) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *FinderContact) GetHeadUrl() string {
	if m != nil && m.HeadUrl != nil {
		return *m.HeadUrl
	}
	return ""
}

func (m *FinderContact) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *FinderContact) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *FinderContact) GetFollowFlag() int32 {
	if m != nil && m.FollowFlag != nil {
		return *m.FollowFlag
	}
	return 0
}

func (m *FinderContact) GetFollowTime() int32 {
	if m != nil && m.FollowTime != nil {
		return *m.FollowTime
	}
	return 0
}

func (m *FinderContact) GetAuthInfo() []byte {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

func (m *FinderContact) GetCoverImgUrl() string {
	if m != nil && m.CoverImgUrl != nil {
		return *m.CoverImgUrl
	}
	return ""
}

func (m *FinderContact) GetSpamStatus() int32 {
	if m != nil && m.SpamStatus != nil {
		return *m.SpamStatus
	}
	return 0
}

func (m *FinderContact) GetExtFlag() int32 {
	if m != nil && m.ExtFlag != nil {
		return *m.ExtFlag
	}
	return 0
}

func (m *FinderContact) GetExtInfo() []byte {
	if m != nil {
		return m.ExtInfo
	}
	return nil
}

func (m *FinderContact) GetOriginalFlag() int32 {
	if m != nil && m.OriginalFlag != nil {
		return *m.OriginalFlag
	}
	return 0
}

func (m *FinderContact) GetOriginalInfo() *FinderAqt {
	if m != nil {
		return m.OriginalInfo
	}
	return nil
}

func (m *FinderContact) GetLiveStatus() int32 {
	if m != nil && m.LiveStatus != nil {
		return *m.LiveStatus
	}
	return 0
}

func (m *FinderContact) GetMsgInfo() []byte {
	if m != nil {
		return m.MsgInfo
	}
	return nil
}

func (m *FinderContact) GetOriginalEntranceFlag() int32 {
	if m != nil && m.OriginalEntranceFlag != nil {
		return *m.OriginalEntranceFlag
	}
	return 0
}

type FinderAqt struct {
	G1                   *int32   `protobuf:"varint,1,opt,name=G1" json:"G1,omitempty"`
	G2                   *int32   `protobuf:"varint,2,opt,name=G2" json:"G2,omitempty"`
	G3                   *int32   `protobuf:"varint,3,opt,name=G3" json:"G3,omitempty"`
	G4                   *int32   `protobuf:"varint,4,opt,name=G4" json:"G4,omitempty"`
	G5                   *int32   `protobuf:"varint,5,opt,name=G5" json:"G5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderAqt) Reset()         { *m = FinderAqt{} }
func (m *FinderAqt) String() string { return proto.CompactTextString(m) }
func (*FinderAqt) ProtoMessage()    {}
func (*FinderAqt) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{9}
}

func (m *FinderAqt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderAqt.Unmarshal(m, b)
}
func (m *FinderAqt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderAqt.Marshal(b, m, deterministic)
}
func (m *FinderAqt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderAqt.Merge(m, src)
}
func (m *FinderAqt) XXX_Size() int {
	return xxx_messageInfo_FinderAqt.Size(m)
}
func (m *FinderAqt) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderAqt.DiscardUnknown(m)
}

var xxx_messageInfo_FinderAqt proto.InternalMessageInfo

func (m *FinderAqt) GetG1() int32 {
	if m != nil && m.G1 != nil {
		return *m.G1
	}
	return 0
}

func (m *FinderAqt) GetG2() int32 {
	if m != nil && m.G2 != nil {
		return *m.G2
	}
	return 0
}

func (m *FinderAqt) GetG3() int32 {
	if m != nil && m.G3 != nil {
		return *m.G3
	}
	return 0
}

func (m *FinderAqt) GetG4() int32 {
	if m != nil && m.G4 != nil {
		return *m.G4
	}
	return 0
}

func (m *FinderAqt) GetG5() int32 {
	if m != nil && m.G5 != nil {
		return *m.G5
	}
	return 0
}

type FinderUserPrepareRequest struct {
	BaseRequest          *BaseRequest     `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	Scene                *int32           `protobuf:"varint,2,opt,name=Scene" json:"Scene,omitempty"`
	FinderTxRequest      *FinderTxRequest `protobuf:"bytes,3,opt,name=FinderTxRequest" json:"FinderTxRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FinderUserPrepareRequest) Reset()         { *m = FinderUserPrepareRequest{} }
func (m *FinderUserPrepareRequest) String() string { return proto.CompactTextString(m) }
func (*FinderUserPrepareRequest) ProtoMessage()    {}
func (*FinderUserPrepareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{10}
}

func (m *FinderUserPrepareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderUserPrepareRequest.Unmarshal(m, b)
}
func (m *FinderUserPrepareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderUserPrepareRequest.Marshal(b, m, deterministic)
}
func (m *FinderUserPrepareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderUserPrepareRequest.Merge(m, src)
}
func (m *FinderUserPrepareRequest) XXX_Size() int {
	return xxx_messageInfo_FinderUserPrepareRequest.Size(m)
}
func (m *FinderUserPrepareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderUserPrepareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinderUserPrepareRequest proto.InternalMessageInfo

func (m *FinderUserPrepareRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *FinderUserPrepareRequest) GetScene() int32 {
	if m != nil && m.Scene != nil {
		return *m.Scene
	}
	return 0
}

func (m *FinderUserPrepareRequest) GetFinderTxRequest() *FinderTxRequest {
	if m != nil {
		return m.FinderTxRequest
	}
	return nil
}

type FinderUserPrepareResponse struct {
	BaseResponse          *BaseResponse             `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	ActionType            *int32                    `protobuf:"varint,2,opt,name=ActionType" json:"ActionType,omitempty"`
	VerifyInfo            *FinderNicknameVerifyInfo `protobuf:"bytes,3,opt,name=VerifyInfo" json:"VerifyInfo,omitempty"`
	SelfContact           *FinderContact            `protobuf:"bytes,4,opt,name=SelfContact" json:"SelfContact,omitempty"`
	UserFlag              *int32                    `protobuf:"varint,5,opt,name=UserFlag" json:"UserFlag,omitempty"`
	NicknameModifyWording *string                   `protobuf:"bytes,6,opt,name=NicknameModifyWording" json:"NicknameModifyWording,omitempty"`
	GKc                   *string                   `protobuf:"bytes,7,opt,name=GKc" json:"GKc,omitempty"`
	GKd                   *string                   `protobuf:"bytes,8,opt,name=GKd" json:"GKd,omitempty"`
	GKe                   *int32                    `protobuf:"varint,9,opt,name=GKe" json:"GKe,omitempty"`
	T                     *int32                    `protobuf:"varint,10,opt,name=T" json:"T,omitempty"`
	GKf                   *int32                    `protobuf:"varint,11,opt,name=GKf" json:"GKf,omitempty"`
	G                     *int32                    `protobuf:"varint,12,opt,name=G" json:"G,omitempty"`
	GKg                   []byte                    `protobuf:"bytes,13,opt,name=GKg" json:"GKg,omitempty"`
	GT                    *int32                    `protobuf:"varint,14,opt,name=GT" json:"GT,omitempty"`
	GKi                   *int32                    `protobuf:"varint,15,opt,name=GKi" json:"GKi,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *FinderUserPrepareResponse) Reset()         { *m = FinderUserPrepareResponse{} }
func (m *FinderUserPrepareResponse) String() string { return proto.CompactTextString(m) }
func (*FinderUserPrepareResponse) ProtoMessage()    {}
func (*FinderUserPrepareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{11}
}

func (m *FinderUserPrepareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderUserPrepareResponse.Unmarshal(m, b)
}
func (m *FinderUserPrepareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderUserPrepareResponse.Marshal(b, m, deterministic)
}
func (m *FinderUserPrepareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderUserPrepareResponse.Merge(m, src)
}
func (m *FinderUserPrepareResponse) XXX_Size() int {
	return xxx_messageInfo_FinderUserPrepareResponse.Size(m)
}
func (m *FinderUserPrepareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderUserPrepareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinderUserPrepareResponse proto.InternalMessageInfo

func (m *FinderUserPrepareResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *FinderUserPrepareResponse) GetActionType() int32 {
	if m != nil && m.ActionType != nil {
		return *m.ActionType
	}
	return 0
}

func (m *FinderUserPrepareResponse) GetVerifyInfo() *FinderNicknameVerifyInfo {
	if m != nil {
		return m.VerifyInfo
	}
	return nil
}

func (m *FinderUserPrepareResponse) GetSelfContact() *FinderContact {
	if m != nil {
		return m.SelfContact
	}
	return nil
}

func (m *FinderUserPrepareResponse) GetUserFlag() int32 {
	if m != nil && m.UserFlag != nil {
		return *m.UserFlag
	}
	return 0
}

func (m *FinderUserPrepareResponse) GetNicknameModifyWording() string {
	if m != nil && m.NicknameModifyWording != nil {
		return *m.NicknameModifyWording
	}
	return ""
}

func (m *FinderUserPrepareResponse) GetGKc() string {
	if m != nil && m.GKc != nil {
		return *m.GKc
	}
	return ""
}

func (m *FinderUserPrepareResponse) GetGKd() string {
	if m != nil && m.GKd != nil {
		return *m.GKd
	}
	return ""
}

func (m *FinderUserPrepareResponse) GetGKe() int32 {
	if m != nil && m.GKe != nil {
		return *m.GKe
	}
	return 0
}

func (m *FinderUserPrepareResponse) GetT() int32 {
	if m != nil && m.T != nil {
		return *m.T
	}
	return 0
}

func (m *FinderUserPrepareResponse) GetGKf() int32 {
	if m != nil && m.GKf != nil {
		return *m.GKf
	}
	return 0
}

func (m *FinderUserPrepareResponse) GetG() int32 {
	if m != nil && m.G != nil {
		return *m.G
	}
	return 0
}

func (m *FinderUserPrepareResponse) GetGKg() []byte {
	if m != nil {
		return m.GKg
	}
	return nil
}

func (m *FinderUserPrepareResponse) GetGT() int32 {
	if m != nil && m.GT != nil {
		return *m.GT
	}
	return 0
}

func (m *FinderUserPrepareResponse) GetGKi() int32 {
	if m != nil && m.GKi != nil {
		return *m.GKi
	}
	return 0
}

type FinderNicknameVerifyInfo struct {
	VerifyPrefix         *string  `protobuf:"bytes,1,opt,name=VerifyPrefix" json:"VerifyPrefix,omitempty"`
	BannerWording        *string  `protobuf:"bytes,2,opt,name=BannerWording" json:"BannerWording,omitempty"`
	VerifyLink           *string  `protobuf:"bytes,3,opt,name=VerifyLink" json:"VerifyLink,omitempty"`
	Appname              *string  `protobuf:"bytes,4,opt,name=Appname" json:"Appname,omitempty"`
	VerifyNickname       *string  `protobuf:"bytes,5,opt,name=VerifyNickname" json:"VerifyNickname,omitempty"`
	HeadImgUrl           *string  `protobuf:"bytes,6,opt,name=HeadImgUrl" json:"HeadImgUrl,omitempty"`
	ErrScene             *int32   `protobuf:"varint,7,opt,name=ErrScene" json:"ErrScene,omitempty"`
	G                    *string  `protobuf:"bytes,8,opt,name=G" json:"G,omitempty"`
	T                    *string  `protobuf:"bytes,9,opt,name=T" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderNicknameVerifyInfo) Reset()         { *m = FinderNicknameVerifyInfo{} }
func (m *FinderNicknameVerifyInfo) String() string { return proto.CompactTextString(m) }
func (*FinderNicknameVerifyInfo) ProtoMessage()    {}
func (*FinderNicknameVerifyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{12}
}

func (m *FinderNicknameVerifyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderNicknameVerifyInfo.Unmarshal(m, b)
}
func (m *FinderNicknameVerifyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderNicknameVerifyInfo.Marshal(b, m, deterministic)
}
func (m *FinderNicknameVerifyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderNicknameVerifyInfo.Merge(m, src)
}
func (m *FinderNicknameVerifyInfo) XXX_Size() int {
	return xxx_messageInfo_FinderNicknameVerifyInfo.Size(m)
}
func (m *FinderNicknameVerifyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderNicknameVerifyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FinderNicknameVerifyInfo proto.InternalMessageInfo

func (m *FinderNicknameVerifyInfo) GetVerifyPrefix() string {
	if m != nil && m.VerifyPrefix != nil {
		return *m.VerifyPrefix
	}
	return ""
}

func (m *FinderNicknameVerifyInfo) GetBannerWording() string {
	if m != nil && m.BannerWording != nil {
		return *m.BannerWording
	}
	return ""
}

func (m *FinderNicknameVerifyInfo) GetVerifyLink() string {
	if m != nil && m.VerifyLink != nil {
		return *m.VerifyLink
	}
	return ""
}

func (m *FinderNicknameVerifyInfo) GetAppname() string {
	if m != nil && m.Appname != nil {
		return *m.Appname
	}
	return ""
}

func (m *FinderNicknameVerifyInfo) GetVerifyNickname() string {
	if m != nil && m.VerifyNickname != nil {
		return *m.VerifyNickname
	}
	return ""
}

func (m *FinderNicknameVerifyInfo) GetHeadImgUrl() string {
	if m != nil && m.HeadImgUrl != nil {
		return *m.HeadImgUrl
	}
	return ""
}

func (m *FinderNicknameVerifyInfo) GetErrScene() int32 {
	if m != nil && m.ErrScene != nil {
		return *m.ErrScene
	}
	return 0
}

func (m *FinderNicknameVerifyInfo) GetG() string {
	if m != nil && m.G != nil {
		return *m.G
	}
	return ""
}

func (m *FinderNicknameVerifyInfo) GetT() string {
	if m != nil && m.T != nil {
		return *m.T
	}
	return ""
}

type FinderFollowRequest struct {
	FinderUsername       *string          `protobuf:"bytes,2,opt,name=FinderUsername" json:"FinderUsername,omitempty"`
	OpType               *int32           `protobuf:"varint,3,opt,name=OpType" json:"OpType,omitempty"`
	RefObjectId          *uint64          `protobuf:"varint,4,opt,name=RefObjectId" json:"RefObjectId,omitempty"`
	PosterUsername       *string          `protobuf:"bytes,5,opt,name=PosterUsername" json:"PosterUsername,omitempty"`
	FinderReq            *FinderTxRequest `protobuf:"bytes,7,opt,name=FinderReq" json:"FinderReq,omitempty"`
	Cook                 *string          `protobuf:"bytes,8,opt,name=Cook" json:"Cook,omitempty"`
	EnterType            *int32           `protobuf:"varint,9,opt,name=EnterType" json:"EnterType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FinderFollowRequest) Reset()         { *m = FinderFollowRequest{} }
func (m *FinderFollowRequest) String() string { return proto.CompactTextString(m) }
func (*FinderFollowRequest) ProtoMessage()    {}
func (*FinderFollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{13}
}

func (m *FinderFollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderFollowRequest.Unmarshal(m, b)
}
func (m *FinderFollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderFollowRequest.Marshal(b, m, deterministic)
}
func (m *FinderFollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderFollowRequest.Merge(m, src)
}
func (m *FinderFollowRequest) XXX_Size() int {
	return xxx_messageInfo_FinderFollowRequest.Size(m)
}
func (m *FinderFollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderFollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinderFollowRequest proto.InternalMessageInfo

func (m *FinderFollowRequest) GetFinderUsername() string {
	if m != nil && m.FinderUsername != nil {
		return *m.FinderUsername
	}
	return ""
}

func (m *FinderFollowRequest) GetOpType() int32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

func (m *FinderFollowRequest) GetRefObjectId() uint64 {
	if m != nil && m.RefObjectId != nil {
		return *m.RefObjectId
	}
	return 0
}

func (m *FinderFollowRequest) GetPosterUsername() string {
	if m != nil && m.PosterUsername != nil {
		return *m.PosterUsername
	}
	return ""
}

func (m *FinderFollowRequest) GetFinderReq() *FinderTxRequest {
	if m != nil {
		return m.FinderReq
	}
	return nil
}

func (m *FinderFollowRequest) GetCook() string {
	if m != nil && m.Cook != nil {
		return *m.Cook
	}
	return ""
}

func (m *FinderFollowRequest) GetEnterType() int32 {
	if m != nil && m.EnterType != nil {
		return *m.EnterType
	}
	return 0
}

type FinderFollowResponse struct {
	BaseResponse         *BaseResponse  `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	Contact              *FinderContact `protobuf:"bytes,2,opt,name=Contact" json:"Contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FinderFollowResponse) Reset()         { *m = FinderFollowResponse{} }
func (m *FinderFollowResponse) String() string { return proto.CompactTextString(m) }
func (*FinderFollowResponse) ProtoMessage()    {}
func (*FinderFollowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderFollowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderFollowResponse.Unmarshal(m, b)
}
func (m *FinderFollowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderFollowResponse.Marshal(b, m, deterministic)
}
func (m *FinderFollowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderFollowResponse.Merge(m, src)
}
func (m *FinderFollowResponse) XXX_Size() int {
	return xxx_messageInfo_FinderFollowResponse.Size(m)
}
func (m *FinderFollowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderFollowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinderFollowResponse proto.InternalMessageInfo

func (m *FinderFollowResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *FinderFollowResponse) GetContact() *FinderContact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type FinderUserPageRequest struct {
	BaseRequest          *BaseRequest       `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	Username             *string            `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	MaxId                *uint64            `protobuf:"varint,3,opt,name=maxId" json:"maxId,omitempty"`
	FirstPageMd5         *string            `protobuf:"bytes,4,opt,name=firstPageMd5" json:"firstPageMd5,omitempty"`
	FinderUsername       *string            `protobuf:"bytes,5,opt,name=finderUsername" json:"finderUsername,omitempty"`
	NeedFansCount        *int32             `protobuf:"varint,6,opt,name=needFansCount" json:"needFansCount,omitempty"`
	FinderBasereq        *FinderBaseRequest `protobuf:"bytes,7,opt,name=finderBasereq" json:"finderBasereq,omitempty"`
	LastBuffer           []byte             `protobuf:"bytes,8,opt,name=lastBuffer" json:"lastBuffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FinderUserPageRequest) Reset()         { *m = FinderUserPageRequest{} }
func (m *FinderUserPageRequest) String() string { return proto.CompactTextString(m) }
func (*FinderUserPageRequest) ProtoMessage()    {}
func (*FinderUserPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderUserPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderUserPageRequest.Unmarshal(m, b)
}
func (m *FinderUserPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderUserPageRequest.Marshal(b, m, deterministic)
}
func (m *FinderUserPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderUserPageRequest.Merge(m, src)
}
func (m *FinderUserPageRequest) XXX_Size() int {
	return xxx_messageInfo_FinderUserPageRequest.Size(m)
}
func (m *FinderUserPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderUserPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinderUserPageRequest proto.InternalMessageInfo

func (m *FinderUserPageRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *FinderUserPageRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *FinderUserPageRequest) GetMaxId() uint64 {
	if m != nil && m.MaxId != nil {
		return *m.MaxId
	}
	return 0
}

func (m *FinderUserPageRequest) GetFirstPageMd5() string {
	if m != nil && m.FirstPageMd5 != nil {
		return *m.FirstPageMd5
	}
	return ""
}

func (m *FinderUserPageRequest) GetFinderUsername() string {
	if m != nil && m.FinderUsername != nil {
		return *m.FinderUsername
	}
	return ""
}

func (m *FinderUserPageRequest) GetNeedFansCount() int32 {
	if m != nil && m.NeedFansCount != nil {
		return *m.NeedFansCount
	}
	return 0
}

// 视频号
type FinderBaseRequest struct {
	Userver              *int32             `protobuf:"varint,1,opt,name=userver" json:"userver,omitempty"`
	Scene                *int32             `protobuf:"varint,2,opt,name=scene" json:"scene,omitempty"`
	ExtSpamInfo          []byte             `protobuf:"bytes,3,opt,name=extSpamInfo" json:"extSpamInfo,omitempty"`
	ExptFla              *uint32            `protobuf:"varint,4,opt,name=ExptFla" json:"ExptFla,omitempty"`
	CtxInfo              *ClientContextInfo `protobuf:"bytes,5,opt,name=CtxInfo" json:"CtxInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FinderBaseRequest) Reset()         { *m = FinderBaseRequest{} }
func (m *FinderBaseRequest) String() string { return proto.CompactTextString(m) }
func (*FinderBaseRequest) ProtoMessage()    {}
func (*FinderBaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderBaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderBaseRequest.Unmarshal(m, b)
}
func (m *FinderBaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderBaseRequest.Marshal(b, m, deterministic)
}
func (m *FinderBaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderBaseRequest.Merge(m, src)
}
func (m *FinderBaseRequest) XXX_Size() int {
	return xxx_messageInfo_FinderBaseRequest.Size(m)
}
func (m *FinderBaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderBaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinderBaseRequest proto.InternalMessageInfo

func (m *FinderBaseRequest) GetUserver() int32 {
	if m != nil && m.Userver != nil {
		return *m.Userver
	}
	return 0
}

func (m *FinderBaseRequest) GetScene() int32 {
	if m != nil && m.Scene != nil {
		return *m.Scene
	}
	return 0
}

func (m *FinderBaseRequest) GetExtSpamInfo() []byte {
	if m != nil {
		return m.ExtSpamInfo
	}
	return nil
}

func (m *FinderBaseRequest) GetExptFla() uint32 {
	if m != nil && m.ExptFla != nil {
		return *m.ExptFla
	}
	return 0
}

type ClientContextInfo struct {
	ContextId            *string  `protobuf:"bytes,1,opt,name=ContextId" json:"ContextId,omitempty"`
	ClickTabContextId    *string  `protobuf:"bytes,2,opt,name=ClickTabContextId" json:"ClickTabContextId,omitempty"`
	ClientReportBuff     *string  `protobuf:"bytes,3,opt,name=ClientReportBuff" json:"ClientReportBuff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientContextInfo) Reset()         { *m = ClientContextInfo{} }
func (m *ClientContextInfo) String() string { return proto.CompactTextString(m) }
func (*ClientContextInfo) ProtoMessage()    {}
func (*ClientContextInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *ClientContextInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientContextInfo.Unmarshal(m, b)
}
func (m *ClientContextInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientContextInfo.Marshal(b, m, deterministic)
}
func (m *ClientContextInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientContextInfo.Merge(m, src)
}
func (m *ClientContextInfo) XXX_Size() int {
	return xxx_messageInfo_ClientContextInfo.Size(m)
}
func (m *ClientContextInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientContextInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientContextInfo proto.InternalMessageInfo

func (m *ClientContextInfo) GetContextId() string {
	if m != nil && m.ContextId != nil {
		return *m.ContextId
	}
	return ""
}

func (m *ClientContextInfo) GetClickTabContextId() string {
	if m != nil && m.ClickTabContextId != nil {
		return *m.ClickTabContextId
	}
	return ""
}

func (m *ClientContextInfo) GetClientReportBuff() string {
	if m != nil && m.ClientReportBuff != nil {
		return *m.ClientReportBuff
	}
	return ""
}

func (m *FinderBaseRequest) GetCtxInfo() *ClientContextInfo {
	if m != nil {
		return m.CtxInfo
	}
	return nil
}

func (m *FinderUserPageRequest) GetFinderBasereq() *FinderBaseRequest {
	if m != nil {
		return m.FinderBasereq
	}
	return nil
}

func (m *FinderUserPageRequest) GetLastBuffer() []byte {
	if m != nil {
		return m.LastBuffer
	}
	return nil
}

type FinderUserInfo struct {
	CoverImgUrl          *string         `protobuf:"bytes,1,opt,name=coverImgUrl" json:"coverImgUrl,omitempty"`
	AuthIconType         *int32          `protobuf:"varint,2,opt,name=authIconType" json:"authIconType,omitempty"`
	AuthProfession       *string         `protobuf:"bytes,3,opt,name=authProfession" json:"authProfession,omitempty"`
	AuthInfo             *FinderAuthInfo `protobuf:"bytes,4,opt,name=authInfo" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FinderUserInfo) Reset()         { *m = FinderUserInfo{} }
func (m *FinderUserInfo) String() string { return proto.CompactTextString(m) }
func (*FinderUserInfo) ProtoMessage()    {}
func (*FinderUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderUserInfo.Unmarshal(m, b)
}
func (m *FinderUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderUserInfo.Marshal(b, m, deterministic)
}
func (m *FinderUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderUserInfo.Merge(m, src)
}
func (m *FinderUserInfo) XXX_Size() int {
	return xxx_messageInfo_FinderUserInfo.Size(m)
}
func (m *FinderUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FinderUserInfo proto.InternalMessageInfo

func (m *FinderUserInfo) GetCoverImgUrl() string {
	if m != nil && m.CoverImgUrl != nil {
		return *m.CoverImgUrl
	}
	return ""
}

func (m *FinderUserInfo) GetAuthIconType() int32 {
	if m != nil && m.AuthIconType != nil {
		return *m.AuthIconType
	}
	return 0
}

func (m *FinderUserInfo) GetAuthProfession() string {
	if m != nil && m.AuthProfession != nil {
		return *m.AuthProfession
	}
	return ""
}

func (m *FinderUserInfo) GetAuthInfo() *FinderAuthInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type FinderAuthInfo struct {
	RealName             *string        `protobuf:"bytes,1,opt,name=realName" json:"realName,omitempty"`
	AuthIconType         *int32         `protobuf:"varint,2,opt,name=authIconType" json:"authIconType,omitempty"`
	AuthProfession       *string        `protobuf:"bytes,3,opt,name=authProfession" json:"authProfession,omitempty"`
	AuthGuarantor        *FinderContact `protobuf:"bytes,4,opt,name=authGuarantor" json:"authGuarantor,omitempty"`
	DetailLink           *string        `protobuf:"bytes,5,opt,name=detailLink" json:"detailLink,omitempty"`
	AppName              *string        `protobuf:"bytes,6,opt,name=appName" json:"appName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FinderAuthInfo) Reset()         { *m = FinderAuthInfo{} }
func (m *FinderAuthInfo) String() string { return proto.CompactTextString(m) }
func (*FinderAuthInfo) ProtoMessage()    {}
func (*FinderAuthInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderAuthInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderAuthInfo.Unmarshal(m, b)
}
func (m *FinderAuthInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderAuthInfo.Marshal(b, m, deterministic)
}
func (m *FinderAuthInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderAuthInfo.Merge(m, src)
}
func (m *FinderAuthInfo) XXX_Size() int {
	return xxx_messageInfo_FinderAuthInfo.Size(m)
}
func (m *FinderAuthInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderAuthInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FinderAuthInfo proto.InternalMessageInfo

func (m *FinderAuthInfo) GetRealName() string {
	if m != nil && m.RealName != nil {
		return *m.RealName
	}
	return ""
}

func (m *FinderAuthInfo) GetAuthIconType() int32 {
	if m != nil && m.AuthIconType != nil {
		return *m.AuthIconType
	}
	return 0
}

func (m *FinderAuthInfo) GetAuthProfession() string {
	if m != nil && m.AuthProfession != nil {
		return *m.AuthProfession
	}
	return ""
}

func (m *FinderAuthInfo) GetAuthGuarantor() *FinderContact {
	if m != nil {
		return m.AuthGuarantor
	}
	return nil
}

func (m *FinderAuthInfo) GetDetailLink() string {
	if m != nil && m.DetailLink != nil {
		return *m.DetailLink
	}
	return ""
}

func (m *FinderAuthInfo) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return ""
}

type FinderMedia struct {
	Url                  *string            `protobuf:"bytes,1,opt,name=Url" json:"Url,omitempty"`
	ThumbUrl             *string            `protobuf:"bytes,2,opt,name=ThumbUrl" json:"ThumbUrl,omitempty"`
	MediaType            *int32             `protobuf:"varint,3,opt,name=MediaType" json:"MediaType,omitempty"`
	VideoPlayLen         *int32             `protobuf:"varint,4,opt,name=VideoPlayLen" json:"VideoPlayLen,omitempty"`
	Width                *float32           `protobuf:"fixed32,5,opt,name=Width" json:"Width,omitempty"`
	Height               *float32           `protobuf:"fixed32,6,opt,name=Height" json:"Height,omitempty"`
	Md5Sum               *string            `protobuf:"bytes,7,opt,name=Md5Sum" json:"Md5Sum,omitempty"`
	FileSize             *int32             `protobuf:"varint,8,opt,name=FileSize" json:"FileSize,omitempty"`
	Bitrate              *int32             `protobuf:"varint,9,opt,name=Bitrate" json:"Bitrate,omitempty"`
	Spec                 []*FinderMediaSpec `protobuf:"bytes,10,rep,name=Spec" json:"Spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FinderMedia) Reset()         { *m = FinderMedia{} }
func (m *FinderMedia) String() string { return proto.CompactTextString(m) }
func (*FinderMedia) ProtoMessage()    {}
func (*FinderMedia) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderMedia) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderMedia.Unmarshal(m, b)
}
func (m *FinderMedia) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderMedia.Marshal(b, m, deterministic)
}
func (m *FinderMedia) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderMedia.Merge(m, src)
}
func (m *FinderMedia) XXX_Size() int {
	return xxx_messageInfo_FinderMedia.Size(m)
}
func (m *FinderMedia) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderMedia.DiscardUnknown(m)
}

var xxx_messageInfo_FinderMedia proto.InternalMessageInfo

func (m *FinderMedia) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *FinderMedia) GetThumbUrl() string {
	if m != nil && m.ThumbUrl != nil {
		return *m.ThumbUrl
	}
	return ""
}

func (m *FinderMedia) GetMediaType() int32 {
	if m != nil && m.MediaType != nil {
		return *m.MediaType
	}
	return 0
}

func (m *FinderMedia) GetVideoPlayLen() int32 {
	if m != nil && m.VideoPlayLen != nil {
		return *m.VideoPlayLen
	}
	return 0
}

func (m *FinderMedia) GetWidth() float32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *FinderMedia) GetHeight() float32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *FinderMedia) GetMd5Sum() string {
	if m != nil && m.Md5Sum != nil {
		return *m.Md5Sum
	}
	return ""
}

func (m *FinderMedia) GetFileSize() int32 {
	if m != nil && m.FileSize != nil {
		return *m.FileSize
	}
	return 0
}

func (m *FinderMedia) GetBitrate() int32 {
	if m != nil && m.Bitrate != nil {
		return *m.Bitrate
	}
	return 0
}

func (m *FinderMedia) GetSpec() []*FinderMediaSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type FinderMediaSpec struct {
	FileFormat           *string  `protobuf:"bytes,1,opt,name=fileFormat" json:"fileFormat,omitempty"`
	FirstLoadBytes       *int32   `protobuf:"varint,2,opt,name=firstLoadBytes" json:"firstLoadBytes,omitempty"`
	BitRate              *int32   `protobuf:"varint,3,opt,name=bitRate" json:"bitRate,omitempty"`
	CodingFormat         *string  `protobuf:"bytes,4,opt,name=codingFormat" json:"codingFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderMediaSpec) Reset()         { *m = FinderMediaSpec{} }
func (m *FinderMediaSpec) String() string { return proto.CompactTextString(m) }
func (*FinderMediaSpec) ProtoMessage()    {}
func (*FinderMediaSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderMediaSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderMediaSpec.Unmarshal(m, b)
}
func (m *FinderMediaSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderMediaSpec.Marshal(b, m, deterministic)
}
func (m *FinderMediaSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderMediaSpec.Merge(m, src)
}
func (m *FinderMediaSpec) XXX_Size() int {
	return xxx_messageInfo_FinderMediaSpec.Size(m)
}
func (m *FinderMediaSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderMediaSpec.DiscardUnknown(m)
}

var xxx_messageInfo_FinderMediaSpec proto.InternalMessageInfo

func (m *FinderMediaSpec) GetFileFormat() string {
	if m != nil && m.FileFormat != nil {
		return *m.FileFormat
	}
	return ""
}

func (m *FinderMediaSpec) GetFirstLoadBytes() int32 {
	if m != nil && m.FirstLoadBytes != nil {
		return *m.FirstLoadBytes
	}
	return 0
}

func (m *FinderMediaSpec) GetBitRate() int32 {
	if m != nil && m.BitRate != nil {
		return *m.BitRate
	}
	return 0
}

func (m *FinderMediaSpec) GetCodingFormat() string {
	if m != nil && m.CodingFormat != nil {
		return *m.CodingFormat
	}
	return ""
}

type FinderMediaExtra struct {
	Text                 *string  `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderMediaExtra) Reset()         { *m = FinderMediaExtra{} }
func (m *FinderMediaExtra) String() string { return proto.CompactTextString(m) }
func (*FinderMediaExtra) ProtoMessage()    {}
func (*FinderMediaExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderMediaExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderMediaExtra.Unmarshal(m, b)
}
func (m *FinderMediaExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderMediaExtra.Marshal(b, m, deterministic)
}
func (m *FinderMediaExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderMediaExtra.Merge(m, src)
}
func (m *FinderMediaExtra) XXX_Size() int {
	return xxx_messageInfo_FinderMediaExtra.Size(m)
}
func (m *FinderMediaExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderMediaExtra.DiscardUnknown(m)
}

var xxx_messageInfo_FinderMediaExtra proto.InternalMessageInfo

func (m *FinderMediaExtra) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type FinderLocation struct {
	Longitude            *float32 `protobuf:"fixed32,1,opt,name=longitude" json:"longitude,omitempty"`
	Latitude             *float32 `protobuf:"fixed32,2,opt,name=latitude" json:"latitude,omitempty"`
	City                 *string  `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	PoiName              *string  `protobuf:"bytes,4,opt,name=poiName" json:"poiName,omitempty"`
	PoiAddress           *string  `protobuf:"bytes,5,opt,name=poiAddress" json:"poiAddress,omitempty"`
	PoiClassifyId        *string  `protobuf:"bytes,6,opt,name=poiClassifyId" json:"poiClassifyId,omitempty"`
	PoiClassifyType      *int32   `protobuf:"varint,7,opt,name=poiClassifyType" json:"poiClassifyType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderLocation) Reset()         { *m = FinderLocation{} }
func (m *FinderLocation) String() string { return proto.CompactTextString(m) }
func (*FinderLocation) ProtoMessage()    {}
func (*FinderLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderLocation.Unmarshal(m, b)
}
func (m *FinderLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderLocation.Marshal(b, m, deterministic)
}
func (m *FinderLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderLocation.Merge(m, src)
}
func (m *FinderLocation) XXX_Size() int {
	return xxx_messageInfo_FinderLocation.Size(m)
}
func (m *FinderLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderLocation.DiscardUnknown(m)
}

var xxx_messageInfo_FinderLocation proto.InternalMessageInfo

func (m *FinderLocation) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *FinderLocation) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *FinderLocation) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *FinderLocation) GetPoiName() string {
	if m != nil && m.PoiName != nil {
		return *m.PoiName
	}
	return ""
}

func (m *FinderLocation) GetPoiAddress() string {
	if m != nil && m.PoiAddress != nil {
		return *m.PoiAddress
	}
	return ""
}

func (m *FinderLocation) GetPoiClassifyId() string {
	if m != nil && m.PoiClassifyId != nil {
		return *m.PoiClassifyId
	}
	return ""
}

func (m *FinderLocation) GetPoiClassifyType() int32 {
	if m != nil && m.PoiClassifyType != nil {
		return *m.PoiClassifyType
	}
	return 0
}

type FinderExtendedReading struct {
	Link                 *string  `protobuf:"bytes,1,opt,name=link" json:"link,omitempty"`
	Title                *string  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderExtendedReading) Reset()         { *m = FinderExtendedReading{} }
func (m *FinderExtendedReading) String() string { return proto.CompactTextString(m) }
func (*FinderExtendedReading) ProtoMessage()    {}
func (*FinderExtendedReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderExtendedReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderExtendedReading.Unmarshal(m, b)
}
func (m *FinderExtendedReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderExtendedReading.Marshal(b, m, deterministic)
}
func (m *FinderExtendedReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderExtendedReading.Merge(m, src)
}
func (m *FinderExtendedReading) XXX_Size() int {
	return xxx_messageInfo_FinderExtendedReading.Size(m)
}
func (m *FinderExtendedReading) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderExtendedReading.DiscardUnknown(m)
}

var xxx_messageInfo_FinderExtendedReading proto.InternalMessageInfo

func (m *FinderExtendedReading) GetLink() string {
	if m != nil && m.Link != nil {
		return *m.Link
	}
	return ""
}

func (m *FinderExtendedReading) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

type FinderTopic struct {
	FinderTopicInfo      *string  `protobuf:"bytes,1,opt,name=finderTopicInfo" json:"finderTopicInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderTopic) Reset()         { *m = FinderTopic{} }
func (m *FinderTopic) String() string { return proto.CompactTextString(m) }
func (*FinderTopic) ProtoMessage()    {}
func (*FinderTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderTopic.Unmarshal(m, b)
}
func (m *FinderTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderTopic.Marshal(b, m, deterministic)
}
func (m *FinderTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderTopic.Merge(m, src)
}
func (m *FinderTopic) XXX_Size() int {
	return xxx_messageInfo_FinderTopic.Size(m)
}
func (m *FinderTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderTopic.DiscardUnknown(m)
}

var xxx_messageInfo_FinderTopic proto.InternalMessageInfo

func (m *FinderTopic) GetFinderTopicInfo() string {
	if m != nil && m.FinderTopicInfo != nil {
		return *m.FinderTopicInfo
	}
	return ""
}

type FinderObjectDesc struct {
	Description          *string                `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Media                []*FinderMedia         `protobuf:"bytes,2,rep,name=media" json:"media,omitempty"`
	MediaType            *int32                 `protobuf:"varint,3,opt,name=mediaType" json:"mediaType,omitempty"`
	Extra                *FinderMediaExtra      `protobuf:"bytes,4,opt,name=extra" json:"extra,omitempty"`
	Location             *FinderLocation        `protobuf:"bytes,5,opt,name=location" json:"location,omitempty"`
	ExtReading           *FinderExtendedReading `protobuf:"bytes,6,opt,name=extReading" json:"extReading,omitempty"`
	Topic                *FinderTopic           `protobuf:"bytes,7,opt,name=topic" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FinderObjectDesc) Reset()         { *m = FinderObjectDesc{} }
func (m *FinderObjectDesc) String() string { return proto.CompactTextString(m) }
func (*FinderObjectDesc) ProtoMessage()    {}
func (*FinderObjectDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderObjectDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderObjectDesc.Unmarshal(m, b)
}
func (m *FinderObjectDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderObjectDesc.Marshal(b, m, deterministic)
}
func (m *FinderObjectDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderObjectDesc.Merge(m, src)
}
func (m *FinderObjectDesc) XXX_Size() int {
	return xxx_messageInfo_FinderObjectDesc.Size(m)
}
func (m *FinderObjectDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderObjectDesc.DiscardUnknown(m)
}

var xxx_messageInfo_FinderObjectDesc proto.InternalMessageInfo

func (m *FinderObjectDesc) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *FinderObjectDesc) GetMedia() []*FinderMedia {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *FinderObjectDesc) GetMediaType() int32 {
	if m != nil && m.MediaType != nil {
		return *m.MediaType
	}
	return 0
}

func (m *FinderObjectDesc) GetExtra() *FinderMediaExtra {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *FinderObjectDesc) GetLocation() *FinderLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *FinderObjectDesc) GetExtReading() *FinderExtendedReading {
	if m != nil {
		return m.ExtReading
	}
	return nil
}

func (m *FinderObjectDesc) GetTopic() *FinderTopic {
	if m != nil {
		return m.Topic
	}
	return nil
}

// 疑似不对
type FinderRecommendInfo struct {
	Tid                  *string  `protobuf:"bytes,1,opt,name=tid" json:"tid,omitempty"`
	RecommendType        *uint32  `protobuf:"varint,2,opt,name=recommendType" json:"recommendType,omitempty"`
	RecommendReason      *string  `protobuf:"bytes,3,opt,name=recommendReason" json:"recommendReason,omitempty"`
	OrgRecommendType     *uint32  `protobuf:"varint,4,opt,name=orgRecommendType" json:"orgRecommendType,omitempty"`
	LastInsertedRowID    *uint32  `protobuf:"varint,5,opt,name=lastInsertedRowID" json:"lastInsertedRowID,omitempty"`
	IsAutoIncrement      *bool    `protobuf:"varint,6,opt,name=isAutoIncrement" json:"isAutoIncrement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderRecommendInfo) Reset()         { *m = FinderRecommendInfo{} }
func (m *FinderRecommendInfo) String() string { return proto.CompactTextString(m) }
func (*FinderRecommendInfo) ProtoMessage()    {}
func (*FinderRecommendInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderRecommendInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderRecommendInfo.Unmarshal(m, b)
}
func (m *FinderRecommendInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderRecommendInfo.Marshal(b, m, deterministic)
}
func (m *FinderRecommendInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderRecommendInfo.Merge(m, src)
}
func (m *FinderRecommendInfo) XXX_Size() int {
	return xxx_messageInfo_FinderRecommendInfo.Size(m)
}
func (m *FinderRecommendInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderRecommendInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FinderRecommendInfo proto.InternalMessageInfo

func (m *FinderRecommendInfo) GetTid() string {
	if m != nil && m.Tid != nil {
		return *m.Tid
	}
	return ""
}

func (m *FinderRecommendInfo) GetRecommendType() uint32 {
	if m != nil && m.RecommendType != nil {
		return *m.RecommendType
	}
	return 0
}

func (m *FinderRecommendInfo) GetRecommendReason() string {
	if m != nil && m.RecommendReason != nil {
		return *m.RecommendReason
	}
	return ""
}

func (m *FinderRecommendInfo) GetOrgRecommendType() uint32 {
	if m != nil && m.OrgRecommendType != nil {
		return *m.OrgRecommendType
	}
	return 0
}

func (m *FinderRecommendInfo) GetLastInsertedRowID() uint32 {
	if m != nil && m.LastInsertedRowID != nil {
		return *m.LastInsertedRowID
	}
	return 0
}

func (m *FinderRecommendInfo) GetIsAutoIncrement() bool {
	if m != nil && m.IsAutoIncrement != nil {
		return *m.IsAutoIncrement
	}
	return false
}

type FinderCommentInfo struct {
	Username             *string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Nickname             *string  `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Content              *string  `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	CommentId            *uint32  `protobuf:"varint,4,opt,name=commentId" json:"commentId,omitempty"`
	ReplyCommentId       *uint32  `protobuf:"varint,5,opt,name=replyCommentId" json:"replyCommentId,omitempty"`
	DeleteFlag           *int32   `protobuf:"varint,6,opt,name=deleteFlag" json:"deleteFlag,omitempty"`
	HeadUrl              *string  `protobuf:"bytes,7,opt,name=headUrl" json:"headUrl,omitempty"`
	LevelTwoComment      []string `protobuf:"bytes,8,rep,name=levelTwoComment" json:"levelTwoComment,omitempty"`
	Createtime           *uint32  `protobuf:"varint,9,opt,name=createtime" json:"createtime,omitempty"`
	ReplyNickname        *string  `protobuf:"bytes,10,opt,name=replyNickname" json:"replyNickname,omitempty"`
	DisplayidDiscarded   *string  `protobuf:"bytes,11,opt,name=displayidDiscarded" json:"displayidDiscarded,omitempty"`
	LikeFlag             *int32   `protobuf:"varint,12,opt,name=likeFlag" json:"likeFlag,omitempty"`
	LikeCount            *int32   `protobuf:"varint,13,opt,name=likeCount" json:"likeCount,omitempty"`
	Displayid            *uint32  `protobuf:"varint,14,opt,name=displayid" json:"displayid,omitempty"`
	ExpandCommentCount   *int32   `protobuf:"varint,15,opt,name=expandCommentCount" json:"expandCommentCount,omitempty"`
	LastBuffer           []byte   `protobuf:"bytes,16,opt,name=lastBuffer" json:"lastBuffer,omitempty"`
	ContinueFlag         *int32   `protobuf:"varint,17,opt,name=continueFlag" json:"continueFlag,omitempty"`
	DisplayFlag          *int32   `protobuf:"varint,18,opt,name=displayFlag" json:"displayFlag,omitempty"`
	BlacklistFlag        *int32   `protobuf:"varint,19,opt,name=blacklistFlag" json:"blacklistFlag,omitempty"`
	ReplyContent         *string  `protobuf:"bytes,20,opt,name=replyContent" json:"replyContent,omitempty"`
	ReplyUsername        *string  `protobuf:"bytes,21,opt,name=replyUsername" json:"replyUsername,omitempty"`
	ClientId             *string  `protobuf:"bytes,22,opt,name=clientId" json:"clientId,omitempty"`
	UpContinueFlag       *int32   `protobuf:"varint,23,opt,name=upContinueFlag" json:"upContinueFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinderCommentInfo) Reset()         { *m = FinderCommentInfo{} }
func (m *FinderCommentInfo) String() string { return proto.CompactTextString(m) }
func (*FinderCommentInfo) ProtoMessage()    {}
func (*FinderCommentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderCommentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderCommentInfo.Unmarshal(m, b)
}
func (m *FinderCommentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderCommentInfo.Marshal(b, m, deterministic)
}
func (m *FinderCommentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderCommentInfo.Merge(m, src)
}
func (m *FinderCommentInfo) XXX_Size() int {
	return xxx_messageInfo_FinderCommentInfo.Size(m)
}
func (m *FinderCommentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderCommentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FinderCommentInfo proto.InternalMessageInfo

func (m *FinderCommentInfo) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *FinderCommentInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *FinderCommentInfo) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *FinderCommentInfo) GetCommentId() uint32 {
	if m != nil && m.CommentId != nil {
		return *m.CommentId
	}
	return 0
}

func (m *FinderCommentInfo) GetReplyCommentId() uint32 {
	if m != nil && m.ReplyCommentId != nil {
		return *m.ReplyCommentId
	}
	return 0
}

func (m *FinderCommentInfo) GetDeleteFlag() int32 {
	if m != nil && m.DeleteFlag != nil {
		return *m.DeleteFlag
	}
	return 0
}

func (m *FinderCommentInfo) GetHeadUrl() string {
	if m != nil && m.HeadUrl != nil {
		return *m.HeadUrl
	}
	return ""
}

func (m *FinderCommentInfo) GetLevelTwoComment() []string {
	if m != nil {
		return m.LevelTwoComment
	}
	return nil
}

func (m *FinderCommentInfo) GetCreatetime() uint32 {
	if m != nil && m.Createtime != nil {
		return *m.Createtime
	}
	return 0
}

func (m *FinderCommentInfo) GetReplyNickname() string {
	if m != nil && m.ReplyNickname != nil {
		return *m.ReplyNickname
	}
	return ""
}

func (m *FinderCommentInfo) GetDisplayidDiscarded() string {
	if m != nil && m.DisplayidDiscarded != nil {
		return *m.DisplayidDiscarded
	}
	return ""
}

func (m *FinderCommentInfo) GetLikeFlag() int32 {
	if m != nil && m.LikeFlag != nil {
		return *m.LikeFlag
	}
	return 0
}

func (m *FinderCommentInfo) GetLikeCount() int32 {
	if m != nil && m.LikeCount != nil {
		return *m.LikeCount
	}
	return 0
}

func (m *FinderCommentInfo) GetDisplayid() uint32 {
	if m != nil && m.Displayid != nil {
		return *m.Displayid
	}
	return 0
}

func (m *FinderCommentInfo) GetExpandCommentCount() int32 {
	if m != nil && m.ExpandCommentCount != nil {
		return *m.ExpandCommentCount
	}
	return 0
}

func (m *FinderCommentInfo) GetLastBuffer() []byte {
	if m != nil {
		return m.LastBuffer
	}
	return nil
}

func (m *FinderCommentInfo) GetContinueFlag() int32 {
	if m != nil && m.ContinueFlag != nil {
		return *m.ContinueFlag
	}
	return 0
}

func (m *FinderCommentInfo) GetDisplayFlag() int32 {
	if m != nil && m.DisplayFlag != nil {
		return *m.DisplayFlag
	}
	return 0
}

func (m *FinderCommentInfo) GetBlacklistFlag() int32 {
	if m != nil && m.BlacklistFlag != nil {
		return *m.BlacklistFlag
	}
	return 0
}

func (m *FinderCommentInfo) GetReplyContent() string {
	if m != nil && m.ReplyContent != nil {
		return *m.ReplyContent
	}
	return ""
}

func (m *FinderCommentInfo) GetReplyUsername() string {
	if m != nil && m.ReplyUsername != nil {
		return *m.ReplyUsername
	}
	return ""
}

func (m *FinderCommentInfo) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *FinderCommentInfo) GetUpContinueFlag() int32 {
	if m != nil && m.UpContinueFlag != nil {
		return *m.UpContinueFlag
	}
	return 0
}

type FinderObjectS struct {
	Id                   *uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nickname             *string                `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Username             *string                `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	ObjectDesc           *FinderObjectDesc      `protobuf:"bytes,4,opt,name=objectDesc" json:"objectDesc,omitempty"`
	Createtime           *int32                 `protobuf:"varint,5,opt,name=createtime" json:"createtime,omitempty"`
	LikeFlag             *int32                 `protobuf:"varint,6,opt,name=likeFlag" json:"likeFlag,omitempty"`
	LikeList             [][]byte               `protobuf:"bytes,7,rep,name=likeList" json:"likeList,omitempty"`
	CommentList          []*FinderCommentInfo   `protobuf:"bytes,8,rep,name=commentList" json:"commentList,omitempty"`
	ForwardCount         *int32                 `protobuf:"varint,9,opt,name=forwardCount" json:"forwardCount,omitempty"`
	Contact              *FinderContact         `protobuf:"bytes,10,opt,name=contact" json:"contact,omitempty"`
	DisplayidDiscarded   *string                `protobuf:"bytes,11,opt,name=displayidDiscarded" json:"displayidDiscarded,omitempty"`
	RecommenderList      []*FinderRecommendInfo `protobuf:"bytes,12,rep,name=recommenderList" json:"recommenderList,omitempty"`
	Displayid            *uint64                `protobuf:"varint,13,opt,name=displayid" json:"displayid,omitempty"`
	LikeCount            *int32                 `protobuf:"varint,14,opt,name=likeCount" json:"likeCount,omitempty"`
	CommentCount         *int32                 `protobuf:"varint,15,opt,name=commentCount" json:"commentCount,omitempty"`
	RecommendReason      *string                `protobuf:"bytes,16,opt,name=recommendReason" json:"recommendReason,omitempty"`
	ReadCount            *int32                 `protobuf:"varint,17,opt,name=readCount" json:"readCount,omitempty"`
	Deletetime           *int32                 `protobuf:"varint,18,opt,name=deletetime" json:"deletetime,omitempty"`
	CommentClose         *int32                 `protobuf:"varint,19,opt,name=commentClose" json:"commentClose,omitempty"`
	RefObjectFlag        *uint32                `protobuf:"varint,20,opt,name=refObjectFlag" json:"refObjectFlag,omitempty"`
	RefObjectid          *uint32                `protobuf:"varint,21,opt,name=refObjectid" json:"refObjectid,omitempty"`
	RefObjectContact     *FinderContact         `protobuf:"bytes,22,opt,name=refObjectContact" json:"refObjectContact,omitempty"`
	RecommendType        *int32                 `protobuf:"varint,23,opt,name=recommendType" json:"recommendType,omitempty"`
	FriendLikeCount      *int32                 `protobuf:"varint,24,opt,name=friendLikeCount" json:"friendLikeCount,omitempty"`
	ObjectNonceId        *string                `protobuf:"bytes,25,opt,name=objectNonceId" json:"objectNonceId,omitempty"`
	RefObjectNonceId     *string                `protobuf:"bytes,26,opt,name=refObjectNonceId" json:"refObjectNonceId,omitempty"`
	ObjectStatus         *int32                 `protobuf:"varint,27,opt,name=objectStatus" json:"objectStatus,omitempty"`
	SendShareFavWording  *string                `protobuf:"bytes,28,opt,name=sendShareFavWording" json:"sendShareFavWording,omitempty"`
	OriginalFlag         *int32                 `protobuf:"varint,29,opt,name=originalFlag" json:"originalFlag,omitempty"`
	SecondaryShowFlag    *int32                 `protobuf:"varint,30,opt,name=secondaryShowFlag" json:"secondaryShowFlag,omitempty"`
	TipsWording          *string                `protobuf:"bytes,31,opt,name=tipsWording" json:"tipsWording,omitempty"`
	OrgRecommendType     *int32                 `protobuf:"varint,32,opt,name=orgRecommendType" json:"orgRecommendType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FinderObjectS) Reset()         { *m = FinderObjectS{} }
func (m *FinderObjectS) String() string { return proto.CompactTextString(m) }
func (*FinderObjectS) ProtoMessage()    {}
func (*FinderObjectS) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}

func (m *FinderObjectS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderObject.Unmarshal(m, b)
}
func (m *FinderObjectS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderObject.Marshal(b, m, deterministic)
}
func (m *FinderObjectS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderObject.Merge(m, src)
}
func (m *FinderObjectS) XXX_Size() int {
	return xxx_messageInfo_FinderObject.Size(m)
}
func (m *FinderObjectS) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderObject.DiscardUnknown(m)
}

var xxx_messageInfo_FinderObjectS proto.InternalMessageInfo

func (m *FinderObjectS) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *FinderObjectS) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *FinderObjectS) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *FinderObjectS) GetObjectDesc() *FinderObjectDesc {
	if m != nil {
		return m.ObjectDesc
	}
	return nil
}

func (m *FinderObjectS) GetCreatetime() int32 {
	if m != nil && m.Createtime != nil {
		return *m.Createtime
	}
	return 0
}

func (m *FinderObjectS) GetLikeFlag() int32 {
	if m != nil && m.LikeFlag != nil {
		return *m.LikeFlag
	}
	return 0
}

func (m *FinderObjectS) GetLikeList() [][]byte {
	if m != nil {
		return m.LikeList
	}
	return nil
}

func (m *FinderObjectS) GetCommentList() []*FinderCommentInfo {
	if m != nil {
		return m.CommentList
	}
	return nil
}

func (m *FinderObjectS) GetForwardCount() int32 {
	if m != nil && m.ForwardCount != nil {
		return *m.ForwardCount
	}
	return 0
}

func (m *FinderObjectS) GetContact() *FinderContact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *FinderObjectS) GetDisplayidDiscarded() string {
	if m != nil && m.DisplayidDiscarded != nil {
		return *m.DisplayidDiscarded
	}
	return ""
}

func (m *FinderObjectS) GetRecommenderList() []*FinderRecommendInfo {
	if m != nil {
		return m.RecommenderList
	}
	return nil
}

func (m *FinderObjectS) GetDisplayid() uint64 {
	if m != nil && m.Displayid != nil {
		return *m.Displayid
	}
	return 0
}

func (m *FinderObjectS) GetLikeCount() int32 {
	if m != nil && m.LikeCount != nil {
		return *m.LikeCount
	}
	return 0
}

func (m *FinderObjectS) GetCommentCount() int32 {
	if m != nil && m.CommentCount != nil {
		return *m.CommentCount
	}
	return 0
}

func (m *FinderObjectS) GetRecommendReason() string {
	if m != nil && m.RecommendReason != nil {
		return *m.RecommendReason
	}
	return ""
}

func (m *FinderObjectS) GetReadCount() int32 {
	if m != nil && m.ReadCount != nil {
		return *m.ReadCount
	}
	return 0
}

func (m *FinderObjectS) GetDeletetime() int32 {
	if m != nil && m.Deletetime != nil {
		return *m.Deletetime
	}
	return 0
}

func (m *FinderObjectS) GetCommentClose() int32 {
	if m != nil && m.CommentClose != nil {
		return *m.CommentClose
	}
	return 0
}

func (m *FinderObjectS) GetRefObjectFlag() uint32 {
	if m != nil && m.RefObjectFlag != nil {
		return *m.RefObjectFlag
	}
	return 0
}

func (m *FinderObjectS) GetRefObjectid() uint32 {
	if m != nil && m.RefObjectid != nil {
		return *m.RefObjectid
	}
	return 0
}

func (m *FinderObjectS) GetRefObjectContact() *FinderContact {
	if m != nil {
		return m.RefObjectContact
	}
	return nil
}

func (m *FinderObjectS) GetRecommendType() int32 {
	if m != nil && m.RecommendType != nil {
		return *m.RecommendType
	}
	return 0
}

func (m *FinderObjectS) GetFriendLikeCount() int32 {
	if m != nil && m.FriendLikeCount != nil {
		return *m.FriendLikeCount
	}
	return 0
}

func (m *FinderObjectS) GetObjectNonceId() string {
	if m != nil && m.ObjectNonceId != nil {
		return *m.ObjectNonceId
	}
	return ""
}

func (m *FinderObjectS) GetRefObjectNonceId() string {
	if m != nil && m.RefObjectNonceId != nil {
		return *m.RefObjectNonceId
	}
	return ""
}

func (m *FinderObjectS) GetObjectStatus() int32 {
	if m != nil && m.ObjectStatus != nil {
		return *m.ObjectStatus
	}
	return 0
}

func (m *FinderObjectS) GetSendShareFavWording() string {
	if m != nil && m.SendShareFavWording != nil {
		return *m.SendShareFavWording
	}
	return ""
}

func (m *FinderObjectS) GetOriginalFlag() int32 {
	if m != nil && m.OriginalFlag != nil {
		return *m.OriginalFlag
	}
	return 0
}

func (m *FinderObjectS) GetSecondaryShowFlag() int32 {
	if m != nil && m.SecondaryShowFlag != nil {
		return *m.SecondaryShowFlag
	}
	return 0
}

func (m *FinderObjectS) GetTipsWording() string {
	if m != nil && m.TipsWording != nil {
		return *m.TipsWording
	}
	return ""
}

func (m *FinderObjectS) GetOrgRecommendType() int32 {
	if m != nil && m.OrgRecommendType != nil {
		return *m.OrgRecommendType
	}
	return 0
}

type Tabs struct {
	Name *string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	Id   *int64  `protobuf:"varint,2,rep,name=id" json:"id,omitempty"`
}

func (m *Tabs) Reset()         { *m = Tabs{} }
func (m *Tabs) String() string { return proto.CompactTextString(m) }
func (*Tabs) ProtoMessage()    {}
func (*Tabs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{3}
}

func (m *Tabs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tabs.Unmarshal(m, b)
}
func (m *Tabs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tabs.Marshal(b, m, deterministic)
}
func (m *Tabs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tabs.Merge(m, src)
}
func (m *Tabs) XXX_Size() int {
	return xxx_messageInfo_Tabs.Size(m)
}
func (m *Tabs) XXX_DiscardUnknown() {
	xxx_messageInfo_Tabs.DiscardUnknown(m)
}

var xxx_messageInfo_Tabs proto.InternalMessageInfo

func (m *Tabs) GetName() *string {
	if m != nil {
		return m.Name
	}
	return nil
}
func (m *Tabs) GetId() *int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type FinderUserPageResponse struct {
	BaseResponse          *BaseResponse             `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	Object                []*FinderObjectS          `protobuf:"bytes,2,rep,name=object" json:"object,omitempty"`
	FirstPageMd5          *string                   `protobuf:"bytes,3,opt,name=firstPageMd5" json:"firstPageMd5,omitempty"`
	FinderUserInfo        *FinderUserInfo           `protobuf:"bytes,4,opt,name=finderUserInfo" json:"finderUserInfo,omitempty"`
	Contact               *FinderContact            `protobuf:"bytes,5,opt,name=contact" json:"contact,omitempty"`
	FeedsCount            *int32                    `protobuf:"varint,6,opt,name=feedsCount" json:"feedsCount,omitempty"`
	ContinueFlag          *int32                    `protobuf:"varint,7,opt,name=continueFlag" json:"continueFlag,omitempty"`
	VerifyInfo            *FinderNicknameVerifyInfo `protobuf:"bytes,8,opt,name=verifyInfo" json:"verifyInfo,omitempty"`
	FansCount             *int32                    `protobuf:"varint,9,opt,name=fansCount" json:"fansCount,omitempty"`
	LastBuffer            []byte                    `protobuf:"bytes,10,opt,name=lastBuffer" json:"lastBuffer,omitempty"`
	FriendFollowCount     *int32                    `protobuf:"varint,11,opt,name=friendFollowCount" json:"friendFollowCount,omitempty"`
	UserTags              [][]byte                  `protobuf:"bytes,12,rep,name=userTags" json:"userTags,omitempty"`
	OriginalEnctranceFlag *int32                    `protobuf:"varint,13,opt,name=originalEnctranceFlag" json:"originalEnctranceFlag,omitempty"`
	listTab               []*Tabs                   `protobuf:"bytes,20,opt,name=listTab" json:"listTab,omitempty"`
	Num                   *int32                    `protobuf:"varint,21,opt,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                  `json:"-"`
	XXX_unrecognized      []byte                    `json:"-"`
	XXX_sizecache         int32                     `json:"-"`
}

func (m *FinderUserPageResponse) Reset()         { *m = FinderUserPageResponse{} }
func (m *FinderUserPageResponse) String() string { return proto.CompactTextString(m) }
func (*FinderUserPageResponse) ProtoMessage()    {}
func (*FinderUserPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d25374d77b8f123, []int{14}
}
func (m *FinderUserPageResponse) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}
func (m *FinderUserPageResponse) GetListTab() []*Tabs {
	if m != nil && m.listTab != nil {
		return m.listTab
	}
	return nil
}
func (m *FinderUserPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinderUserPageResponse.Unmarshal(m, b)
}
func (m *FinderUserPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinderUserPageResponse.Marshal(b, m, deterministic)
}
func (m *FinderUserPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinderUserPageResponse.Merge(m, src)
}
func (m *FinderUserPageResponse) XXX_Size() int {
	return xxx_messageInfo_FinderUserPageResponse.Size(m)
}
func (m *FinderUserPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinderUserPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinderUserPageResponse proto.InternalMessageInfo

func (m *FinderUserPageResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *FinderUserPageResponse) GetObject() []*FinderObjectS {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *FinderUserPageResponse) GetFirstPageMd5() string {
	if m != nil && m.FirstPageMd5 != nil {
		return *m.FirstPageMd5
	}
	return ""
}

func (m *FinderUserPageResponse) GetFinderUserInfo() *FinderUserInfo {
	if m != nil {
		return m.FinderUserInfo
	}
	return nil
}

func (m *FinderUserPageResponse) GetContact() *FinderContact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *FinderUserPageResponse) GetFeedsCount() int32 {
	if m != nil && m.FeedsCount != nil {
		return *m.FeedsCount
	}
	return 0
}

func (m *FinderUserPageResponse) GetContinueFlag() int32 {
	if m != nil && m.ContinueFlag != nil {
		return *m.ContinueFlag
	}
	return 0
}

func (m *FinderUserPageResponse) GetVerifyInfo() *FinderNicknameVerifyInfo {
	if m != nil {
		return m.VerifyInfo
	}
	return nil
}

func (m *FinderUserPageResponse) GetFansCount() int32 {
	if m != nil && m.FansCount != nil {
		return *m.FansCount
	}
	return 0
}

func (m *FinderUserPageResponse) GetLastBuffer() []byte {
	if m != nil {
		return m.LastBuffer
	}
	return nil
}

func (m *FinderUserPageResponse) GetFriendFollowCount() int32 {
	if m != nil && m.FriendFollowCount != nil {
		return *m.FriendFollowCount
	}
	return 0
}

func (m *FinderUserPageResponse) GetUserTags() [][]byte {
	if m != nil {
		return m.UserTags
	}
	return nil
}

func (m *FinderUserPageResponse) GetOriginalEnctranceFlag() int32 {
	if m != nil && m.OriginalEnctranceFlag != nil {
		return *m.OriginalEnctranceFlag
	}
	return 0
}

func init() {
	proto.RegisterType((*FinderSyncRequest)(nil), "wechat_proto.FinderSyncRequest")
	proto.RegisterType((*FinderStatsReportResponse)(nil), "wechat_proto.FinderStatsReportResponse")
	proto.RegisterType((*FinderSearchRequest)(nil), "wechat_proto.FinderSearchRequest")
	proto.RegisterType((*FinderTxRequest)(nil), "wechat_proto.FinderTxRequest")
	proto.RegisterType((*FinderZd)(nil), "wechat_proto.FinderZd")
	proto.RegisterType((*FinderSearchResponse)(nil), "wechat_proto.FinderSearchResponse")
	proto.RegisterType((*FinderObject)(nil), "wechat_proto.FinderObject")
	proto.RegisterType((*FinderVtm)(nil), "wechat_proto.FinderVtm")
	proto.RegisterType((*FinderContact)(nil), "wechat_proto.FinderContact")
	proto.RegisterType((*FinderAqt)(nil), "wechat_proto.FinderAqt")
	proto.RegisterType((*FinderUserPrepareRequest)(nil), "wechat_proto.FinderUserPrepareRequest")
	proto.RegisterType((*FinderUserPrepareResponse)(nil), "wechat_proto.FinderUserPrepareResponse")
	proto.RegisterType((*FinderNicknameVerifyInfo)(nil), "wechat_proto.FinderNicknameVerifyInfo")
	proto.RegisterType((*FinderFollowRequest)(nil), "wechat_proto.FinderFollowRequest")
	proto.RegisterType((*FinderFollowResponse)(nil), "wechat_proto.FinderFollowResponse")
}

func init() { proto.RegisterFile("findersync.proto", fileDescriptor_3d25374d77b8f123) }

var fileDescriptor_3d25374d77b8f123 = []byte{
	// 1182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0xc6, 0xae, 0x24, 0xdb, 0xa2, 0x64, 0xc7, 0x61, 0xdc, 0x54, 0x71, 0xda, 0x40, 0x58, 0x04,
	0x86, 0x7b, 0x71, 0x11, 0xd9, 0xbe, 0xd4, 0x68, 0x01, 0xdb, 0xb0, 0x14, 0x23, 0x49, 0x6d, 0x50,
	0xb2, 0x0b, 0xa4, 0x87, 0x62, 0xb3, 0x4b, 0xc9, 0x5b, 0x4b, 0x5c, 0x99, 0x4b, 0x39, 0xd6, 0x03,
	0xf4, 0xd8, 0x5e, 0x7a, 0xef, 0xb5, 0xf7, 0x1e, 0xfa, 0x08, 0x7d, 0x9a, 0x3e, 0x44, 0x31, 0x43,
	0x72, 0x7f, 0x94, 0x05, 0x1a, 0x04, 0xbe, 0x71, 0xbe, 0x99, 0x25, 0xbf, 0xe1, 0xcc, 0x7c, 0x5c,
	0xb2, 0x3e, 0x8c, 0x44, 0xc8, 0x65, 0x32, 0x17, 0xc1, 0xce, 0x54, 0xc6, 0x2a, 0xa6, 0xcd, 0xf7,
	0x3c, 0xb8, 0xf2, 0xd5, 0x4f, 0x68, 0x6d, 0x1a, 0x4b, 0xfb, 0xbc, 0x47, 0xe4, 0x61, 0x17, 0xe3,
	0xfb, 0x73, 0x11, 0x30, 0x7e, 0x33, 0xe3, 0x89, 0xf2, 0x9e, 0x92, 0x27, 0x06, 0x54, 0xbe, 0x4a,
	0x18, 0x9f, 0xc6, 0x52, 0x31, 0x9e, 0x4c, 0x63, 0x91, 0x70, 0xef, 0x17, 0x97, 0x3c, 0x32, 0x5e,
	0xee, 0xcb, 0xe0, 0xca, 0x7c, 0x44, 0x0f, 0x48, 0xe3, 0x9d, 0x9f, 0x70, 0x63, 0xb6, 0x9c, 0xb6,
	0xb3, 0xdd, 0xe8, 0x3c, 0xd9, 0xc9, 0x9f, 0xbd, 0x73, 0x94, 0x05, 0xb0, 0x7c, 0x34, 0x6d, 0x91,
	0xe5, 0x8b, 0x84, 0xcb, 0x57, 0x7c, 0xde, 0x72, 0xdb, 0xce, 0x76, 0x9d, 0x59, 0x93, 0x3e, 0x26,
	0x4b, 0x67, 0xc3, 0x61, 0xc2, 0x55, 0xab, 0xd2, 0x76, 0xb6, 0x57, 0x99, 0xb1, 0x68, 0x93, 0x38,
	0x83, 0x56, 0xb5, 0xed, 0x6c, 0x37, 0x99, 0x33, 0xa0, 0x1b, 0xa4, 0xd6, 0x0f, 0xb8, 0xe0, 0xad,
	0x1a, 0x06, 0x69, 0x83, 0x52, 0x52, 0xbd, 0x98, 0x45, 0x61, 0x6b, 0x09, 0xb7, 0xc4, 0x35, 0xed,
	0x91, 0x07, 0x9a, 0xfd, 0xe0, 0xce, 0x52, 0x5d, 0x46, 0xaa, 0x5f, 0x16, 0xa9, 0x2e, 0x04, 0xb1,
	0xc5, 0xaf, 0xbc, 0x3f, 0x9d, 0x0f, 0x76, 0xb2, 0x69, 0xdc, 0x72, 0x89, 0xf9, 0xd7, 0x98, 0x35,
	0x33, 0x82, 0x2e, 0xe2, 0x86, 0x60, 0x9b, 0x34, 0x4e, 0xee, 0x54, 0x7f, 0xea, 0x4f, 0x4e, 0xc5,
	0x30, 0xc6, 0x0c, 0x9b, 0x2c, 0x0f, 0x65, 0x69, 0xd6, 0x20, 0xcd, 0xe7, 0xc4, 0xe9, 0x61, 0x8a,
	0x8d, 0xce, 0xe3, 0x32, 0xba, 0x6f, 0x43, 0xe6, 0xf4, 0xe8, 0x1a, 0x71, 0x07, 0x23, 0x4c, 0xba,
	0xc2, 0xdc, 0xc1, 0xc8, 0xfb, 0x86, 0xac, 0x58, 0x37, 0xf8, 0x7a, 0x2f, 0x90, 0x5c, 0x9d, 0xb9,
	0xbd, 0x17, 0x68, 0x77, 0xcc, 0x9d, 0xbb, 0xbd, 0x0e, 0xda, 0xbb, 0x48, 0x04, 0xec, 0x5d, 0xef,
	0x77, 0x97, 0x6c, 0x14, 0xab, 0xad, 0xdb, 0x80, 0x7e, 0x47, 0x9a, 0xba, 0x80, 0xda, 0x36, 0xf5,
	0xde, 0x2c, 0xab, 0xb7, 0x8e, 0x60, 0x85, 0x78, 0xfa, 0x15, 0xa9, 0x5c, 0xaa, 0x49, 0xcb, 0x6d,
	0x57, 0xb6, 0x1b, 0x9d, 0xcf, 0xcb, 0x92, 0xb9, 0x54, 0x13, 0x06, 0x31, 0x0b, 0x2d, 0x50, 0x4b,
	0x5b, 0xc0, 0x23, 0xcd, 0xe3, 0x58, 0xa8, 0x48, 0xcc, 0x78, 0x77, 0xec, 0x8f, 0xcc, 0x35, 0x15,
	0x30, 0xda, 0x21, 0x4b, 0x67, 0xef, 0x7e, 0xe6, 0x81, 0x32, 0xd7, 0xb6, 0x59, 0x76, 0x92, 0x8e,
	0x60, 0x26, 0x52, 0xdf, 0xf9, 0x92, 0x6d, 0x2d, 0xdb, 0x44, 0xcb, 0x59, 0x13, 0x79, 0x1e, 0x69,
	0xe6, 0xbf, 0x84, 0x18, 0x2c, 0xa0, 0x83, 0x1f, 0xe1, 0xda, 0xfb, 0xc7, 0x21, 0xf5, 0x34, 0x11,
	0xba, 0x4f, 0x96, 0x81, 0x97, 0x1f, 0xd8, 0xc9, 0x78, 0x5a, 0x46, 0xc4, 0x84, 0x30, 0x1b, 0x0b,
	0x1b, 0xbf, 0x54, 0x93, 0xb1, 0x29, 0x10, 0xae, 0xe9, 0x26, 0x59, 0x39, 0x15, 0x4a, 0xc6, 0xe1,
	0x2c, 0x30, 0x85, 0x4a, 0x6d, 0xfa, 0x05, 0xa9, 0x77, 0x7d, 0x91, 0x1c, 0xc7, 0x33, 0xa1, 0xcc,
	0x7d, 0x64, 0x00, 0x5c, 0x58, 0x57, 0x46, 0x5c, 0x84, 0xdd, 0x78, 0x3c, 0x8e, 0xdf, 0xe3, 0x95,
	0xd4, 0x58, 0x01, 0xa3, 0xeb, 0xa4, 0xd2, 0x3b, 0x8d, 0xcd, 0xc8, 0xc0, 0xd2, 0xfb, 0xab, 0x4a,
	0x56, 0x0b, 0xf4, 0x80, 0x01, 0xf4, 0xb5, 0xf0, 0x27, 0xdc, 0xb4, 0x52, 0x6a, 0x83, 0xef, 0xfb,
	0x28, 0xb8, 0x46, 0x9f, 0x66, 0x9d, 0xda, 0x30, 0x1e, 0x2f, 0xb9, 0x1f, 0x5e, 0xc8, 0xb1, 0x21,
	0x6e, 0x4d, 0x38, 0xb5, 0xcf, 0x6f, 0x90, 0x71, 0x95, 0xc1, 0x12, 0x32, 0xe9, 0x47, 0x23, 0xe1,
	0xab, 0x99, 0xd4, 0x53, 0x5d, 0x67, 0x19, 0x40, 0x9f, 0x11, 0xa2, 0xf9, 0x62, 0xe1, 0x97, 0x30,
	0x8f, 0x1c, 0x92, 0xf9, 0x07, 0xd1, 0x84, 0x63, 0xe9, 0x52, 0x3f, 0x20, 0xc0, 0xf2, 0x70, 0xa6,
	0xae, 0xb0, 0x68, 0x2b, 0x58, 0xb4, 0xd4, 0x86, 0xa1, 0x3c, 0x8e, 0x6f, 0xb9, 0x3c, 0x9d, 0x8c,
	0x80, 0x69, 0x1d, 0xcf, 0xce, 0x43, 0xb0, 0x3b, 0x0c, 0x28, 0xa8, 0xe3, 0x2c, 0x69, 0x11, 0xbd,
	0x7b, 0x86, 0x40, 0x9e, 0x27, 0x77, 0x0a, 0xa9, 0x35, 0xb4, 0x0c, 0x18, 0xd3, 0x78, 0xf0, 0xd8,
	0x26, 0x1e, 0x6b, 0x4d, 0xa8, 0xcd, 0x99, 0x8c, 0x46, 0x91, 0xf0, 0xc7, 0xf8, 0xe1, 0xaa, 0xae,
	0x4d, 0x1e, 0xa3, 0x07, 0x59, 0x0c, 0x6e, 0xb1, 0x86, 0x9d, 0x54, 0x3a, 0x3c, 0x87, 0x37, 0x8a,
	0x15, 0x82, 0x81, 0xf4, 0xeb, 0xe8, 0x96, 0x1b, 0xd2, 0x0f, 0x34, 0xe9, 0x0c, 0x01, 0x6a, 0x6f,
	0x92, 0x11, 0xee, 0xbb, 0xae, 0xa9, 0x19, 0x93, 0x76, 0xc8, 0x86, 0xdd, 0xe9, 0x44, 0x28, 0xe9,
	0x8b, 0x40, 0xcf, 0xdb, 0x43, 0xdc, 0xa3, 0xd4, 0xe7, 0xfd, 0x68, 0x9b, 0xff, 0xf0, 0x46, 0xe5,
	0x44, 0xa7, 0xb6, 0x20, 0x3a, 0xb5, 0x05, 0xd1, 0x01, 0x7b, 0x17, 0xed, 0x3d, 0xd3, 0xbe, 0x6e,
	0x6f, 0x0f, 0xed, 0x7d, 0xd3, 0xad, 0x6e, 0x6f, 0xdf, 0xfb, 0xdb, 0x21, 0x2d, 0xbd, 0x3b, 0xb4,
	0xdd, 0xb9, 0xe4, 0x53, 0x5f, 0xf2, 0x7b, 0x79, 0x87, 0xca, 0x65, 0xba, 0xe4, 0xcd, 0xa8, 0x7c,
	0xd2, 0x9b, 0xf1, 0x6f, 0xc5, 0xbe, 0xac, 0x05, 0xe2, 0xf7, 0x24, 0xa9, 0xcf, 0x08, 0x39, 0x0c,
	0x54, 0x14, 0x8b, 0xc1, 0x7c, 0x6a, 0x33, 0xc8, 0x21, 0xb4, 0x4b, 0xc8, 0x25, 0x97, 0xd1, 0x70,
	0x9e, 0x3e, 0x36, 0x8d, 0xce, 0x56, 0x59, 0x06, 0x76, 0x60, 0xb3, 0x68, 0x96, 0xfb, 0x92, 0x7e,
	0x4b, 0x1a, 0x7d, 0x3e, 0x1e, 0x5a, 0x3d, 0xab, 0xfe, 0xbf, 0x9e, 0xe5, 0xe3, 0xad, 0x7a, 0x60,
	0x0b, 0xe9, 0x9a, 0xa6, 0x36, 0xdd, 0x23, 0x9f, 0xd9, 0xc3, 0xdf, 0xc4, 0x61, 0x34, 0x9c, 0xff,
	0x10, 0xcb, 0x30, 0x12, 0x23, 0xa3, 0x47, 0xe5, 0x4e, 0xd4, 0xac, 0x57, 0x81, 0x51, 0x68, 0x58,
	0x6a, 0x24, 0xc4, 0xd1, 0x46, 0x24, 0xd4, 0x08, 0xc7, 0x69, 0xae, 0x01, 0xc2, 0xb5, 0xcc, 0x13,
	0xfb, 0xb4, 0xa2, 0x7f, 0x68, 0xe6, 0x15, 0x96, 0xe0, 0xef, 0xe1, 0x94, 0xd6, 0xe0, 0x51, 0x45,
	0xbf, 0x1e, 0xcb, 0x26, 0xf8, 0x47, 0xd8, 0x95, 0x03, 0x9c, 0x41, 0xe8, 0x4a, 0xb3, 0x43, 0x64,
	0x26, 0x0b, 0x96, 0xde, 0x1f, 0xae, 0xed, 0xd3, 0x0f, 0x6f, 0x14, 0x06, 0x5e, 0x5b, 0xe7, 0x92,
	0x0f, 0xa3, 0x3b, 0x23, 0xa4, 0x05, 0x8c, 0x3e, 0x27, 0xab, 0x47, 0xbe, 0x10, 0x5c, 0xda, 0x6b,
	0xd0, 0x8a, 0x5a, 0x04, 0xa1, 0xee, 0xfa, 0xab, 0xd7, 0x91, 0xb8, 0x36, 0xca, 0x9a, 0x43, 0x60,
	0xb2, 0x0f, 0xa7, 0x53, 0x54, 0xe4, 0xaa, 0x96, 0x5d, 0x63, 0xd2, 0x2d, 0xb2, 0xa6, 0xe3, 0x52,
	0xc9, 0xd6, 0x4a, 0xbb, 0x80, 0xc2, 0x09, 0xa0, 0xd4, 0x46, 0x11, 0x75, 0x2d, 0x72, 0x08, 0x94,
	0xf4, 0x44, 0x4a, 0x3d, 0x39, 0x5a, 0x6c, 0x53, 0x5b, 0x5f, 0xa3, 0x2e, 0x84, 0xd3, 0xd3, 0x97,
	0xae, 0x25, 0xd5, 0x19, 0x78, 0xbf, 0xa5, 0xff, 0x92, 0x5a, 0x9b, 0xed, 0x18, 0x6e, 0x91, 0xb5,
	0x6c, 0x4c, 0x72, 0x4f, 0xc9, 0x02, 0x8a, 0x7f, 0x06, 0x53, 0xec, 0x76, 0xfb, 0x67, 0x80, 0x16,
	0x48, 0x38, 0xe3, 0x43, 0xfd, 0x38, 0x9f, 0x86, 0xe6, 0x59, 0xc9, 0x43, 0x70, 0xc2, 0x79, 0x9c,
	0xa8, 0xdc, 0x09, 0x26, 0xf3, 0x22, 0x4a, 0x0f, 0xac, 0x8e, 0x31, 0x7e, 0xf3, 0x71, 0x3f, 0x8a,
	0x59, 0x3c, 0xbc, 0xde, 0xc7, 0x71, 0x7c, 0x6d, 0xb2, 0xc7, 0x35, 0xbc, 0x6b, 0x27, 0x42, 0x71,
	0x89, 0xac, 0x75, 0x37, 0x66, 0x80, 0xf7, 0xab, 0x63, 0x7f, 0xb7, 0xec, 0x85, 0xdc, 0x93, 0x36,
	0xe4, 0xfe, 0x3f, 0xdc, 0x8f, 0xff, 0xff, 0x38, 0x6a, 0xbc, 0xad, 0xef, 0xec, 0x7c, 0xad, 0x23,
	0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x65, 0xfb, 0xff, 0x77, 0x5a, 0x0c, 0x00, 0x00,
}
