// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hybrid.proto

package wechat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EcdhPacket struct {
	Type                 *uint32  `protobuf:"varint,1,req,name=Type" json:"Type,omitempty"`
	Key                  *BufferT `protobuf:"bytes,2,req,name=Key" json:"Key,omitempty"`
	Token                []byte   `protobuf:"bytes,3,req,name=Token" json:"Token,omitempty"`
	Url                  *string  `protobuf:"bytes,4,opt,name=Url" json:"Url,omitempty"`
	ProtobufData         []byte   `protobuf:"bytes,5,opt,name=ProtobufData" json:"ProtobufData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EcdhPacket) Reset()         { *m = EcdhPacket{} }
func (m *EcdhPacket) String() string { return proto.CompactTextString(m) }
func (*EcdhPacket) ProtoMessage()    {}
func (*EcdhPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f516b268995d746, []int{0}
}

func (m *EcdhPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhPacket.Unmarshal(m, b)
}
func (m *EcdhPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhPacket.Marshal(b, m, deterministic)
}
func (m *EcdhPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhPacket.Merge(m, src)
}
func (m *EcdhPacket) XXX_Size() int {
	return xxx_messageInfo_EcdhPacket.Size(m)
}
func (m *EcdhPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhPacket.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhPacket proto.InternalMessageInfo

func (m *EcdhPacket) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *EcdhPacket) GetKey() *BufferT {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *EcdhPacket) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *EcdhPacket) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *EcdhPacket) GetProtobufData() []byte {
	if m != nil {
		return m.ProtobufData
	}
	return nil
}

type HybridDecryptResponse struct {
	Key                  *BufferT `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Type                 *uint32  `protobuf:"varint,2,req,name=Type" json:"Type,omitempty"`
	ProtobufData         []byte   `protobuf:"bytes,3,req,name=ProtobufData" json:"ProtobufData,omitempty"`
	Token                []byte   `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HybridDecryptResponse) Reset()         { *m = HybridDecryptResponse{} }
func (m *HybridDecryptResponse) String() string { return proto.CompactTextString(m) }
func (*HybridDecryptResponse) ProtoMessage()    {}
func (*HybridDecryptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f516b268995d746, []int{1}
}

func (m *HybridDecryptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HybridDecryptResponse.Unmarshal(m, b)
}
func (m *HybridDecryptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HybridDecryptResponse.Marshal(b, m, deterministic)
}
func (m *HybridDecryptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HybridDecryptResponse.Merge(m, src)
}
func (m *HybridDecryptResponse) XXX_Size() int {
	return xxx_messageInfo_HybridDecryptResponse.Size(m)
}
func (m *HybridDecryptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HybridDecryptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HybridDecryptResponse proto.InternalMessageInfo

func (m *HybridDecryptResponse) GetKey() *BufferT {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *HybridDecryptResponse) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *HybridDecryptResponse) GetProtobufData() []byte {
	if m != nil {
		return m.ProtobufData
	}
	return nil
}

func (m *HybridDecryptResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type HybridEcdhRequest struct {
	Type                 *int32   `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	SecECDHKey           *BufferT `protobuf:"bytes,2,opt,name=SecECDHKey" json:"SecECDHKey,omitempty"`
	Randomkeydata        []byte   `protobuf:"bytes,3,opt,name=randomkeydata" json:"randomkeydata,omitempty"`
	Randomkeyextenddata  []byte   `protobuf:"bytes,4,opt,name=randomkeyextenddata" json:"randomkeyextenddata,omitempty"`
	Encyptdata           []byte   `protobuf:"bytes,5,opt,name=encyptdata" json:"encyptdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HybridEcdhRequest) Reset()         { *m = HybridEcdhRequest{} }
func (m *HybridEcdhRequest) String() string { return proto.CompactTextString(m) }
func (*HybridEcdhRequest) ProtoMessage()    {}
func (*HybridEcdhRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f516b268995d746, []int{2}
}

func (m *HybridEcdhRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HybridEcdhRequest.Unmarshal(m, b)
}
func (m *HybridEcdhRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HybridEcdhRequest.Marshal(b, m, deterministic)
}
func (m *HybridEcdhRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HybridEcdhRequest.Merge(m, src)
}
func (m *HybridEcdhRequest) XXX_Size() int {
	return xxx_messageInfo_HybridEcdhRequest.Size(m)
}
func (m *HybridEcdhRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HybridEcdhRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HybridEcdhRequest proto.InternalMessageInfo

func (m *HybridEcdhRequest) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *HybridEcdhRequest) GetSecECDHKey() *BufferT {
	if m != nil {
		return m.SecECDHKey
	}
	return nil
}

func (m *HybridEcdhRequest) GetRandomkeydata() []byte {
	if m != nil {
		return m.Randomkeydata
	}
	return nil
}

func (m *HybridEcdhRequest) GetRandomkeyextenddata() []byte {
	if m != nil {
		return m.Randomkeyextenddata
	}
	return nil
}

func (m *HybridEcdhRequest) GetEncyptdata() []byte {
	if m != nil {
		return m.Encyptdata
	}
	return nil
}

type HybridEcdhResponse struct {
	SecECDHKey           *BufferT `protobuf:"bytes,1,opt,name=SecECDHKey" json:"SecECDHKey,omitempty"`
	Type                 *int32   `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Decryptdata          []byte   `protobuf:"bytes,3,opt,name=decryptdata" json:"decryptdata,omitempty"`
	Randomkeyextenddata  []byte   `protobuf:"bytes,4,opt,name=randomkeyextenddata" json:"randomkeyextenddata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HybridEcdhResponse) Reset()         { *m = HybridEcdhResponse{} }
func (m *HybridEcdhResponse) String() string { return proto.CompactTextString(m) }
func (*HybridEcdhResponse) ProtoMessage()    {}
func (*HybridEcdhResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f516b268995d746, []int{3}
}

func (m *HybridEcdhResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HybridEcdhResponse.Unmarshal(m, b)
}
func (m *HybridEcdhResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HybridEcdhResponse.Marshal(b, m, deterministic)
}
func (m *HybridEcdhResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HybridEcdhResponse.Merge(m, src)
}
func (m *HybridEcdhResponse) XXX_Size() int {
	return xxx_messageInfo_HybridEcdhResponse.Size(m)
}
func (m *HybridEcdhResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HybridEcdhResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HybridEcdhResponse proto.InternalMessageInfo

func (m *HybridEcdhResponse) GetSecECDHKey() *BufferT {
	if m != nil {
		return m.SecECDHKey
	}
	return nil
}

func (m *HybridEcdhResponse) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *HybridEcdhResponse) GetDecryptdata() []byte {
	if m != nil {
		return m.Decryptdata
	}
	return nil
}

func (m *HybridEcdhResponse) GetRandomkeyextenddata() []byte {
	if m != nil {
		return m.Randomkeyextenddata
	}
	return nil
}

func init() {
	proto.RegisterType((*EcdhPacket)(nil), "wechat_proto.EcdhPacket")
	proto.RegisterType((*HybridDecryptResponse)(nil), "wechat_proto.HybridDecryptResponse")
	proto.RegisterType((*HybridEcdhRequest)(nil), "wechat_proto.HybridEcdhRequest")
	proto.RegisterType((*HybridEcdhResponse)(nil), "wechat_proto.HybridEcdhResponse")
}

func init() { proto.RegisterFile("hybrid.proto", fileDescriptor_0f516b268995d746) }

var fileDescriptor_0f516b268995d746 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x33, 0x05, 0x16, 0x5c, 0x4a, 0xa2, 0xd7, 0x9f, 0x34, 0x2e, 0x4c, 0xd3, 0xb8, 0x98,
	0x55, 0x35, 0x2e, 0x7c, 0x00, 0x84, 0x84, 0xc4, 0x0d, 0x19, 0x71, 0xe3, 0x86, 0x94, 0xce, 0x25,
	0x18, 0xb4, 0xad, 0x65, 0x88, 0xf6, 0x29, 0xdc, 0xf9, 0x24, 0xbe, 0x8b, 0xaf, 0x63, 0x66, 0x06,
	0x70, 0x6a, 0x8c, 0x3f, 0xbb, 0x7b, 0xce, 0xdc, 0x76, 0xce, 0x77, 0x06, 0xfc, 0x79, 0x35, 0x2d,
	0xef, 0x64, 0x5c, 0x94, 0xb9, 0xca, 0xd1, 0x7f, 0xa2, 0x74, 0x9e, 0xa8, 0x89, 0x51, 0x47, 0x6b,
	0x65, 0xcf, 0xa2, 0x57, 0x06, 0x30, 0x48, 0xe5, 0x7c, 0x94, 0xa4, 0x0b, 0x52, 0x88, 0xd0, 0x1c,
	0x57, 0x05, 0x05, 0x2c, 0xf4, 0x78, 0x57, 0x98, 0x19, 0x39, 0x34, 0xae, 0xa8, 0x0a, 0xbc, 0xd0,
	0xe3, 0x9d, 0xf3, 0xc3, 0xd8, 0xfd, 0x59, 0xdc, 0x5b, 0xcd, 0x66, 0x54, 0x4e, 0x94, 0xd0, 0x2b,
	0xb8, 0x0f, 0xad, 0x71, 0xbe, 0xa0, 0x2c, 0x68, 0x84, 0x1e, 0xf7, 0x85, 0x15, 0xb8, 0x03, 0x8d,
	0x9b, 0xf2, 0x3e, 0x68, 0x86, 0x8c, 0xb7, 0x85, 0x1e, 0x31, 0x02, 0x7f, 0xa4, 0x3f, 0x9f, 0xae,
	0x66, 0xfd, 0x44, 0x25, 0x41, 0x2b, 0x64, 0xdc, 0x17, 0x35, 0x2f, 0x7a, 0x61, 0x70, 0x30, 0x34,
	0x14, 0x7d, 0x4a, 0xcb, 0xaa, 0x50, 0x82, 0x96, 0x45, 0x9e, 0x2d, 0xb7, 0x79, 0xd8, 0xef, 0x79,
	0x36, 0x34, 0x9e, 0x43, 0xf3, 0xf5, 0x6e, 0x1b, 0xb5, 0xe6, 0x69, 0x0e, 0x65, 0x38, 0x9a, 0x26,
	0x98, 0x15, 0xd1, 0x3b, 0x83, 0x5d, 0x9b, 0x48, 0x17, 0x26, 0xe8, 0x71, 0x45, 0x4b, 0xd3, 0x98,
	0xb2, 0x8d, 0x31, 0xde, 0x12, 0x66, 0xc6, 0x0b, 0x80, 0x6b, 0x4a, 0x07, 0x97, 0xfd, 0xa1, 0x2d,
	0x8e, 0xfd, 0x10, 0xd4, 0xd9, 0xc4, 0x13, 0xe8, 0x96, 0x49, 0x26, 0xf3, 0x87, 0x05, 0x55, 0xd2,
	0x86, 0xd3, 0xf7, 0xd7, 0x4d, 0x3c, 0x83, 0xbd, 0xad, 0x41, 0xcf, 0x8a, 0x32, 0x69, 0x76, 0x6d,
	0xd6, 0xef, 0x8e, 0xf0, 0x18, 0x80, 0xb2, 0xb4, 0x2a, 0x94, 0xfc, 0x6c, 0xdb, 0x71, 0xa2, 0x37,
	0x06, 0xe8, 0x92, 0xad, 0x8b, 0xae, 0x63, 0xb0, 0x3f, 0x63, 0x6c, 0x2a, 0xf1, 0x9c, 0x4a, 0x42,
	0xe8, 0x48, 0xfb, 0x8e, 0x0e, 0x98, 0x6b, 0xfd, 0x1f, 0xab, 0xd7, 0xb9, 0x6d, 0xc7, 0xf1, 0xa9,
	0xcd, 0xf3, 0x11, 0x00, 0x00, 0xff, 0xff, 0x49, 0xcb, 0xa5, 0xa2, 0xf3, 0x02, 0x00, 0x00,
}
