// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package wechat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BindOpMobileForRegRequest struct {
	BaseRequest          *BaseRequest      `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	Mobile               *string           `protobuf:"bytes,3,opt,name=Mobile" json:"Mobile,omitempty"`
	Opcode               *int64            `protobuf:"varint,4,opt,name=Opcode" json:"Opcode,omitempty"`
	Verifycode           *string           `protobuf:"bytes,5,opt,name=Verifycode" json:"Verifycode,omitempty"`
	SafeDeviceName       *string           `protobuf:"bytes,10,opt,name=SafeDeviceName" json:"SafeDeviceName,omitempty"`
	SafeDeviceType       *string           `protobuf:"bytes,11,opt,name=SafeDeviceType" json:"SafeDeviceType,omitempty"`
	RandomEncryKey       *SKBuiltinString_ `protobuf:"bytes,12,opt,name=RandomEncryKey" json:"RandomEncryKey,omitempty"`
	Language             *string           `protobuf:"bytes,13,opt,name=Language" json:"Language,omitempty"`
	InputMobileReTrYs    *uint32           `protobuf:"varint,14,opt,name=InputMobileReTrYs" json:"InputMobileReTrYs,omitempty"`
	AdjustRet            *uint32           `protobuf:"varint,15,opt,name=AdjustRet" json:"AdjustRet,omitempty"`
	ClientSeqID          *string           `protobuf:"bytes,16,opt,name=ClientSeqID" json:"ClientSeqID,omitempty"`
	DialLang             *string           `protobuf:"bytes,18,opt,name=DialLang" json:"DialLang,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BindOpMobileForRegRequest) Reset()         { *m = BindOpMobileForRegRequest{} }
func (m *BindOpMobileForRegRequest) String() string { return proto.CompactTextString(m) }
func (*BindOpMobileForRegRequest) ProtoMessage()    {}
func (*BindOpMobileForRegRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *BindOpMobileForRegRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindOpMobileForRegRequest.Unmarshal(m, b)
}
func (m *BindOpMobileForRegRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindOpMobileForRegRequest.Marshal(b, m, deterministic)
}
func (m *BindOpMobileForRegRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindOpMobileForRegRequest.Merge(m, src)
}
func (m *BindOpMobileForRegRequest) XXX_Size() int {
	return xxx_messageInfo_BindOpMobileForRegRequest.Size(m)
}
func (m *BindOpMobileForRegRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindOpMobileForRegRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindOpMobileForRegRequest proto.InternalMessageInfo

func (m *BindOpMobileForRegRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *BindOpMobileForRegRequest) GetMobile() string {
	if m != nil && m.Mobile != nil {
		return *m.Mobile
	}
	return ""
}

func (m *BindOpMobileForRegRequest) GetOpcode() int64 {
	if m != nil && m.Opcode != nil {
		return *m.Opcode
	}
	return 0
}

func (m *BindOpMobileForRegRequest) GetVerifycode() string {
	if m != nil && m.Verifycode != nil {
		return *m.Verifycode
	}
	return ""
}

func (m *BindOpMobileForRegRequest) GetSafeDeviceName() string {
	if m != nil && m.SafeDeviceName != nil {
		return *m.SafeDeviceName
	}
	return ""
}

func (m *BindOpMobileForRegRequest) GetSafeDeviceType() string {
	if m != nil && m.SafeDeviceType != nil {
		return *m.SafeDeviceType
	}
	return ""
}

func (m *BindOpMobileForRegRequest) GetRandomEncryKey() *SKBuiltinString_ {
	if m != nil {
		return m.RandomEncryKey
	}
	return nil
}

func (m *BindOpMobileForRegRequest) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *BindOpMobileForRegRequest) GetInputMobileReTrYs() uint32 {
	if m != nil && m.InputMobileReTrYs != nil {
		return *m.InputMobileReTrYs
	}
	return 0
}

func (m *BindOpMobileForRegRequest) GetAdjustRet() uint32 {
	if m != nil && m.AdjustRet != nil {
		return *m.AdjustRet
	}
	return 0
}

func (m *BindOpMobileForRegRequest) GetClientSeqID() string {
	if m != nil && m.ClientSeqID != nil {
		return *m.ClientSeqID
	}
	return ""
}

func (m *BindOpMobileForRegRequest) GetDialLang() string {
	if m != nil && m.DialLang != nil {
		return *m.DialLang
	}
	return ""
}

type BindOpMobileForRegResponse struct {
	BaseResponse         *BaseResponse    `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	AuthTicket           *string          `protobuf:"bytes,10,opt,name=AuthTicket" json:"AuthTicket,omitempty"`
	BuiltinIPList        *BuiltinIPList   `protobuf:"bytes,8,opt,name=BuiltinIPList" json:"BuiltinIPList,omitempty"`
	Cc                   *string          `protobuf:"bytes,12,opt,name=Cc" json:"Cc,omitempty"`
	FormatedMobile       *string          `protobuf:"bytes,16,opt,name=FormatedMobile" json:"FormatedMobile,omitempty"`
	MmtlsControlBitFlag  *uint64          `protobuf:"varint,18,opt,name=MmtlsControlBitFlag" json:"MmtlsControlBitFlag,omitempty"`
	MobileCheckType      *uint64          `protobuf:"varint,21,opt,name=MobileCheckType" json:"MobileCheckType,omitempty"`
	NeedSetPwd           *uint64          `protobuf:"varint,4,opt,name=NeedSetPwd" json:"NeedSetPwd,omitempty"`
	NetworkControl       *NetworkControl  `protobuf:"bytes,9,opt,name=NetworkControl" json:"NetworkControl,omitempty"`
	NewHostList          *HostList        `protobuf:"bytes,7,opt,name=NewHostList" json:"NewHostList,omitempty"`
	ObsoleteItem1        *uint64          `protobuf:"varint,13,opt,name=ObsoleteItem1" json:"ObsoleteItem1,omitempty"`
	PureMobile           *string          `protobuf:"bytes,15,opt,name=PureMobile" json:"PureMobile,omitempty"`
	Pwd                  *string          `protobuf:"bytes,5,opt,name=Pwd" json:"Pwd,omitempty"`
	RegSessionId         *string          `protobuf:"bytes,22,opt,name=regSessionId" json:"regSessionId,omitempty"`
	SafeDevice           *uint64          `protobuf:"varint,11,opt,name=SafeDevice" json:"SafeDevice,omitempty"`
	SafeDeviceList       *SafeDeviceListV `protobuf:"bytes,14,opt,name=SafeDeviceList" json:"SafeDeviceList,omitempty"`
	ShowStyle            *ShowStyleKey    `protobuf:"bytes,17,opt,name=ShowStyle" json:"ShowStyle,omitempty"`
	SmsNo                *string          `protobuf:"bytes,3,opt,name=SmsNo" json:"SmsNo,omitempty"`
	SmsUpCode            *string          `protobuf:"bytes,19,opt,name=SmsUpCode" json:"SmsUpCode,omitempty"`
	SmsUpMobile          *string          `protobuf:"bytes,20,opt,name=SmsUpMobile" json:"SmsUpMobile,omitempty"`
	Ticket               *string          `protobuf:"bytes,2,opt,name=ticket" json:"ticket,omitempty"`
	Username             *string          `protobuf:"bytes,6,opt,name=Username" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BindOpMobileForRegResponse) Reset()         { *m = BindOpMobileForRegResponse{} }
func (m *BindOpMobileForRegResponse) String() string { return proto.CompactTextString(m) }
func (*BindOpMobileForRegResponse) ProtoMessage()    {}
func (*BindOpMobileForRegResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *BindOpMobileForRegResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindOpMobileForRegResponse.Unmarshal(m, b)
}
func (m *BindOpMobileForRegResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindOpMobileForRegResponse.Marshal(b, m, deterministic)
}
func (m *BindOpMobileForRegResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindOpMobileForRegResponse.Merge(m, src)
}
func (m *BindOpMobileForRegResponse) XXX_Size() int {
	return xxx_messageInfo_BindOpMobileForRegResponse.Size(m)
}
func (m *BindOpMobileForRegResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindOpMobileForRegResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindOpMobileForRegResponse proto.InternalMessageInfo

func (m *BindOpMobileForRegResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *BindOpMobileForRegResponse) GetAuthTicket() string {
	if m != nil && m.AuthTicket != nil {
		return *m.AuthTicket
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetBuiltinIPList() *BuiltinIPList {
	if m != nil {
		return m.BuiltinIPList
	}
	return nil
}

func (m *BindOpMobileForRegResponse) GetCc() string {
	if m != nil && m.Cc != nil {
		return *m.Cc
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetFormatedMobile() string {
	if m != nil && m.FormatedMobile != nil {
		return *m.FormatedMobile
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetMmtlsControlBitFlag() uint64 {
	if m != nil && m.MmtlsControlBitFlag != nil {
		return *m.MmtlsControlBitFlag
	}
	return 0
}

func (m *BindOpMobileForRegResponse) GetMobileCheckType() uint64 {
	if m != nil && m.MobileCheckType != nil {
		return *m.MobileCheckType
	}
	return 0
}

func (m *BindOpMobileForRegResponse) GetNeedSetPwd() uint64 {
	if m != nil && m.NeedSetPwd != nil {
		return *m.NeedSetPwd
	}
	return 0
}

func (m *BindOpMobileForRegResponse) GetNetworkControl() *NetworkControl {
	if m != nil {
		return m.NetworkControl
	}
	return nil
}

func (m *BindOpMobileForRegResponse) GetNewHostList() *HostList {
	if m != nil {
		return m.NewHostList
	}
	return nil
}

func (m *BindOpMobileForRegResponse) GetObsoleteItem1() uint64 {
	if m != nil && m.ObsoleteItem1 != nil {
		return *m.ObsoleteItem1
	}
	return 0
}

func (m *BindOpMobileForRegResponse) GetPureMobile() string {
	if m != nil && m.PureMobile != nil {
		return *m.PureMobile
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetRegSessionId() string {
	if m != nil && m.RegSessionId != nil {
		return *m.RegSessionId
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetSafeDevice() uint64 {
	if m != nil && m.SafeDevice != nil {
		return *m.SafeDevice
	}
	return 0
}

func (m *BindOpMobileForRegResponse) GetSafeDeviceList() *SafeDeviceListV {
	if m != nil {
		return m.SafeDeviceList
	}
	return nil
}

func (m *BindOpMobileForRegResponse) GetShowStyle() *ShowStyleKey {
	if m != nil {
		return m.ShowStyle
	}
	return nil
}

func (m *BindOpMobileForRegResponse) GetSmsNo() string {
	if m != nil && m.SmsNo != nil {
		return *m.SmsNo
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetSmsUpCode() string {
	if m != nil && m.SmsUpCode != nil {
		return *m.SmsUpCode
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetSmsUpMobile() string {
	if m != nil && m.SmsUpMobile != nil {
		return *m.SmsUpMobile
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetTicket() string {
	if m != nil && m.Ticket != nil {
		return *m.Ticket
	}
	return ""
}

func (m *BindOpMobileForRegResponse) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type SafeDeviceListV struct {
	Count                *uint64        `protobuf:"varint,1,opt,name=Count" json:"Count,omitempty"`
	SafeDeviceList       []*SafeDeviceV `protobuf:"bytes,2,rep,name=SafeDeviceList" json:"SafeDeviceList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SafeDeviceListV) Reset()         { *m = SafeDeviceListV{} }
func (m *SafeDeviceListV) String() string { return proto.CompactTextString(m) }
func (*SafeDeviceListV) ProtoMessage()    {}
func (*SafeDeviceListV) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *SafeDeviceListV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeDeviceListV.Unmarshal(m, b)
}
func (m *SafeDeviceListV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeDeviceListV.Marshal(b, m, deterministic)
}
func (m *SafeDeviceListV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeDeviceListV.Merge(m, src)
}
func (m *SafeDeviceListV) XXX_Size() int {
	return xxx_messageInfo_SafeDeviceListV.Size(m)
}
func (m *SafeDeviceListV) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeDeviceListV.DiscardUnknown(m)
}

var xxx_messageInfo_SafeDeviceListV proto.InternalMessageInfo

func (m *SafeDeviceListV) GetCount() uint64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *SafeDeviceListV) GetSafeDeviceList() []*SafeDeviceV {
	if m != nil {
		return m.SafeDeviceList
	}
	return nil
}

type SafeDeviceV struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Uuid                 *string  `protobuf:"bytes,2,opt,name=QrUuid" json:"QrUuid,omitempty"`
	DeviceType           *string  `protobuf:"bytes,3,opt,name=DeviceType" json:"DeviceType,omitempty"`
	CreateTime           *uint64  `protobuf:"varint,4,opt,name=CreateTime" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeDeviceV) Reset()         { *m = SafeDeviceV{} }
func (m *SafeDeviceV) String() string { return proto.CompactTextString(m) }
func (*SafeDeviceV) ProtoMessage()    {}
func (*SafeDeviceV) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *SafeDeviceV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeDeviceV.Unmarshal(m, b)
}
func (m *SafeDeviceV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeDeviceV.Marshal(b, m, deterministic)
}
func (m *SafeDeviceV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeDeviceV.Merge(m, src)
}
func (m *SafeDeviceV) XXX_Size() int {
	return xxx_messageInfo_SafeDeviceV.Size(m)
}
func (m *SafeDeviceV) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeDeviceV.DiscardUnknown(m)
}

var xxx_messageInfo_SafeDeviceV proto.InternalMessageInfo

func (m *SafeDeviceV) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SafeDeviceV) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *SafeDeviceV) GetDeviceType() string {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return ""
}

func (m *SafeDeviceV) GetCreateTime() uint64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*BindOpMobileForRegRequest)(nil), "wechat_proto.BindOpMobileForRegRequest")
	proto.RegisterType((*BindOpMobileForRegResponse)(nil), "wechat_proto.BindOpMobileForRegResponse")
	proto.RegisterType((*SafeDeviceListV)(nil), "wechat_proto.SafeDeviceListV")
	proto.RegisterType((*SafeDeviceV)(nil), "wechat_proto.SafeDeviceV")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 755 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdb, 0x4e, 0xeb, 0x38,
	0x14, 0x55, 0x2f, 0x5c, 0xea, 0xf4, 0x02, 0x86, 0x41, 0xa1, 0xc3, 0xa0, 0xaa, 0x1a, 0x8d, 0xfa,
	0x30, 0xea, 0x5c, 0x9e, 0x90, 0x46, 0x1a, 0xa9, 0x4d, 0xa9, 0xa6, 0x02, 0x0a, 0x72, 0x0a, 0xd2,
	0x9c, 0x17, 0x14, 0x92, 0x4d, 0x6b, 0x48, 0xe2, 0x12, 0x3b, 0xa7, 0xea, 0xaf, 0x9c, 0x0f, 0x3c,
	0xdf, 0x71, 0x64, 0x3b, 0x25, 0x97, 0xf6, 0xcd, 0x6b, 0xed, 0xe5, 0xcb, 0xde, 0xdb, 0x6b, 0x23,
	0xc3, 0x67, 0x73, 0x1a, 0xf6, 0x97, 0x11, 0x13, 0x0c, 0xd7, 0x57, 0xe0, 0x2e, 0x1c, 0xf1, 0xac,
	0x50, 0x3b, 0x41, 0x3a, 0xd6, 0xfd, 0x5e, 0x41, 0xe7, 0x43, 0x1a, 0x7a, 0xf7, 0xcb, 0x3b, 0xf6,
	0x42, 0x7d, 0x18, 0xb3, 0x88, 0xc0, 0x9c, 0xc0, 0x47, 0x0c, 0x5c, 0xe0, 0x7f, 0x90, 0xf1, 0xe2,
	0x70, 0x48, 0xa0, 0x59, 0xea, 0x94, 0x7a, 0xc6, 0xdf, 0xe7, 0xfd, 0xec, 0x79, 0xfd, 0x61, 0x2a,
	0x20, 0x59, 0x35, 0x3e, 0x43, 0xfb, 0xfa, 0x4c, 0xb3, 0xd2, 0x29, 0xf5, 0x6a, 0x24, 0x41, 0x92,
	0xbf, 0x5f, 0xba, 0xcc, 0x03, 0xb3, 0xda, 0x29, 0xf5, 0x2a, 0x24, 0x41, 0xf8, 0x12, 0xa1, 0x27,
	0x88, 0xe8, 0xeb, 0x5a, 0xc5, 0xf6, 0xd4, 0x9e, 0x0c, 0x83, 0x7f, 0x43, 0x4d, 0xdb, 0x79, 0x85,
	0x11, 0x7c, 0xa5, 0x2e, 0x4c, 0x9d, 0x00, 0x4c, 0xa4, 0x34, 0x05, 0x36, 0xaf, 0x9b, 0xad, 0x97,
	0x60, 0x1a, 0x45, 0x9d, 0x64, 0xf1, 0x18, 0x35, 0x89, 0x13, 0x7a, 0x2c, 0xb8, 0x0e, 0xdd, 0x68,
	0x7d, 0x03, 0x6b, 0xb3, 0xae, 0xf2, 0xbb, 0xcc, 0xe7, 0x67, 0xdf, 0x0c, 0x63, 0xea, 0x0b, 0x1a,
	0xda, 0x22, 0xa2, 0xe1, 0xfc, 0x99, 0x14, 0x76, 0xe1, 0x36, 0x3a, 0xbc, 0x75, 0xc2, 0x79, 0xec,
	0xcc, 0xc1, 0x6c, 0xa8, 0x9b, 0x3e, 0x31, 0xfe, 0x1d, 0x1d, 0x4f, 0xc2, 0x65, 0x2c, 0x74, 0xea,
	0x04, 0x66, 0xd1, 0xff, 0xdc, 0x6c, 0x76, 0x4a, 0xbd, 0x06, 0xd9, 0x0e, 0xe0, 0x0b, 0x54, 0x1b,
	0x78, 0x6f, 0x31, 0x17, 0x04, 0x84, 0xd9, 0x52, 0xaa, 0x94, 0xc0, 0x1d, 0x64, 0x58, 0x3e, 0x85,
	0x50, 0xd8, 0xf0, 0x31, 0x19, 0x99, 0x47, 0xea, 0xaa, 0x2c, 0x25, 0x5f, 0x32, 0xa2, 0x8e, 0x2f,
	0x6f, 0x37, 0xb1, 0x7e, 0xc9, 0x06, 0x77, 0xbf, 0x1d, 0xa0, 0xf6, 0xae, 0x46, 0xf3, 0x25, 0x0b,
	0x39, 0xe0, 0x7f, 0x51, 0x5d, 0xf7, 0x4e, 0xe3, 0xa4, 0xd5, 0xed, 0x5d, 0xad, 0xd6, 0x0a, 0x92,
	0xd3, 0xcb, 0xe6, 0x0d, 0x62, 0xb1, 0x98, 0x51, 0xf7, 0x1d, 0x44, 0xd2, 0x98, 0x0c, 0x83, 0x07,
	0xa8, 0x91, 0x94, 0x71, 0xf2, 0x70, 0x4b, 0xb9, 0x30, 0x0f, 0xd5, 0x05, 0x3f, 0x17, 0x2e, 0xc8,
	0x4a, 0x48, 0x7e, 0x07, 0x6e, 0xa2, 0xb2, 0xe5, 0xaa, 0x1e, 0xd5, 0x48, 0xd9, 0x72, 0x65, 0x9f,
	0xc7, 0x2c, 0x0a, 0x1c, 0x01, 0x5e, 0xf2, 0xcf, 0x74, 0x49, 0x0a, 0x2c, 0xfe, 0x13, 0x9d, 0xdc,
	0x05, 0xc2, 0xe7, 0x16, 0x0b, 0x45, 0xc4, 0xfc, 0x21, 0x15, 0x63, 0xdf, 0xd1, 0x05, 0xaa, 0x92,
	0x5d, 0x21, 0xdc, 0x43, 0x2d, 0xbd, 0xd7, 0x5a, 0x80, 0xfb, 0xae, 0xbe, 0xd0, 0x4f, 0x4a, 0x5d,
	0xa4, 0x65, 0xda, 0x53, 0x00, 0xcf, 0x06, 0xf1, 0xb0, 0xf2, 0xd4, 0x7f, 0xae, 0x92, 0x0c, 0x83,
	0x47, 0xa8, 0x39, 0x05, 0xb1, 0x62, 0xd1, 0x7b, 0x72, 0x85, 0x59, 0x53, 0x79, 0x5f, 0xe4, 0xf3,
	0xce, 0x6b, 0x48, 0x61, 0x0f, 0xbe, 0x42, 0xc6, 0x14, 0x56, 0xff, 0x31, 0x2e, 0x54, 0xe9, 0x0e,
	0xd4, 0x11, 0x67, 0xf9, 0x23, 0x36, 0x51, 0x92, 0x95, 0xe2, 0x5f, 0x51, 0xe3, 0xfe, 0x85, 0x33,
	0x1f, 0x04, 0x4c, 0x04, 0x04, 0x7f, 0xa9, 0x0f, 0x5a, 0x25, 0x79, 0x52, 0x66, 0xf1, 0x10, 0x47,
	0x90, 0x54, 0xb1, 0xa5, 0x9b, 0x97, 0x32, 0xf8, 0x08, 0x55, 0x64, 0x7a, 0xda, 0x92, 0x72, 0x89,
	0xbb, 0xa8, 0x1e, 0xc1, 0xdc, 0x06, 0xce, 0x29, 0x0b, 0x27, 0x9e, 0x79, 0xa6, 0x42, 0x39, 0x4e,
	0x9e, 0x9a, 0x3a, 0x4e, 0x79, 0xb0, 0x4a, 0x32, 0x0c, 0xbe, 0xce, 0xfa, 0x54, 0x25, 0xd6, 0x54,
	0x89, 0xfd, 0x52, 0xf0, 0x5f, 0x4e, 0xf3, 0x44, 0x0a, 0x9b, 0xf0, 0x15, 0xaa, 0xd9, 0x0b, 0xb6,
	0xb2, 0xc5, 0xda, 0x07, 0xf3, 0x78, 0xd7, 0xb7, 0xfd, 0x0c, 0xdf, 0xc0, 0x9a, 0xa4, 0x62, 0x7c,
	0x8a, 0xf6, 0xec, 0x80, 0x4f, 0x59, 0x32, 0x9f, 0x34, 0x90, 0x26, 0xb4, 0x03, 0xfe, 0xb8, 0xb4,
	0xe4, 0x14, 0x3a, 0x51, 0x91, 0x94, 0x90, 0x26, 0x54, 0x20, 0xa9, 0xd5, 0xa9, 0x36, 0x61, 0x86,
	0x92, 0xe3, 0x4d, 0x68, 0x17, 0x94, 0xf5, 0xd8, 0xd3, 0x48, 0x9a, 0xf3, 0x91, 0x43, 0x14, 0xca,
	0xc1, 0xb5, 0xaf, 0xcd, 0xb9, 0xc1, 0xdd, 0x37, 0xd4, 0x2a, 0xa4, 0x29, 0x1f, 0x67, 0xb1, 0x38,
	0xd4, 0x43, 0xb7, 0x4a, 0x34, 0xc0, 0x83, 0xad, 0x9a, 0x95, 0x3b, 0x95, 0xed, 0x99, 0x9c, 0x6a,
	0xb6, 0xea, 0xd5, 0x8d, 0x91, 0x91, 0x09, 0x63, 0x8c, 0xaa, 0x6a, 0x96, 0x96, 0xd4, 0x93, 0xd4,
	0x5a, 0x72, 0x8f, 0x31, 0xf5, 0x92, 0x04, 0xd4, 0x5a, 0x76, 0x33, 0x33, 0x51, 0x75, 0xc5, 0x32,
	0x8c, 0x8c, 0x5b, 0x11, 0x38, 0x02, 0x66, 0x34, 0x80, 0x8d, 0x13, 0x52, 0x66, 0x68, 0x7c, 0xa9,
	0xf5, 0xfb, 0x7f, 0xe8, 0x57, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xd0, 0x60, 0xa7, 0x9f,
	0x06, 0x00, 0x00,
}
