// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rests.proto

package wechat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LbsRequest struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,req,name=BaseRequest" json:"BaseRequest,omitempty"`
	OpCode               *uint64      `protobuf:"varint,2,opt,name=opcode" json:"code,omitempty"`
	Longitude            *float32     `protobuf:"fixed32,3,opt,name=longitude" json:"longitude,omitempty"`
	Latitude             *float32     `protobuf:"fixed32,4,opt,name=latitude" json:"latitude,omitempty"`
	Precision            *int64       `protobuf:"varint,5,opt,name=precision" json:"precision,omitempty"`
	MacAddr              *string      `protobuf:"bytes,6,opt,name=macAddr" json:"macAddr,omitempty"`
	CellId               *string      `protobuf:"bytes,7,opt,name=cellId" json:"cellId,omitempty"`
	GPSSource            *int64       `protobuf:"varint,8,opt,name=gPSSource" json:"gPSSource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LbsRequest) Reset()         { *m = LbsRequest{} }
func (m *LbsRequest) String() string { return proto.CompactTextString(m) }
func (*LbsRequest) ProtoMessage()    {}
func (*LbsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{0}
}

func (m *LbsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LbsRequest.Unmarshal(m, b)
}
func (m *LbsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LbsRequest.Marshal(b, m, deterministic)
}
func (m *LbsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbsRequest.Merge(m, src)
}
func (m *LbsRequest) XXX_Size() int {
	return xxx_messageInfo_LbsRequest.Size(m)
}
func (m *LbsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LbsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LbsRequest proto.InternalMessageInfo

func (m *LbsRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *LbsRequest) GetOpCode() uint64 {
	if m != nil && m.OpCode != nil {
		return *m.OpCode
	}
	return 0
}
func (m *LbsRequest) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *LbsRequest) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}
func (m *LbsRequest) GetPrecision() int64 {
	if m != nil && m.Precision != nil {
		return *m.Precision
	}
	return 0
}

func (m *LbsRequest) GetMacAddr() string {
	if m != nil && m.MacAddr != nil {
		return *m.MacAddr
	}
	return ""
}

func (m *LbsRequest) GetCellId() string {
	if m != nil && m.CellId != nil {
		return *m.CellId
	}
	return ""
}

func (m *LbsRequest) GetGPSSource() int64 {
	if m != nil && m.GPSSource != nil {
		return *m.GPSSource
	}
	return 0
}

type LbsResponse struct {
	BaseResponse         *BaseResponse     `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	ContactCount         *uint64           `protobuf:"varint,2,opt,name=contactCount" json:"contactCount,omitempty"`
	ContactList          []*LbsContactInfo `protobuf:"bytes,3,rep,name=contactList" json:"contactList,omitempty"`
	FlushTime            *uint64           `protobuf:"varint,5,opt,name=flushTime" json:"flushTime,omitempty"`
	IsShowRoom           *uint64           `protobuf:"varint,6,opt,name=isShowRoom" json:"isShowRoom,omitempty"`
	RoomMemberCount      *uint64           `protobuf:"varint,7,opt,name=roomMemberCount" json:"roomMemberCount,omitempty"`
	State                *uint64           `protobuf:"varint,4,opt,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LbsResponse) Reset()         { *m = LbsResponse{} }
func (m *LbsResponse) String() string { return proto.CompactTextString(m) }
func (*LbsResponse) ProtoMessage()    {}
func (*LbsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{1}
}

func (m *LbsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LbsResponse.Unmarshal(m, b)
}
func (m *LbsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LbsResponse.Marshal(b, m, deterministic)
}
func (m *LbsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbsResponse.Merge(m, src)
}
func (m *LbsResponse) XXX_Size() int {
	return xxx_messageInfo_LbsResponse.Size(m)
}
func (m *LbsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LbsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LbsResponse proto.InternalMessageInfo

func (m *LbsResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *LbsResponse) GetContactCount() uint64 {
	if m != nil && m.ContactCount != nil {
		return *m.ContactCount
	}
	return 0
}

func (m *LbsResponse) GetContactList() []*LbsContactInfo {
	if m != nil {
		return m.ContactList
	}
	return nil
}

func (m *LbsResponse) GetFlushTime() uint64 {
	if m != nil && m.FlushTime != nil {
		return *m.FlushTime
	}
	return 0
}

func (m *LbsResponse) GetIsShowRoom() uint64 {
	if m != nil && m.IsShowRoom != nil {
		return *m.IsShowRoom
	}
	return 0
}

func (m *LbsResponse) GetRoomMemberCount() uint64 {
	if m != nil && m.RoomMemberCount != nil {
		return *m.RoomMemberCount
	}
	return 0
}

func (m *LbsResponse) GetState() uint64 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type LbsContactInfo struct {
	Alias                *string          `protobuf:"bytes,12,opt,name=alias" json:"alias,omitempty"`
	NtispamTicket        *string          `protobuf:"bytes,26,opt,name=ntispamTicket" json:"ntispamTicket,omitempty"`
	BigHeadImgUrl        *string          `protobuf:"bytes,22,opt,name=bigHeadImgUrl" json:"bigHeadImgUrl,omitempty"`
	City                 *string          `protobuf:"bytes,4,opt,name=city" json:"city,omitempty"`
	CustomizedInfo       *CustomizedInfos `protobuf:"bytes,25,opt,name=customizedInfo" json:"customizedInfo,omitempty"`
	Distance             *string          `protobuf:"bytes,6,opt,name=distance" json:"distance,omitempty"`
	HeadImgVersion       *int64           `protobuf:"varint,19,opt,name=headImgVersion" json:"headImgVersion,omitempty"`
	ImgStatus            *uint64          `protobuf:"varint,8,opt,name=imgStatus" json:"imgStatus,omitempty"`
	MyBrandList          *string          `protobuf:"bytes,24,opt,name=myBrandList" json:"myBrandList,omitempty"`
	NickName             *string          `protobuf:"bytes,2,opt,name=nickName" json:"nickName,omitempty"`
	Province             *string          `protobuf:"bytes,3,opt,name=province" json:"province,omitempty"`
	Sex                  *int64           `protobuf:"varint,7,opt,name=sex" json:"sex,omitempty"`
	Signature            *string          `protobuf:"bytes,5,opt,name=signature" json:"signature,omitempty"`
	SmallHeadImgUrl      *string          `protobuf:"bytes,23,opt,name=smallHeadImgUrl" json:"smallHeadImgUrl,omitempty"`
	SnsUserInfo          *SnsUserInfo     `protobuf:"bytes,20,opt,name=SnsUserInfo" json:"SnsUserInfo,omitempty"`
	UserName             *string          `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	VerifyContent        *string          `protobuf:"bytes,11,opt,name=verifyContent" json:"verifyContent,omitempty"`
	VerifyInfo           *string          `protobuf:"bytes,10,opt,name=verifyInfo" json:"verifyInfo,omitempty"`
	Weibo                *string          `protobuf:"bytes,13,opt,name=weibo" json:"weibo,omitempty"`
	WeiboFlag            *uint64          `protobuf:"varint,15,opt,name=weiboFlag" json:"weiboFlag,omitempty"`
	WeiboNickname        *string          `protobuf:"bytes,14,opt,name=weiboNickname" json:"weiboNickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LbsContactInfo) Reset()         { *m = LbsContactInfo{} }
func (m *LbsContactInfo) String() string { return proto.CompactTextString(m) }
func (*LbsContactInfo) ProtoMessage()    {}
func (*LbsContactInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{2}
}

func (m *LbsContactInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LbsContactInfo.Unmarshal(m, b)
}
func (m *LbsContactInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LbsContactInfo.Marshal(b, m, deterministic)
}
func (m *LbsContactInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LbsContactInfo.Merge(m, src)
}
func (m *LbsContactInfo) XXX_Size() int {
	return xxx_messageInfo_LbsContactInfo.Size(m)
}
func (m *LbsContactInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LbsContactInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LbsContactInfo proto.InternalMessageInfo

func (m *LbsContactInfo) GetAlias() string {
	if m != nil && m.Alias != nil {
		return *m.Alias
	}
	return ""
}

func (m *LbsContactInfo) GetNtispamTicket() string {
	if m != nil && m.NtispamTicket != nil {
		return *m.NtispamTicket
	}
	return ""
}

func (m *LbsContactInfo) GetBigHeadImgUrl() string {
	if m != nil && m.BigHeadImgUrl != nil {
		return *m.BigHeadImgUrl
	}
	return ""
}

func (m *LbsContactInfo) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *LbsContactInfo) GetCustomizedInfo() *CustomizedInfos {
	if m != nil {
		return m.CustomizedInfo
	}
	return nil
}

func (m *LbsContactInfo) GetDistance() string {
	if m != nil && m.Distance != nil {
		return *m.Distance
	}
	return ""
}

func (m *LbsContactInfo) GetHeadImgVersion() int64 {
	if m != nil && m.HeadImgVersion != nil {
		return *m.HeadImgVersion
	}
	return 0
}

func (m *LbsContactInfo) GetImgStatus() uint64 {
	if m != nil && m.ImgStatus != nil {
		return *m.ImgStatus
	}
	return 0
}

func (m *LbsContactInfo) GetMyBrandList() string {
	if m != nil && m.MyBrandList != nil {
		return *m.MyBrandList
	}
	return ""
}

func (m *LbsContactInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *LbsContactInfo) GetProvince() string {
	if m != nil && m.Province != nil {
		return *m.Province
	}
	return ""
}

func (m *LbsContactInfo) GetSex() int64 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *LbsContactInfo) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *LbsContactInfo) GetSmallHeadImgUrl() string {
	if m != nil && m.SmallHeadImgUrl != nil {
		return *m.SmallHeadImgUrl
	}
	return ""
}

func (m *LbsContactInfo) GetSnsUserInfo() *SnsUserInfo {
	if m != nil {
		return m.SnsUserInfo
	}
	return nil
}

func (m *LbsContactInfo) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *LbsContactInfo) GetVerifyContent() string {
	if m != nil && m.VerifyContent != nil {
		return *m.VerifyContent
	}
	return ""
}

func (m *LbsContactInfo) GetVerifyInfo() string {
	if m != nil && m.VerifyInfo != nil {
		return *m.VerifyInfo
	}
	return ""
}

func (m *LbsContactInfo) GetWeibo() string {
	if m != nil && m.Weibo != nil {
		return *m.Weibo
	}
	return ""
}

func (m *LbsContactInfo) GetWeiboFlag() uint64 {
	if m != nil && m.WeiboFlag != nil {
		return *m.WeiboFlag
	}
	return 0
}

func (m *LbsContactInfo) GetWeiboNickname() string {
	if m != nil && m.WeiboNickname != nil {
		return *m.WeiboNickname
	}
	return ""
}

type CustomizedInfos struct {
	BrandFlag            *uint64  `protobuf:"varint,1,opt,name=brandFlag" json:"brandFlag,omitempty"`
	ExternalInfo         *string  `protobuf:"bytes,2,opt,name=externalInfo" json:"externalInfo,omitempty"`
	BrandInfo            *string  `protobuf:"bytes,3,opt,name=brandInfo" json:"brandInfo,omitempty"`
	BrandIconURL         *string  `protobuf:"bytes,4,opt,name=brandIconURL" json:"brandIconURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomizedInfos) Reset()         { *m = CustomizedInfos{} }
func (m *CustomizedInfos) String() string { return proto.CompactTextString(m) }
func (*CustomizedInfos) ProtoMessage()    {}
func (*CustomizedInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{3}
}

func (m *CustomizedInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomizedInfos.Unmarshal(m, b)
}
func (m *CustomizedInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomizedInfos.Marshal(b, m, deterministic)
}
func (m *CustomizedInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomizedInfos.Merge(m, src)
}
func (m *CustomizedInfos) XXX_Size() int {
	return xxx_messageInfo_CustomizedInfos.Size(m)
}
func (m *CustomizedInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomizedInfos.DiscardUnknown(m)
}

var xxx_messageInfo_CustomizedInfos proto.InternalMessageInfo

func (m *CustomizedInfos) GetBrandFlag() uint64 {
	if m != nil && m.BrandFlag != nil {
		return *m.BrandFlag
	}
	return 0
}

func (m *CustomizedInfos) GetExternalInfo() string {
	if m != nil && m.ExternalInfo != nil {
		return *m.ExternalInfo
	}
	return ""
}

func (m *CustomizedInfos) GetBrandInfo() string {
	if m != nil && m.BrandInfo != nil {
		return *m.BrandInfo
	}
	return ""
}

func (m *CustomizedInfos) GetBrandIconURL() string {
	if m != nil && m.BrandIconURL != nil {
		return *m.BrandIconURL
	}
	return ""
}

type GetUserRankLikeCountRequest struct {
	BaseRequest          *BaseRequest `protobuf:"bytes,1,req,name=BaseRequest" json:"BaseRequest,omitempty"`
	LatestRank           *bool        `protobuf:"varint,2,opt,name=latestRank" json:"latestRank,omitempty"`
	RankId               *string      `protobuf:"bytes,3,opt,name=rankId" json:"rankId,omitempty"`
	AppUsername          *string      `protobuf:"bytes,4,opt,name=appUsername" json:"appUsername,omitempty"`
	Username             *string      `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserRankLikeCountRequest) Reset()         { *m = GetUserRankLikeCountRequest{} }
func (m *GetUserRankLikeCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRankLikeCountRequest) ProtoMessage()    {}
func (*GetUserRankLikeCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{4}
}

func (m *GetUserRankLikeCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRankLikeCountRequest.Unmarshal(m, b)
}
func (m *GetUserRankLikeCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRankLikeCountRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRankLikeCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRankLikeCountRequest.Merge(m, src)
}
func (m *GetUserRankLikeCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRankLikeCountRequest.Size(m)
}
func (m *GetUserRankLikeCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRankLikeCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRankLikeCountRequest proto.InternalMessageInfo

func (m *GetUserRankLikeCountRequest) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *GetUserRankLikeCountRequest) GetLatestRank() bool {
	if m != nil && m.LatestRank != nil {
		return *m.LatestRank
	}
	return false
}

func (m *GetUserRankLikeCountRequest) GetRankId() string {
	if m != nil && m.RankId != nil {
		return *m.RankId
	}
	return ""
}

func (m *GetUserRankLikeCountRequest) GetAppUsername() string {
	if m != nil && m.AppUsername != nil {
		return *m.AppUsername
	}
	return ""
}

func (m *GetUserRankLikeCountRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type GetUserRankLikeCountResponse struct {
	BaseResponse         *BaseResponse   `protobuf:"bytes,1,opt,name=baseResponse" json:"baseResponse,omitempty"`
	AffectedUserList     []*AffectedUser `protobuf:"bytes,2,rep,name=affectedUserList" json:"affectedUserList,omitempty"`
	FriendLikeList       []*FriendLike   `protobuf:"bytes,3,rep,name=friendLikeList" json:"friendLikeList,omitempty"`
	Follows              []string        `protobuf:"bytes,4,rep,name=follows" json:"follows,omitempty"`
	ChampionCoverUrl     *string         `protobuf:"bytes,5,opt,name=championCoverUrl" json:"championCoverUrl,omitempty"`
	ChampionMotto        *string         `protobuf:"bytes,6,opt,name=championMotto" json:"championMotto,omitempty"`
	RankId               *string         `protobuf:"bytes,7,opt,name=rankId" json:"rankId,omitempty"`
	ShareTitle           *string         `protobuf:"bytes,8,opt,name=shareTitle" json:"shareTitle,omitempty"`
	Fic                  *string         `protobuf:"bytes,9,opt,name=fic" json:"fic,omitempty"`
	HasCoverUrl          *bool           `protobuf:"varint,10,opt,name=hasCoverUrl" json:"hasCoverUrl,omitempty"`
	FId                  *string         `protobuf:"bytes,11,opt,name=fId" json:"fId,omitempty"`
	LikeUserList         []*LikeUser     `protobuf:"bytes,12,rep,name=likeUserList" json:"likeUserList,omitempty"`
	FIf                  *bool           `protobuf:"varint,13,opt,name=fIf" json:"fIf,omitempty"`
	FIn                  *string         `protobuf:"bytes,14,opt,name=fIn" json:"fIn,omitempty"`
	FIo                  *bool           `protobuf:"varint,15,opt,name=fIo" json:"fIo,omitempty"`
	FIp                  *int64          `protobuf:"varint,16,opt,name=fIp" json:"fIp,omitempty"`
	FIq                  *string         `protobuf:"bytes,17,opt,name=fIq" json:"fIq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserRankLikeCountResponse) Reset()         { *m = GetUserRankLikeCountResponse{} }
func (m *GetUserRankLikeCountResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserRankLikeCountResponse) ProtoMessage()    {}
func (*GetUserRankLikeCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{5}
}

func (m *GetUserRankLikeCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRankLikeCountResponse.Unmarshal(m, b)
}
func (m *GetUserRankLikeCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRankLikeCountResponse.Marshal(b, m, deterministic)
}
func (m *GetUserRankLikeCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRankLikeCountResponse.Merge(m, src)
}
func (m *GetUserRankLikeCountResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserRankLikeCountResponse.Size(m)
}
func (m *GetUserRankLikeCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRankLikeCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRankLikeCountResponse proto.InternalMessageInfo

func (m *GetUserRankLikeCountResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *GetUserRankLikeCountResponse) GetAffectedUserList() []*AffectedUser {
	if m != nil {
		return m.AffectedUserList
	}
	return nil
}

func (m *GetUserRankLikeCountResponse) GetFriendLikeList() []*FriendLike {
	if m != nil {
		return m.FriendLikeList
	}
	return nil
}

func (m *GetUserRankLikeCountResponse) GetFollows() []string {
	if m != nil {
		return m.Follows
	}
	return nil
}

func (m *GetUserRankLikeCountResponse) GetChampionCoverUrl() string {
	if m != nil && m.ChampionCoverUrl != nil {
		return *m.ChampionCoverUrl
	}
	return ""
}

func (m *GetUserRankLikeCountResponse) GetChampionMotto() string {
	if m != nil && m.ChampionMotto != nil {
		return *m.ChampionMotto
	}
	return ""
}

func (m *GetUserRankLikeCountResponse) GetRankId() string {
	if m != nil && m.RankId != nil {
		return *m.RankId
	}
	return ""
}

func (m *GetUserRankLikeCountResponse) GetShareTitle() string {
	if m != nil && m.ShareTitle != nil {
		return *m.ShareTitle
	}
	return ""
}

func (m *GetUserRankLikeCountResponse) GetFic() string {
	if m != nil && m.Fic != nil {
		return *m.Fic
	}
	return ""
}

func (m *GetUserRankLikeCountResponse) GetHasCoverUrl() bool {
	if m != nil && m.HasCoverUrl != nil {
		return *m.HasCoverUrl
	}
	return false
}

func (m *GetUserRankLikeCountResponse) GetFId() string {
	if m != nil && m.FId != nil {
		return *m.FId
	}
	return ""
}

func (m *GetUserRankLikeCountResponse) GetLikeUserList() []*LikeUser {
	if m != nil {
		return m.LikeUserList
	}
	return nil
}

func (m *GetUserRankLikeCountResponse) GetFIf() bool {
	if m != nil && m.FIf != nil {
		return *m.FIf
	}
	return false
}

func (m *GetUserRankLikeCountResponse) GetFIn() string {
	if m != nil && m.FIn != nil {
		return *m.FIn
	}
	return ""
}

func (m *GetUserRankLikeCountResponse) GetFIo() bool {
	if m != nil && m.FIo != nil {
		return *m.FIo
	}
	return false
}

func (m *GetUserRankLikeCountResponse) GetFIp() int64 {
	if m != nil && m.FIp != nil {
		return *m.FIp
	}
	return 0
}

func (m *GetUserRankLikeCountResponse) GetFIq() string {
	if m != nil && m.FIq != nil {
		return *m.FIq
	}
	return ""
}

type LikeUser struct {
	Index                *int64   `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Username             *string  `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Khq                  *int64   `protobuf:"varint,3,opt,name=khq" json:"khq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeUser) Reset()         { *m = LikeUser{} }
func (m *LikeUser) String() string { return proto.CompactTextString(m) }
func (*LikeUser) ProtoMessage()    {}
func (*LikeUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{6}
}

func (m *LikeUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeUser.Unmarshal(m, b)
}
func (m *LikeUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeUser.Marshal(b, m, deterministic)
}
func (m *LikeUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeUser.Merge(m, src)
}
func (m *LikeUser) XXX_Size() int {
	return xxx_messageInfo_LikeUser.Size(m)
}
func (m *LikeUser) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeUser.DiscardUnknown(m)
}

var xxx_messageInfo_LikeUser proto.InternalMessageInfo

func (m *LikeUser) GetIndex() int64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *LikeUser) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LikeUser) GetKhq() int64 {
	if m != nil && m.Khq != nil {
		return *m.Khq
	}
	return 0
}

type FriendLike struct {
	OKf                  *int64   `protobuf:"varint,1,opt,name=oKf" json:"oKf,omitempty"`
	Username             *string  `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendLike) Reset()         { *m = FriendLike{} }
func (m *FriendLike) String() string { return proto.CompactTextString(m) }
func (*FriendLike) ProtoMessage()    {}
func (*FriendLike) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{7}
}

func (m *FriendLike) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendLike.Unmarshal(m, b)
}
func (m *FriendLike) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendLike.Marshal(b, m, deterministic)
}
func (m *FriendLike) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendLike.Merge(m, src)
}
func (m *FriendLike) XXX_Size() int {
	return xxx_messageInfo_FriendLike.Size(m)
}
func (m *FriendLike) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendLike.DiscardUnknown(m)
}

var xxx_messageInfo_FriendLike proto.InternalMessageInfo

func (m *FriendLike) GetOKf() int64 {
	if m != nil && m.OKf != nil {
		return *m.OKf
	}
	return 0
}

func (m *FriendLike) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

type AffectedUser struct {
	Gwi                  *int64   `protobuf:"varint,3,opt,name=gwi" json:"gwi,omitempty"`
	Gwj                  *int64   `protobuf:"varint,4,opt,name=gwj" json:"gwj,omitempty"`
	Gwk                  *int64   `protobuf:"varint,5,opt,name=gwk" json:"gwk,omitempty"`
	Score                *int64   `protobuf:"varint,2,opt,name=score" json:"score,omitempty"`
	UserName             *string  `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AffectedUser) Reset()         { *m = AffectedUser{} }
func (m *AffectedUser) String() string { return proto.CompactTextString(m) }
func (*AffectedUser) ProtoMessage()    {}
func (*AffectedUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2e845c122469318, []int{8}
}

func (m *AffectedUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AffectedUser.Unmarshal(m, b)
}
func (m *AffectedUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AffectedUser.Marshal(b, m, deterministic)
}
func (m *AffectedUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AffectedUser.Merge(m, src)
}
func (m *AffectedUser) XXX_Size() int {
	return xxx_messageInfo_AffectedUser.Size(m)
}
func (m *AffectedUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AffectedUser.DiscardUnknown(m)
}

var xxx_messageInfo_AffectedUser proto.InternalMessageInfo

func (m *AffectedUser) GetGwi() int64 {
	if m != nil && m.Gwi != nil {
		return *m.Gwi
	}
	return 0
}

func (m *AffectedUser) GetGwj() int64 {
	if m != nil && m.Gwj != nil {
		return *m.Gwj
	}
	return 0
}

func (m *AffectedUser) GetGwk() int64 {
	if m != nil && m.Gwk != nil {
		return *m.Gwk
	}
	return 0
}

func (m *AffectedUser) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *AffectedUser) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*LbsRequest)(nil), "wechat_proto.LbsRequest")
	proto.RegisterType((*LbsResponse)(nil), "wechat_proto.LbsResponse")
	proto.RegisterType((*LbsContactInfo)(nil), "wechat_proto.LbsContactInfo")
	proto.RegisterType((*CustomizedInfos)(nil), "wechat_proto.CustomizedInfos")
	proto.RegisterType((*GetUserRankLikeCountRequest)(nil), "wechat_proto.GetUserRankLikeCountRequest")
	proto.RegisterType((*GetUserRankLikeCountResponse)(nil), "wechat_proto.GetUserRankLikeCountResponse")
	proto.RegisterType((*LikeUser)(nil), "wechat_proto.LikeUser")
	proto.RegisterType((*FriendLike)(nil), "wechat_proto.FriendLike")
	proto.RegisterType((*AffectedUser)(nil), "wechat_proto.AffectedUser")
}

func init() { proto.RegisterFile("rests.proto", fileDescriptor_e2e845c122469318) }

var fileDescriptor_e2e845c122469318 = []byte{
	// 1076 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x51, 0x6e, 0x1b, 0x37,
	0x13, 0x86, 0xb4, 0x72, 0x6c, 0x51, 0x8a, 0xed, 0x9f, 0x7f, 0xe0, 0x32, 0xae, 0x6b, 0x08, 0x42,
	0x51, 0x08, 0x7d, 0x70, 0x01, 0x3f, 0xa6, 0x40, 0xd0, 0xd8, 0xa8, 0x5b, 0xa1, 0x8e, 0x51, 0x50,
	0x76, 0x1f, 0xfa, 0x52, 0x50, 0xbb, 0x5c, 0x89, 0xd9, 0x5d, 0x72, 0x4d, 0x52, 0x96, 0xdd, 0x1b,
	0xf4, 0x00, 0x3d, 0x47, 0xaf, 0xd2, 0x03, 0xf4, 0x00, 0x3d, 0x46, 0x31, 0xc3, 0x95, 0xb4, 0xab,
	0x04, 0x79, 0xca, 0x1b, 0xbf, 0x8f, 0xc3, 0xe1, 0x70, 0xe6, 0x9b, 0xd9, 0x25, 0x3d, 0x2b, 0x9d,
	0x77, 0x67, 0xa5, 0x35, 0xde, 0xd0, 0xfe, 0x52, 0xc6, 0x73, 0xe1, 0x7f, 0x43, 0x74, 0x5c, 0xa1,
	0xb0, 0x37, 0xfc, 0xa3, 0x4d, 0xc8, 0xf5, 0xd4, 0x71, 0x79, 0xbf, 0x90, 0xce, 0xd3, 0x6f, 0x49,
	0xef, 0x42, 0x38, 0x59, 0x41, 0xd6, 0x1a, 0xb4, 0x47, 0xbd, 0xf3, 0x97, 0x67, 0x75, 0x07, 0x67,
	0x35, 0x03, 0x5e, 0xb7, 0xa6, 0x47, 0xe4, 0x99, 0x29, 0x2f, 0x4d, 0x22, 0x59, 0x7b, 0xd0, 0x1a,
	0x75, 0x79, 0x85, 0xe8, 0x09, 0xe9, 0xe6, 0x46, 0xcf, 0x94, 0x5f, 0x24, 0x92, 0x45, 0x83, 0xd6,
	0xa8, 0xcd, 0x37, 0x04, 0x3d, 0x26, 0x7b, 0xb9, 0xf0, 0x61, 0xb3, 0x83, 0x9b, 0x6b, 0x0c, 0x27,
	0x4b, 0x2b, 0x63, 0xe5, 0x94, 0xd1, 0x6c, 0x67, 0xd0, 0x1a, 0x45, 0x7c, 0x43, 0x50, 0x46, 0x76,
	0x0b, 0x11, 0xbf, 0x49, 0x12, 0xcb, 0x9e, 0xe1, 0x85, 0x2b, 0x08, 0x91, 0xc4, 0x32, 0xcf, 0xc7,
	0x09, 0xdb, 0x0d, 0x91, 0x04, 0x04, 0xfe, 0x66, 0x3f, 0x4f, 0x26, 0x66, 0x61, 0x63, 0xc9, 0xf6,
	0x82, 0xbf, 0x35, 0x31, 0xfc, 0xab, 0x4d, 0x7a, 0x98, 0x0b, 0x57, 0x1a, 0xed, 0x24, 0x7d, 0x4d,
	0xfa, 0x53, 0x7c, 0x5e, 0xc0, 0xac, 0x35, 0x68, 0x8d, 0x7a, 0xe7, 0xc7, 0x1f, 0xca, 0x46, 0xb0,
	0xe0, 0x0d, 0x7b, 0x3a, 0x24, 0xfd, 0xd8, 0x68, 0x2f, 0x62, 0x7f, 0x69, 0x16, 0xda, 0x63, 0x56,
	0x3a, 0xbc, 0xc1, 0xd1, 0xd7, 0xa4, 0x57, 0xe1, 0x6b, 0xe5, 0x3c, 0x8b, 0x06, 0xd1, 0xa8, 0x77,
	0x7e, 0xd2, 0xbc, 0xe2, 0x7a, 0xea, 0x2e, 0x83, 0xcd, 0x58, 0xa7, 0x86, 0xd7, 0x0f, 0xc0, 0x8b,
	0xd2, 0x7c, 0xe1, 0xe6, 0xb7, 0xaa, 0x90, 0x98, 0xa1, 0x0e, 0xdf, 0x10, 0xf4, 0x94, 0x10, 0xe5,
	0x26, 0x73, 0xb3, 0xe4, 0xc6, 0x14, 0x98, 0xa4, 0x0e, 0xaf, 0x31, 0x74, 0x44, 0x0e, 0xac, 0x31,
	0xc5, 0x5b, 0x59, 0x4c, 0xa5, 0x0d, 0x41, 0xee, 0xa2, 0xd1, 0x36, 0x4d, 0x5f, 0x90, 0x1d, 0xe7,
	0x85, 0x0f, 0x25, 0xea, 0xf0, 0x00, 0x86, 0xff, 0xec, 0x90, 0xfd, 0x66, 0x74, 0x60, 0x28, 0x72,
	0x25, 0x1c, 0xeb, 0x63, 0xe6, 0x03, 0xa0, 0x5f, 0x92, 0xe7, 0xda, 0x2b, 0x57, 0x8a, 0xe2, 0x56,
	0xc5, 0x99, 0xf4, 0xec, 0x18, 0x77, 0x9b, 0x24, 0x58, 0x4d, 0xd5, 0xec, 0x47, 0x29, 0x92, 0x71,
	0x31, 0xbb, 0xb3, 0x39, 0x3b, 0x0a, 0x56, 0x0d, 0x92, 0x52, 0xd2, 0x89, 0x95, 0x7f, 0xc2, 0x48,
	0xba, 0x1c, 0xd7, 0xf4, 0x7b, 0xb2, 0x1f, 0x2f, 0x9c, 0x37, 0x85, 0xfa, 0x5d, 0x26, 0x10, 0x07,
	0x7b, 0x89, 0xc5, 0xfa, 0xa2, 0x99, 0xc9, 0xcb, 0x86, 0x8d, 0xe3, 0x5b, 0x87, 0x40, 0x8b, 0x89,
	0x72, 0x5e, 0xe8, 0x58, 0x56, 0x92, 0x5a, 0x63, 0xfa, 0x15, 0xd9, 0x9f, 0x87, 0x20, 0x7e, 0x91,
	0x16, 0x05, 0xf9, 0x7f, 0x14, 0xd0, 0x16, 0x0b, 0x15, 0x51, 0xc5, 0x6c, 0xe2, 0x85, 0x5f, 0x38,
	0xd4, 0x58, 0x87, 0x6f, 0x08, 0x3a, 0x20, 0xbd, 0xe2, 0xe9, 0xc2, 0x0a, 0x9d, 0x60, 0xbd, 0x19,
	0x5e, 0x52, 0xa7, 0x20, 0x06, 0xad, 0xe2, 0xec, 0x46, 0x14, 0xab, 0x3e, 0x5a, 0x63, 0xd8, 0x2b,
	0xad, 0x79, 0x50, 0x10, 0x5f, 0x14, 0xf6, 0x56, 0x98, 0x1e, 0x92, 0xc8, 0xc9, 0x47, 0xac, 0x5f,
	0xc4, 0x61, 0x09, 0x91, 0x38, 0x35, 0xd3, 0xc2, 0x2f, 0x6c, 0xd0, 0x46, 0x97, 0x6f, 0x08, 0xa8,
	0xbd, 0x2b, 0x44, 0x9e, 0xd7, 0xd2, 0xfd, 0x19, 0xda, 0x6c, 0xd3, 0x30, 0x14, 0x26, 0xda, 0xdd,
	0x39, 0x69, 0x31, 0xb3, 0x2f, 0x30, 0xb3, 0x5b, 0x43, 0xa1, 0x66, 0xc0, 0xeb, 0xd6, 0x10, 0xf2,
	0xc2, 0x49, 0x8b, 0xcf, 0x69, 0x85, 0x90, 0x57, 0x18, 0xea, 0xfd, 0x20, 0xad, 0x4a, 0x9f, 0x40,
	0x40, 0x52, 0x7b, 0xd6, 0x0b, 0xf5, 0x6e, 0x90, 0x20, 0xe2, 0x40, 0xe0, 0xed, 0x04, 0x4d, 0x6a,
	0x0c, 0x28, 0x6e, 0x29, 0xd5, 0xd4, 0xb0, 0xe7, 0x41, 0x71, 0x08, 0xe0, 0xf1, 0xb8, 0xb8, 0xca,
	0xc5, 0x8c, 0x1d, 0x84, 0x32, 0xac, 0x09, 0xb8, 0x19, 0xc1, 0x8d, 0x8a, 0x33, 0x0d, 0xa1, 0xed,
	0x87, 0x9b, 0x1b, 0xe4, 0xf0, 0xcf, 0x16, 0x39, 0xd8, 0x92, 0x0c, 0xf8, 0x9d, 0x42, 0xad, 0xd0,
	0x6f, 0x2b, 0xf8, 0x5d, 0x13, 0xd0, 0xf2, 0xf2, 0xd1, 0x4b, 0xab, 0x45, 0x8e, 0xd1, 0x86, 0x02,
	0x36, 0xb8, 0xb5, 0x07, 0x34, 0x08, 0x55, 0xdc, 0x10, 0xe0, 0x21, 0x80, 0xd8, 0xe8, 0x3b, 0x7e,
	0x5d, 0xa9, 0xbc, 0xc1, 0x0d, 0xff, 0x6e, 0x91, 0xcf, 0x7f, 0x90, 0x1e, 0x72, 0xcc, 0x85, 0xce,
	0xae, 0x55, 0x26, 0xb1, 0x4b, 0x3f, 0xc9, 0x14, 0x3f, 0x25, 0x24, 0x17, 0x1e, 0x68, 0xa1, 0x33,
	0x7c, 0xc0, 0x1e, 0xaf, 0x31, 0x30, 0x5b, 0xad, 0xd0, 0xd9, 0x38, 0xa9, 0x62, 0xaf, 0x10, 0x28,
	0x5b, 0x94, 0x25, 0xc4, 0x84, 0x09, 0x0d, 0x71, 0xd7, 0xa9, 0x95, 0x14, 0x70, 0x7b, 0x67, 0x23,
	0x05, 0x4c, 0xf5, 0xbf, 0x1d, 0x72, 0xf2, 0xe1, 0x27, 0x7d, 0xa2, 0x61, 0x7c, 0x45, 0x0e, 0x45,
	0x9a, 0xca, 0xd8, 0xcb, 0x04, 0x2e, 0xc1, 0xee, 0x6b, 0xe3, 0xb4, 0xdd, 0xf2, 0xf1, 0xa6, 0x66,
	0xc5, 0xdf, 0x3b, 0x43, 0xbf, 0x23, 0xfb, 0xa9, 0x55, 0x12, 0x9a, 0x35, 0x93, 0xb5, 0x99, 0xcd,
	0x9a, 0x5e, 0xae, 0xd6, 0x36, 0x7c, 0xcb, 0x1e, 0x3e, 0x5b, 0xa9, 0xc9, 0x73, 0xb3, 0x74, 0xac,
	0x33, 0x88, 0xe0, 0xb3, 0x55, 0x41, 0xfa, 0x35, 0x39, 0x8c, 0xe7, 0xa2, 0x28, 0x95, 0xd1, 0x97,
	0xe6, 0x41, 0x5a, 0xe8, 0xc9, 0x90, 0xa8, 0xf7, 0x78, 0x50, 0xf0, 0x8a, 0x7b, 0x6b, 0xbc, 0x37,
	0xd5, 0xbc, 0x6a, 0x92, 0xb5, 0x62, 0xed, 0x36, 0x8a, 0x75, 0x4a, 0x88, 0x9b, 0x0b, 0x2b, 0x6f,
	0x95, 0xcf, 0xc3, 0x97, 0xb0, 0xcb, 0x6b, 0x0c, 0x0c, 0x93, 0x54, 0xc5, 0xac, 0x8b, 0x1b, 0xb0,
	0x84, 0xf2, 0xce, 0x85, 0x5b, 0x87, 0x45, 0x50, 0x17, 0x75, 0x0a, 0xcf, 0x8c, 0x93, 0xaa, 0x87,
	0x61, 0x49, 0x5f, 0x91, 0x7e, 0xae, 0x32, 0xb9, 0xce, 0x77, 0x1f, 0x33, 0x75, 0xb4, 0xf5, 0x75,
	0xab, 0x2c, 0x78, 0xc3, 0x36, 0x78, 0x4b, 0xb1, 0xa7, 0xf7, 0xc0, 0x5b, 0x1a, 0x18, 0x5d, 0x75,
	0x2a, 0x2c, 0x03, 0x63, 0xb0, 0xbb, 0xd1, 0xc6, 0x04, 0xa6, 0x64, 0x87, 0x61, 0x08, 0xa6, 0xe3,
	0x32, 0x30, 0xf7, 0xec, 0x7f, 0xab, 0x53, 0xf7, 0xc3, 0x1b, 0xb2, 0xb7, 0xba, 0x13, 0x66, 0x87,
	0xd2, 0x89, 0x7c, 0x44, 0x39, 0x45, 0x3c, 0x80, 0x86, 0x50, 0xdb, 0x4d, 0xa1, 0x82, 0xbf, 0x6c,
	0x7e, 0x8f, 0xda, 0x8f, 0x38, 0x2c, 0x87, 0xaf, 0x08, 0xd9, 0x54, 0x1b, 0xf6, 0xcd, 0x4f, 0x69,
	0xe5, 0x0f, 0x96, 0x1f, 0xf3, 0x36, 0x7c, 0x20, 0xfd, 0xba, 0xde, 0xe0, 0xf4, 0x6c, 0xa9, 0x56,
	0xde, 0x67, 0x4b, 0x15, 0x98, 0x77, 0xd8, 0x4e, 0xc8, 0xbc, 0x0b, 0x4c, 0x56, 0xfd, 0x0e, 0xc1,
	0x12, 0x3f, 0xce, 0xb1, 0xb1, 0xc1, 0x7d, 0xc4, 0x03, 0xf8, 0xd8, 0xe4, 0xbd, 0xe8, 0xfd, 0xda,
	0x3d, 0x3b, 0xfb, 0x26, 0xd4, 0xe1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x9d, 0x7c, 0x08,
	0x2d, 0x0a, 0x00, 0x00,
}
