// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spamAndroid.proto

package wechat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpamAndroidBody struct {
	Loc                                  *uint32          `protobuf:"varint,1,opt,name=Loc" json:"Loc,omitempty"`
	Root                                 *uint32          `protobuf:"varint,2,opt,name=Root" json:"Root,omitempty"`
	Debug                                *uint32          `protobuf:"varint,3,opt,name=Debug" json:"Debug,omitempty"`
	PackageSign                          *string          `protobuf:"bytes,4,opt,name=PackageSign" json:"PackageSign,omitempty"`
	RadioVersion                         *string          `protobuf:"bytes,5,opt,name=RadioVersion" json:"RadioVersion,omitempty"`
	BuildVersion                         *string          `protobuf:"bytes,6,opt,name=BuildVersion" json:"BuildVersion,omitempty"`
	DeviceId                             *string          `protobuf:"bytes,7,opt,name=DeviceId" json:"DeviceId,omitempty"`
	AndroidId                            *string          `protobuf:"bytes,8,opt,name=AndroidId" json:"AndroidId,omitempty"`
	SerialId                             *string          `protobuf:"bytes,9,opt,name=SerialId" json:"SerialId,omitempty"`
	Model                                *string          `protobuf:"bytes,10,opt,name=Model" json:"Model,omitempty"`
	CpuCount                             *uint32          `protobuf:"varint,11,opt,name=CpuCount" json:"CpuCount,omitempty"`
	CpuBrand                             *string          `protobuf:"bytes,12,opt,name=CpuBrand" json:"CpuBrand,omitempty"`
	CpuExt                               *string          `protobuf:"bytes,13,opt,name=CpuExt" json:"CpuExt,omitempty"`
	WlanAddress                          *string          `protobuf:"bytes,14,opt,name=WlanAddress" json:"WlanAddress,omitempty"`
	Ssid                                 *string          `protobuf:"bytes,15,opt,name=Ssid" json:"Ssid,omitempty"`
	Bssid                                *string          `protobuf:"bytes,16,opt,name=Bssid" json:"Bssid,omitempty"`
	SimOperator                          *string          `protobuf:"bytes,17,opt,name=SimOperator" json:"SimOperator,omitempty"`
	WifiName                             *string          `protobuf:"bytes,18,opt,name=WifiName" json:"WifiName,omitempty"`
	BuildFP                              *string          `protobuf:"bytes,19,opt,name=BuildFP" json:"BuildFP,omitempty"`
	BuildBoard                           *string          `protobuf:"bytes,20,opt,name=BuildBoard" json:"BuildBoard,omitempty"`
	BuildBootLoader                      *string          `protobuf:"bytes,21,opt,name=BuildBootLoader" json:"BuildBootLoader,omitempty"`
	BuildBrand                           *string          `protobuf:"bytes,22,opt,name=BuildBrand" json:"BuildBrand,omitempty"`
	BuildDevice                          *string          `protobuf:"bytes,23,opt,name=BuildDevice" json:"BuildDevice,omitempty"`
	BuildHardware                        *string          `protobuf:"bytes,24,opt,name=BuildHardware" json:"BuildHardware,omitempty"`
	BuildProduct                         *string          `protobuf:"bytes,25,opt,name=BuildProduct" json:"BuildProduct,omitempty"`
	BuildManufacturer                    *string          `protobuf:"bytes,26,opt,name=BuildManufacturer" json:"BuildManufacturer,omitempty"`
	PhoneNum                             *string          `protobuf:"bytes,27,opt,name=PhoneNum" json:"PhoneNum,omitempty"`
	NetType                              *string          `protobuf:"bytes,28,opt,name=NetType" json:"NetType,omitempty"`
	Qemu                                 *uint64          `protobuf:"varint,29,opt,name=Qemu" json:"Qemu,omitempty"`
	Modified                             *uint64          `protobuf:"varint,30,opt,name=Modified" json:"Modified,omitempty"`
	Task                                 *uint64          `protobuf:"varint,31,opt,name=Task" json:"Task,omitempty"`
	PackageName                          *string          `protobuf:"bytes,32,opt,name=PackageName" json:"PackageName,omitempty"`
	AppName                              *string          `protobuf:"bytes,33,opt,name=AppName" json:"AppName,omitempty"`
	DataDir                              *string          `protobuf:"bytes,34,opt,name=DataDir" json:"DataDir,omitempty"`
	ClassLoader                          *string          `protobuf:"bytes,35,opt,name=ClassLoader" json:"ClassLoader,omitempty"`
	HardwareMask                         *uint64          `protobuf:"varint,38,opt,name=HardwareMask" json:"HardwareMask,omitempty"`
	Luckpackcount                        *uint64          `protobuf:"varint,41,opt,name=Luckpackcount" json:"Luckpackcount,omitempty"`
	BaseAPKMD5                           *string          `protobuf:"bytes,42,opt,name=BaseAPKMD5" json:"BaseAPKMD5,omitempty"`
	ClientVersion                        *string          `protobuf:"bytes,43,opt,name=ClientVersion" json:"ClientVersion,omitempty"`
	TbVersion                            *string          `protobuf:"bytes,44,opt,name=TbVersion" json:"TbVersion,omitempty"`
	Ip                                   *string          `protobuf:"bytes,45,opt,name=Ip" json:"Ip,omitempty"`
	Locale                               *string          `protobuf:"bytes,46,opt,name=Locale" json:"Locale,omitempty"`
	CallState                            *uint64          `protobuf:"varint,47,opt,name=CallState" json:"CallState,omitempty"`
	KeyGuardSecure                       *uint64          `protobuf:"varint,48,opt,name=KeyGuardSecure" json:"KeyGuardSecure,omitempty"`
	WifiOn                               *uint64          `protobuf:"varint,50,opt,name=WifiOn" json:"WifiOn,omitempty"`
	XposeCall                            *uint64          `protobuf:"varint,51,opt,name=XposeCall" json:"XposeCall,omitempty"`
	AdbEnable                            *uint64          `protobuf:"varint,53,opt,name=AdbEnable" json:"AdbEnable,omitempty"`
	Monkey                               *uint64          `protobuf:"varint,54,opt,name=Monkey" json:"Monkey,omitempty"`
	SplashName                           *string          `protobuf:"bytes,55,opt,name=SplashName" json:"SplashName,omitempty"`
	OsBinderProxy                        *string          `protobuf:"bytes,56,opt,name=OsBinderProxy" json:"OsBinderProxy,omitempty"`
	StubProxy                            *string          `protobuf:"bytes,57,opt,name=StubProxy" json:"StubProxy,omitempty"`
	VirtualNet                           *uint64          `protobuf:"varint,58,opt,name=VirtualNet" json:"VirtualNet,omitempty"`
	Vpn                                  *uint64          `protobuf:"varint,59,opt,name=Vpn" json:"Vpn,omitempty"`
	SubScriberId                         *string          `protobuf:"bytes,60,opt,name=SubScriberId" json:"SubScriberId,omitempty"`
	GsmSimSate                           *string          `protobuf:"bytes,61,opt,name=GsmSimSate" json:"GsmSimSate,omitempty"`
	GsmSimOperator                       *string          `protobuf:"bytes,62,opt,name=GsmSimOperator" json:"GsmSimOperator,omitempty"`
	GsmSimOperatorNumber                 *string          `protobuf:"bytes,63,opt,name=GsmSimOperatorNumber" json:"GsmSimOperatorNumber,omitempty"`
	SoterId                              *string          `protobuf:"bytes,64,opt,name=SoterId" json:"SoterId,omitempty"`
	KernelReleaseNumber                  *string          `protobuf:"bytes,65,opt,name=KernelReleaseNumber" json:"KernelReleaseNumber,omitempty"`
	UsbState                             *uint64          `protobuf:"varint,66,opt,name=UsbState" json:"UsbState,omitempty"`
	Sign                                 *string          `protobuf:"bytes,67,opt,name=Sign" json:"Sign,omitempty"`
	PackageFlag                          *uint64          `protobuf:"varint,68,opt,name=PackageFlag" json:"PackageFlag,omitempty"`
	AccessFlag                           *uint64          `protobuf:"varint,69,opt,name=AccessFlag" json:"AccessFlag,omitempty"`
	Unkonwn                              *uint64          `protobuf:"varint,70,opt,name=Unkonwn" json:"Unkonwn,omitempty"`
	TbVersionCrc                         *uint64          `protobuf:"varint,71,opt,name=TbVersionCrc" json:"TbVersionCrc,omitempty"`
	SfMD5                                *string          `protobuf:"bytes,72,opt,name=SfMD5" json:"SfMD5,omitempty"`
	SfArmMD5                             *string          `protobuf:"bytes,73,opt,name=SfArmMD5" json:"SfArmMD5,omitempty"`
	SfArm64MD5                           *string          `protobuf:"bytes,74,opt,name=SfArm64MD5" json:"SfArm64MD5,omitempty"`
	SbMD5                                *string          `protobuf:"bytes,75,opt,name=SbMD5" json:"SbMD5,omitempty"`
	SoterId2                             *string          `protobuf:"bytes,76,opt,name=SoterId2" json:"SoterId2,omitempty"`
	WidevineDeviceID                     *string          `protobuf:"bytes,77,opt,name=WidevineDeviceID" json:"WidevineDeviceID,omitempty"`
	FSID                                 *string          `protobuf:"bytes,78,opt,name=FSID" json:"FSID,omitempty"`
	Oaid                                 *string          `protobuf:"bytes,79,opt,name=Oaid" json:"Oaid,omitempty"`
	TimeCheck                            *uint64          `protobuf:"varint,80,opt,name=TimeCheck" json:"TimeCheck,omitempty"`
	NanoTime                             *uint64          `protobuf:"varint,81,opt,name=NanoTime" json:"NanoTime,omitempty"`
	Refreshtime                          *uint64          `protobuf:"varint,83,opt,name=Refreshtime" json:"Refreshtime,omitempty"`
	SoftConfig                           *string          `protobuf:"bytes,84,rep,name=SoftConfig" json:"SoftConfig,omitempty"`
	SoftData                             []byte           `protobuf:"bytes,85,rep,name=SoftData" json:"SoftData,omitempty"`
	DebugFlags                           *uint64          `protobuf:"varint,86,opt,name=DebugFlags" json:"DebugFlags,omitempty"`
	RouteIFace                           *string          `protobuf:"bytes,87,opt,name=RouteIFace" json:"RouteIFace,omitempty"`
	TvSec                                *uint64          `protobuf:"varint,88,opt,name=TvSec" json:"TvSec,omitempty"`
	TvUsec                               *uint64          `protobuf:"varint,89,opt,name=TvUsec" json:"TvUsec,omitempty"`
	TvCheck                              *uint64          `protobuf:"varint,90,opt,name=TvCheck" json:"TvCheck,omitempty"`
	PkgHash3Encrypted                    []byte           `protobuf:"bytes,91,opt,name=PkgHash3Encrypted" json:"PkgHash3Encrypted,omitempty"`
	PkgHash3Sum                          *uint64          `protobuf:"varint,92,opt,name=pkgHash3Sum" json:"pkgHash3Sum,omitempty"`
	EntranceClassLoaderNameEncrypted     []byte           `protobuf:"bytes,93,opt,name=EntranceClassLoaderNameEncrypted" json:"EntranceClassLoaderNameEncrypted,omitempty"`
	EntranceClassLoaderNameSum           *uint64          `protobuf:"varint,94,opt,name=EntranceClassLoaderNameSum" json:"EntranceClassLoaderNameSum,omitempty"`
	ApkLeadingMD5Encrypted               []byte           `protobuf:"bytes,95,opt,name=ApkLeadingMD5Encrypted" json:"ApkLeadingMD5Encrypted,omitempty"`
	ApkLeadingMD5Sum                     *uint64          `protobuf:"varint,96,opt,name=ApkLeadingMD5Sum" json:"ApkLeadingMD5Sum,omitempty"`
	AppInstrumentationClassNameEncrypted []byte           `protobuf:"bytes,97,opt,name=AppInstrumentationClassNameEncrypted" json:"AppInstrumentationClassNameEncrypted,omitempty"`
	AppInstrumentationClassNameSum       *uint64          `protobuf:"varint,98,opt,name=AppInstrumentationClassNameSum" json:"AppInstrumentationClassNameSum,omitempty"`
	AmsBinderClassNameEncrypted          []byte           `protobuf:"bytes,99,opt,name=AmsBinderClassNameEncrypted" json:"AmsBinderClassNameEncrypted,omitempty"`
	AmsBinderClassNameSum                *uint64          `protobuf:"varint,100,opt,name=AmsBinderClassNameSum" json:"AmsBinderClassNameSum,omitempty"`
	AmsSingletonClassNameEncrypted       []byte           `protobuf:"bytes,101,opt,name=AmsSingletonClassNameEncrypted" json:"AmsSingletonClassNameEncrypted,omitempty"`
	AmsSingletonClassNameSum             *uint64          `protobuf:"varint,102,opt,name=AmsSingletonClassNameSum" json:"AmsSingletonClassNameSum,omitempty"`
	ApkSignatureEncrypted                []byte           `protobuf:"bytes,103,opt,name=ApkSignatureEncrypted" json:"ApkSignatureEncrypted,omitempty"`
	ApkSignatureSum                      *uint64          `protobuf:"varint,104,opt,name=ApkSignatureSum" json:"ApkSignatureSum,omitempty"`
	FrameworkMd5Encrypted                []byte           `protobuf:"bytes,105,opt,name=FrameworkMd5Encrypted" json:"FrameworkMd5Encrypted,omitempty"`
	FrameworkMd5Sum                      *uint64          `protobuf:"varint,106,opt,name=FrameworkMd5Sum" json:"FrameworkMd5Sum,omitempty"`
	FrameworkArmMd5Encrypted             []byte           `protobuf:"bytes,107,opt,name=FrameworkArmMd5Encrypted" json:"FrameworkArmMd5Encrypted,omitempty"`
	FrameworkArmMd5Sum                   *uint64          `protobuf:"varint,108,opt,name=FrameworkArmMd5Sum" json:"FrameworkArmMd5Sum,omitempty"`
	FrameworkArm64Md5Encrypted           []byte           `protobuf:"bytes,109,opt,name=FrameworkArm64Md5Encrypted" json:"FrameworkArm64Md5Encrypted,omitempty"`
	FrameworkArm64Md5Sum                 *uint64          `protobuf:"varint,110,opt,name=FrameworkArm64Md5Sum" json:"FrameworkArm64Md5Sum,omitempty"`
	BinMd5Encrypted                      []byte           `protobuf:"bytes,111,opt,name=BinMd5Encrypted" json:"BinMd5Encrypted,omitempty"`
	BinMd5Sum                            *uint64          `protobuf:"varint,112,opt,name=BinMd5Sum" json:"BinMd5Sum,omitempty"`
	FsidEncrypted                        []byte           `protobuf:"bytes,113,opt,name=FsidEncrypted" json:"FsidEncrypted,omitempty"`
	FsidSum                              *uint64          `protobuf:"varint,114,opt,name=FsidSum" json:"FsidSum,omitempty"`
	RootFlags                            *uint64          `protobuf:"varint,115,opt,name=RootFlags" json:"RootFlags,omitempty"`
	Uid                                  *uint64          `protobuf:"varint,116,opt,name=uid" json:"uid,omitempty"`
	DebuggerFlags                        *uint64          `protobuf:"varint,117,opt,name=DebuggerFlags" json:"DebuggerFlags,omitempty"`
	ApkPathEncrypted                     []byte           `protobuf:"bytes,118,opt,name=ApkPathEncrypted" json:"ApkPathEncrypted,omitempty"`
	ApkPathEncrypted_                    *uint64          `protobuf:"varint,119,opt,name=apkPathEncrypted" json:"apkPathEncrypted,omitempty"`
	RealApkPathEncrypted                 []byte           `protobuf:"bytes,120,opt,name=RealApkPathEncrypted" json:"RealApkPathEncrypted,omitempty"`
	RealApkPathSum                       *uint64          `protobuf:"varint,121,opt,name=realApkPathSum" json:"realApkPathSum,omitempty"`
	IllegalLibraryEncrypted              []byte           `protobuf:"bytes,122,opt,name=illegalLibraryEncrypted" json:"illegalLibraryEncrypted,omitempty"`
	IllegalLibrarySum                    *uint64          `protobuf:"varint,123,opt,name=illegalLibrarySum" json:"illegalLibrarySum,omitempty"`
	StackTraceEncrypted                  []byte           `protobuf:"bytes,124,opt,name=stackTraceEncrypted" json:"stackTraceEncrypted,omitempty"`
	StackTraceSum                        *uint64          `protobuf:"varint,125,opt,name=stackTraceSum" json:"stackTraceSum,omitempty"`
	ExtraSystemInfo                      *ExtraSystemInfo `protobuf:"bytes,126,opt,name=extraSystemInfo" json:"extraSystemInfo,omitempty"`
	BinderFlags                          *uint64          `protobuf:"varint,127,opt,name=binderFlags" json:"binderFlags,omitempty"`
	XXX_NoUnkeyedLiteral                 struct{}         `json:"-"`
	XXX_unrecognized                     []byte           `json:"-"`
	XXX_sizecache                        int32            `json:"-"`
}

func (m *SpamAndroidBody) Reset()         { *m = SpamAndroidBody{} }
func (m *SpamAndroidBody) String() string { return proto.CompactTextString(m) }
func (*SpamAndroidBody) ProtoMessage()    {}
func (*SpamAndroidBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e39aca74c6de0f1, []int{0}
}

func (m *SpamAndroidBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpamAndroidBody.Unmarshal(m, b)
}
func (m *SpamAndroidBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpamAndroidBody.Marshal(b, m, deterministic)
}
func (m *SpamAndroidBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpamAndroidBody.Merge(m, src)
}
func (m *SpamAndroidBody) XXX_Size() int {
	return xxx_messageInfo_SpamAndroidBody.Size(m)
}
func (m *SpamAndroidBody) XXX_DiscardUnknown() {
	xxx_messageInfo_SpamAndroidBody.DiscardUnknown(m)
}

var xxx_messageInfo_SpamAndroidBody proto.InternalMessageInfo

func (m *SpamAndroidBody) GetLoc() uint32 {
	if m != nil && m.Loc != nil {
		return *m.Loc
	}
	return 0
}

func (m *SpamAndroidBody) GetRoot() uint32 {
	if m != nil && m.Root != nil {
		return *m.Root
	}
	return 0
}

func (m *SpamAndroidBody) GetDebug() uint32 {
	if m != nil && m.Debug != nil {
		return *m.Debug
	}
	return 0
}

func (m *SpamAndroidBody) GetPackageSign() string {
	if m != nil && m.PackageSign != nil {
		return *m.PackageSign
	}
	return ""
}

func (m *SpamAndroidBody) GetRadioVersion() string {
	if m != nil && m.RadioVersion != nil {
		return *m.RadioVersion
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildVersion() string {
	if m != nil && m.BuildVersion != nil {
		return *m.BuildVersion
	}
	return ""
}

func (m *SpamAndroidBody) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *SpamAndroidBody) GetAndroidId() string {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return ""
}

func (m *SpamAndroidBody) GetSerialId() string {
	if m != nil && m.SerialId != nil {
		return *m.SerialId
	}
	return ""
}

func (m *SpamAndroidBody) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *SpamAndroidBody) GetCpuCount() uint32 {
	if m != nil && m.CpuCount != nil {
		return *m.CpuCount
	}
	return 0
}

func (m *SpamAndroidBody) GetCpuBrand() string {
	if m != nil && m.CpuBrand != nil {
		return *m.CpuBrand
	}
	return ""
}

func (m *SpamAndroidBody) GetCpuExt() string {
	if m != nil && m.CpuExt != nil {
		return *m.CpuExt
	}
	return ""
}

func (m *SpamAndroidBody) GetWlanAddress() string {
	if m != nil && m.WlanAddress != nil {
		return *m.WlanAddress
	}
	return ""
}

func (m *SpamAndroidBody) GetSsid() string {
	if m != nil && m.Ssid != nil {
		return *m.Ssid
	}
	return ""
}

func (m *SpamAndroidBody) GetBssid() string {
	if m != nil && m.Bssid != nil {
		return *m.Bssid
	}
	return ""
}

func (m *SpamAndroidBody) GetSimOperator() string {
	if m != nil && m.SimOperator != nil {
		return *m.SimOperator
	}
	return ""
}

func (m *SpamAndroidBody) GetWifiName() string {
	if m != nil && m.WifiName != nil {
		return *m.WifiName
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildFP() string {
	if m != nil && m.BuildFP != nil {
		return *m.BuildFP
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildBoard() string {
	if m != nil && m.BuildBoard != nil {
		return *m.BuildBoard
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildBootLoader() string {
	if m != nil && m.BuildBootLoader != nil {
		return *m.BuildBootLoader
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildBrand() string {
	if m != nil && m.BuildBrand != nil {
		return *m.BuildBrand
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildDevice() string {
	if m != nil && m.BuildDevice != nil {
		return *m.BuildDevice
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildHardware() string {
	if m != nil && m.BuildHardware != nil {
		return *m.BuildHardware
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildProduct() string {
	if m != nil && m.BuildProduct != nil {
		return *m.BuildProduct
	}
	return ""
}

func (m *SpamAndroidBody) GetBuildManufacturer() string {
	if m != nil && m.BuildManufacturer != nil {
		return *m.BuildManufacturer
	}
	return ""
}

func (m *SpamAndroidBody) GetPhoneNum() string {
	if m != nil && m.PhoneNum != nil {
		return *m.PhoneNum
	}
	return ""
}

func (m *SpamAndroidBody) GetNetType() string {
	if m != nil && m.NetType != nil {
		return *m.NetType
	}
	return ""
}

func (m *SpamAndroidBody) GetQemu() uint64 {
	if m != nil && m.Qemu != nil {
		return *m.Qemu
	}
	return 0
}

func (m *SpamAndroidBody) GetModified() uint64 {
	if m != nil && m.Modified != nil {
		return *m.Modified
	}
	return 0
}

func (m *SpamAndroidBody) GetTask() uint64 {
	if m != nil && m.Task != nil {
		return *m.Task
	}
	return 0
}

func (m *SpamAndroidBody) GetPackageName() string {
	if m != nil && m.PackageName != nil {
		return *m.PackageName
	}
	return ""
}

func (m *SpamAndroidBody) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return ""
}

func (m *SpamAndroidBody) GetDataDir() string {
	if m != nil && m.DataDir != nil {
		return *m.DataDir
	}
	return ""
}

func (m *SpamAndroidBody) GetClassLoader() string {
	if m != nil && m.ClassLoader != nil {
		return *m.ClassLoader
	}
	return ""
}

func (m *SpamAndroidBody) GetHardwareMask() uint64 {
	if m != nil && m.HardwareMask != nil {
		return *m.HardwareMask
	}
	return 0
}

func (m *SpamAndroidBody) GetLuckpackcount() uint64 {
	if m != nil && m.Luckpackcount != nil {
		return *m.Luckpackcount
	}
	return 0
}

func (m *SpamAndroidBody) GetBaseAPKMD5() string {
	if m != nil && m.BaseAPKMD5 != nil {
		return *m.BaseAPKMD5
	}
	return ""
}

func (m *SpamAndroidBody) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

func (m *SpamAndroidBody) GetTbVersion() string {
	if m != nil && m.TbVersion != nil {
		return *m.TbVersion
	}
	return ""
}

func (m *SpamAndroidBody) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *SpamAndroidBody) GetLocale() string {
	if m != nil && m.Locale != nil {
		return *m.Locale
	}
	return ""
}

func (m *SpamAndroidBody) GetCallState() uint64 {
	if m != nil && m.CallState != nil {
		return *m.CallState
	}
	return 0
}

func (m *SpamAndroidBody) GetKeyGuardSecure() uint64 {
	if m != nil && m.KeyGuardSecure != nil {
		return *m.KeyGuardSecure
	}
	return 0
}

func (m *SpamAndroidBody) GetWifiOn() uint64 {
	if m != nil && m.WifiOn != nil {
		return *m.WifiOn
	}
	return 0
}

func (m *SpamAndroidBody) GetXposeCall() uint64 {
	if m != nil && m.XposeCall != nil {
		return *m.XposeCall
	}
	return 0
}

func (m *SpamAndroidBody) GetAdbEnable() uint64 {
	if m != nil && m.AdbEnable != nil {
		return *m.AdbEnable
	}
	return 0
}

func (m *SpamAndroidBody) GetMonkey() uint64 {
	if m != nil && m.Monkey != nil {
		return *m.Monkey
	}
	return 0
}

func (m *SpamAndroidBody) GetSplashName() string {
	if m != nil && m.SplashName != nil {
		return *m.SplashName
	}
	return ""
}

func (m *SpamAndroidBody) GetOsBinderProxy() string {
	if m != nil && m.OsBinderProxy != nil {
		return *m.OsBinderProxy
	}
	return ""
}

func (m *SpamAndroidBody) GetStubProxy() string {
	if m != nil && m.StubProxy != nil {
		return *m.StubProxy
	}
	return ""
}

func (m *SpamAndroidBody) GetVirtualNet() uint64 {
	if m != nil && m.VirtualNet != nil {
		return *m.VirtualNet
	}
	return 0
}

func (m *SpamAndroidBody) GetVpn() uint64 {
	if m != nil && m.Vpn != nil {
		return *m.Vpn
	}
	return 0
}

func (m *SpamAndroidBody) GetSubScriberId() string {
	if m != nil && m.SubScriberId != nil {
		return *m.SubScriberId
	}
	return ""
}

func (m *SpamAndroidBody) GetGsmSimSate() string {
	if m != nil && m.GsmSimSate != nil {
		return *m.GsmSimSate
	}
	return ""
}

func (m *SpamAndroidBody) GetGsmSimOperator() string {
	if m != nil && m.GsmSimOperator != nil {
		return *m.GsmSimOperator
	}
	return ""
}

func (m *SpamAndroidBody) GetGsmSimOperatorNumber() string {
	if m != nil && m.GsmSimOperatorNumber != nil {
		return *m.GsmSimOperatorNumber
	}
	return ""
}

func (m *SpamAndroidBody) GetSoterId() string {
	if m != nil && m.SoterId != nil {
		return *m.SoterId
	}
	return ""
}

func (m *SpamAndroidBody) GetKernelReleaseNumber() string {
	if m != nil && m.KernelReleaseNumber != nil {
		return *m.KernelReleaseNumber
	}
	return ""
}

func (m *SpamAndroidBody) GetUsbState() uint64 {
	if m != nil && m.UsbState != nil {
		return *m.UsbState
	}
	return 0
}

func (m *SpamAndroidBody) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

func (m *SpamAndroidBody) GetPackageFlag() uint64 {
	if m != nil && m.PackageFlag != nil {
		return *m.PackageFlag
	}
	return 0
}

func (m *SpamAndroidBody) GetAccessFlag() uint64 {
	if m != nil && m.AccessFlag != nil {
		return *m.AccessFlag
	}
	return 0
}

func (m *SpamAndroidBody) GetUnkonwn() uint64 {
	if m != nil && m.Unkonwn != nil {
		return *m.Unkonwn
	}
	return 0
}

func (m *SpamAndroidBody) GetTbVersionCrc() uint64 {
	if m != nil && m.TbVersionCrc != nil {
		return *m.TbVersionCrc
	}
	return 0
}

func (m *SpamAndroidBody) GetSfMD5() string {
	if m != nil && m.SfMD5 != nil {
		return *m.SfMD5
	}
	return ""
}

func (m *SpamAndroidBody) GetSfArmMD5() string {
	if m != nil && m.SfArmMD5 != nil {
		return *m.SfArmMD5
	}
	return ""
}

func (m *SpamAndroidBody) GetSfArm64MD5() string {
	if m != nil && m.SfArm64MD5 != nil {
		return *m.SfArm64MD5
	}
	return ""
}

func (m *SpamAndroidBody) GetSbMD5() string {
	if m != nil && m.SbMD5 != nil {
		return *m.SbMD5
	}
	return ""
}

func (m *SpamAndroidBody) GetSoterId2() string {
	if m != nil && m.SoterId2 != nil {
		return *m.SoterId2
	}
	return ""
}

func (m *SpamAndroidBody) GetWidevineDeviceID() string {
	if m != nil && m.WidevineDeviceID != nil {
		return *m.WidevineDeviceID
	}
	return ""
}

func (m *SpamAndroidBody) GetFSID() string {
	if m != nil && m.FSID != nil {
		return *m.FSID
	}
	return ""
}

func (m *SpamAndroidBody) GetOaid() string {
	if m != nil && m.Oaid != nil {
		return *m.Oaid
	}
	return ""
}

func (m *SpamAndroidBody) GetTimeCheck() uint64 {
	if m != nil && m.TimeCheck != nil {
		return *m.TimeCheck
	}
	return 0
}

func (m *SpamAndroidBody) GetNanoTime() uint64 {
	if m != nil && m.NanoTime != nil {
		return *m.NanoTime
	}
	return 0
}

func (m *SpamAndroidBody) GetRefreshtime() uint64 {
	if m != nil && m.Refreshtime != nil {
		return *m.Refreshtime
	}
	return 0
}

func (m *SpamAndroidBody) GetSoftConfig() string {
	if m != nil {
		return *m.SoftConfig
	}
	return ""
}

func (m *SpamAndroidBody) GetSoftData() []byte {
	if m != nil {
		return m.SoftData
	}
	return nil
}

func (m *SpamAndroidBody) GetDebugFlags() uint64 {
	if m != nil && m.DebugFlags != nil {
		return *m.DebugFlags
	}
	return 0
}

func (m *SpamAndroidBody) GetRouteIFace() string {
	if m != nil && m.RouteIFace != nil {
		return *m.RouteIFace
	}
	return ""
}

func (m *SpamAndroidBody) GetTvSec() uint64 {
	if m != nil && m.TvSec != nil {
		return *m.TvSec
	}
	return 0
}

func (m *SpamAndroidBody) GetTvUsec() uint64 {
	if m != nil && m.TvUsec != nil {
		return *m.TvUsec
	}
	return 0
}

func (m *SpamAndroidBody) GetTvCheck() uint64 {
	if m != nil && m.TvCheck != nil {
		return *m.TvCheck
	}
	return 0
}

func (m *SpamAndroidBody) GetPkgHash3Encrypted() []byte {
	if m != nil {
		return m.PkgHash3Encrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetPkgHash3Sum() uint64 {
	if m != nil && m.PkgHash3Sum != nil {
		return *m.PkgHash3Sum
	}
	return 0
}

func (m *SpamAndroidBody) GetEntranceClassLoaderNameEncrypted() []byte {
	if m != nil {
		return m.EntranceClassLoaderNameEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetEntranceClassLoaderNameSum() uint64 {
	if m != nil && m.EntranceClassLoaderNameSum != nil {
		return *m.EntranceClassLoaderNameSum
	}
	return 0
}

func (m *SpamAndroidBody) GetApkLeadingMD5Encrypted() []byte {
	if m != nil {
		return m.ApkLeadingMD5Encrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetApkLeadingMD5Sum() uint64 {
	if m != nil && m.ApkLeadingMD5Sum != nil {
		return *m.ApkLeadingMD5Sum
	}
	return 0
}

func (m *SpamAndroidBody) GetAppInstrumentationClassNameEncrypted() []byte {
	if m != nil {
		return m.AppInstrumentationClassNameEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetAppInstrumentationClassNameSum() uint64 {
	if m != nil && m.AppInstrumentationClassNameSum != nil {
		return *m.AppInstrumentationClassNameSum
	}
	return 0
}

func (m *SpamAndroidBody) GetAmsBinderClassNameEncrypted() []byte {
	if m != nil {
		return m.AmsBinderClassNameEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetAmsBinderClassNameSum() uint64 {
	if m != nil && m.AmsBinderClassNameSum != nil {
		return *m.AmsBinderClassNameSum
	}
	return 0
}

func (m *SpamAndroidBody) GetAmsSingletonClassNameEncrypted() []byte {
	if m != nil {
		return m.AmsSingletonClassNameEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetAmsSingletonClassNameSum() uint64 {
	if m != nil && m.AmsSingletonClassNameSum != nil {
		return *m.AmsSingletonClassNameSum
	}
	return 0
}

func (m *SpamAndroidBody) GetApkSignatureEncrypted() []byte {
	if m != nil {
		return m.ApkSignatureEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetApkSignatureSum() uint64 {
	if m != nil && m.ApkSignatureSum != nil {
		return *m.ApkSignatureSum
	}
	return 0
}

func (m *SpamAndroidBody) GetFrameworkMd5Encrypted() []byte {
	if m != nil {
		return m.FrameworkMd5Encrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetFrameworkMd5Sum() uint64 {
	if m != nil && m.FrameworkMd5Sum != nil {
		return *m.FrameworkMd5Sum
	}
	return 0
}

func (m *SpamAndroidBody) GetFrameworkArmMd5Encrypted() []byte {
	if m != nil {
		return m.FrameworkArmMd5Encrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetFrameworkArmMd5Sum() uint64 {
	if m != nil && m.FrameworkArmMd5Sum != nil {
		return *m.FrameworkArmMd5Sum
	}
	return 0
}

func (m *SpamAndroidBody) GetFrameworkArm64Md5Encrypted() []byte {
	if m != nil {
		return m.FrameworkArm64Md5Encrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetFrameworkArm64Md5Sum() uint64 {
	if m != nil && m.FrameworkArm64Md5Sum != nil {
		return *m.FrameworkArm64Md5Sum
	}
	return 0
}

func (m *SpamAndroidBody) GetBinMd5Encrypted() []byte {
	if m != nil {
		return m.BinMd5Encrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetBinMd5Sum() uint64 {
	if m != nil && m.BinMd5Sum != nil {
		return *m.BinMd5Sum
	}
	return 0
}

func (m *SpamAndroidBody) GetFsidEncrypted() []byte {
	if m != nil {
		return m.FsidEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetFsidSum() uint64 {
	if m != nil && m.FsidSum != nil {
		return *m.FsidSum
	}
	return 0
}

func (m *SpamAndroidBody) GetRootFlags() uint64 {
	if m != nil && m.RootFlags != nil {
		return *m.RootFlags
	}
	return 0
}

func (m *SpamAndroidBody) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *SpamAndroidBody) GetDebuggerFlags() uint64 {
	if m != nil && m.DebuggerFlags != nil {
		return *m.DebuggerFlags
	}
	return 0
}

func (m *SpamAndroidBody) GetApkPathEncrypted() []byte {
	if m != nil {
		return m.ApkPathEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetApkPathEncrypted_() uint64 {
	if m != nil && m.ApkPathEncrypted_ != nil {
		return *m.ApkPathEncrypted_
	}
	return 0
}

func (m *SpamAndroidBody) GetRealApkPathEncrypted() []byte {
	if m != nil {
		return m.RealApkPathEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetRealApkPathSum() uint64 {
	if m != nil && m.RealApkPathSum != nil {
		return *m.RealApkPathSum
	}
	return 0
}

func (m *SpamAndroidBody) GetIllegalLibraryEncrypted() []byte {
	if m != nil {
		return m.IllegalLibraryEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetIllegalLibrarySum() uint64 {
	if m != nil && m.IllegalLibrarySum != nil {
		return *m.IllegalLibrarySum
	}
	return 0
}

func (m *SpamAndroidBody) GetStackTraceEncrypted() []byte {
	if m != nil {
		return m.StackTraceEncrypted
	}
	return nil
}

func (m *SpamAndroidBody) GetStackTraceSum() uint64 {
	if m != nil && m.StackTraceSum != nil {
		return *m.StackTraceSum
	}
	return 0
}

func (m *SpamAndroidBody) GetExtraSystemInfo() *ExtraSystemInfo {
	if m != nil {
		return m.ExtraSystemInfo
	}
	return nil
}

func (m *SpamAndroidBody) GetBinderFlags() uint64 {
	if m != nil && m.BinderFlags != nil {
		return *m.BinderFlags
	}
	return 0
}

type ExtraSystemInfo struct {
	ServiceNamesMd5Encrypted         []byte   `protobuf:"bytes,1,opt,name=serviceNamesMd5Encrypted" json:"serviceNamesMd5Encrypted,omitempty"`
	ServiceNamesMd5Sum               *uint64  `protobuf:"varint,2,opt,name=serviceNamesMd5Sum" json:"serviceNamesMd5Sum,omitempty"`
	SystemAppMd5Encrypted            []byte   `protobuf:"bytes,3,opt,name=systemAppMd5Encrypted" json:"systemAppMd5Encrypted,omitempty"`
	SystemAppMd5Sum                  *uint64  `protobuf:"varint,4,opt,name=systemAppMd5Sum" json:"systemAppMd5Sum,omitempty"`
	SystemPrivateAppMd5Encrypted     []byte   `protobuf:"bytes,5,opt,name=systemPrivateAppMd5Encrypted" json:"systemPrivateAppMd5Encrypted,omitempty"`
	SystemPrivateAppMd5Sum           *uint64  `protobuf:"varint,6,opt,name=systemPrivateAppMd5Sum" json:"systemPrivateAppMd5Sum,omitempty"`
	VendorAppMd5Encrypted            []byte   `protobuf:"bytes,7,opt,name=vendorAppMd5Encrypted" json:"vendorAppMd5Encrypted,omitempty"`
	VendorAppMd5Sum                  *uint64  `protobuf:"varint,8,opt,name=vendorAppMd5Sum" json:"vendorAppMd5Sum,omitempty"`
	ProductAppMd5Encrypted           []byte   `protobuf:"bytes,9,opt,name=productAppMd5Encrypted" json:"productAppMd5Encrypted,omitempty"`
	ProductAppMd5Sum                 *uint64  `protobuf:"varint,10,opt,name=productAppMd5Sum" json:"productAppMd5Sum,omitempty"`
	LsMd5Encrypted                   []byte   `protobuf:"bytes,11,opt,name=lsMd5Encrypted" json:"lsMd5Encrypted,omitempty"`
	LsMd5Sum                         *uint64  `protobuf:"varint,12,opt,name=lsMd5Sum" json:"lsMd5Sum,omitempty"`
	FrameworkResMd5Encrypted         []byte   `protobuf:"bytes,13,opt,name=frameworkResMd5Encrypted" json:"frameworkResMd5Encrypted,omitempty"`
	FrameworkResMd5Sum               *uint64  `protobuf:"varint,14,opt,name=frameworkResMd5Sum" json:"frameworkResMd5Sum,omitempty"`
	LibCppMd5Encrypted               []byte   `protobuf:"bytes,15,opt,name=libCppMd5Encrypted" json:"libCppMd5Encrypted,omitempty"`
	LibCppMd5Sum                     *uint64  `protobuf:"varint,16,opt,name=libCppMd5Sum" json:"libCppMd5Sum,omitempty"`
	LinkerMd5Encrypted               []byte   `protobuf:"bytes,17,opt,name=linkerMd5Encrypted" json:"linkerMd5Encrypted,omitempty"`
	LinkerMd5Sum                     *uint64  `protobuf:"varint,18,opt,name=linkerMd5Sum" json:"linkerMd5Sum,omitempty"`
	RootDirLastAccessTimeEncrypted   []byte   `protobuf:"bytes,19,opt,name=rootDirLastAccessTimeEncrypted" json:"rootDirLastAccessTimeEncrypted,omitempty"`
	RootDirLastAccessTimeSum         *uint64  `protobuf:"varint,20,opt,name=rootDirLastAccessTimeSum" json:"rootDirLastAccessTimeSum,omitempty"`
	SystemDirLastAccessTimeEncrypted []byte   `protobuf:"bytes,21,opt,name=systemDirLastAccessTimeEncrypted" json:"systemDirLastAccessTimeEncrypted,omitempty"`
	SystemDirLastAccessTimeSum       *uint64  `protobuf:"varint,22,opt,name=systemDirLastAccessTimeSum" json:"systemDirLastAccessTimeSum,omitempty"`
	DataDirLastAccessTimeEncrypted   []byte   `protobuf:"bytes,23,opt,name=dataDirLastAccessTimeEncrypted" json:"dataDirLastAccessTimeEncrypted,omitempty"`
	DataDirLastAccessTimeSum         *uint64  `protobuf:"varint,24,opt,name=dataDirLastAccessTimeSum" json:"dataDirLastAccessTimeSum,omitempty"`
	BuildFPEncrypted                 []byte   `protobuf:"bytes,25,opt,name=buildFPEncrypted" json:"buildFPEncrypted,omitempty"`
	BuildFPSum                       *uint64  `protobuf:"varint,26,opt,name=buildFPSum" json:"buildFPSum,omitempty"`
	KernelEncrypted                  []byte   `protobuf:"bytes,27,opt,name=kernelEncrypted" json:"kernelEncrypted,omitempty"`
	KernelSum                        *uint64  `protobuf:"varint,28,opt,name=kernelSum" json:"kernelSum,omitempty"`
	XXX_NoUnkeyedLiteral             struct{} `json:"-"`
	XXX_unrecognized                 []byte   `json:"-"`
	XXX_sizecache                    int32    `json:"-"`
}

func (m *ExtraSystemInfo) Reset()         { *m = ExtraSystemInfo{} }
func (m *ExtraSystemInfo) String() string { return proto.CompactTextString(m) }
func (*ExtraSystemInfo) ProtoMessage()    {}
func (*ExtraSystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e39aca74c6de0f1, []int{1}
}

func (m *ExtraSystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraSystemInfo.Unmarshal(m, b)
}
func (m *ExtraSystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraSystemInfo.Marshal(b, m, deterministic)
}
func (m *ExtraSystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraSystemInfo.Merge(m, src)
}
func (m *ExtraSystemInfo) XXX_Size() int {
	return xxx_messageInfo_ExtraSystemInfo.Size(m)
}
func (m *ExtraSystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraSystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraSystemInfo proto.InternalMessageInfo

func (m *ExtraSystemInfo) GetServiceNamesMd5Encrypted() []byte {
	if m != nil {
		return m.ServiceNamesMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetServiceNamesMd5Sum() uint64 {
	if m != nil && m.ServiceNamesMd5Sum != nil {
		return *m.ServiceNamesMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetSystemAppMd5Encrypted() []byte {
	if m != nil {
		return m.SystemAppMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetSystemAppMd5Sum() uint64 {
	if m != nil && m.SystemAppMd5Sum != nil {
		return *m.SystemAppMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetSystemPrivateAppMd5Encrypted() []byte {
	if m != nil {
		return m.SystemPrivateAppMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetSystemPrivateAppMd5Sum() uint64 {
	if m != nil && m.SystemPrivateAppMd5Sum != nil {
		return *m.SystemPrivateAppMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetVendorAppMd5Encrypted() []byte {
	if m != nil {
		return m.VendorAppMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetVendorAppMd5Sum() uint64 {
	if m != nil && m.VendorAppMd5Sum != nil {
		return *m.VendorAppMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetProductAppMd5Encrypted() []byte {
	if m != nil {
		return m.ProductAppMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetProductAppMd5Sum() uint64 {
	if m != nil && m.ProductAppMd5Sum != nil {
		return *m.ProductAppMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetLsMd5Encrypted() []byte {
	if m != nil {
		return m.LsMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetLsMd5Sum() uint64 {
	if m != nil && m.LsMd5Sum != nil {
		return *m.LsMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetFrameworkResMd5Encrypted() []byte {
	if m != nil {
		return m.FrameworkResMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetFrameworkResMd5Sum() uint64 {
	if m != nil && m.FrameworkResMd5Sum != nil {
		return *m.FrameworkResMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetLibCppMd5Encrypted() []byte {
	if m != nil {
		return m.LibCppMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetLibCppMd5Sum() uint64 {
	if m != nil && m.LibCppMd5Sum != nil {
		return *m.LibCppMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetLinkerMd5Encrypted() []byte {
	if m != nil {
		return m.LinkerMd5Encrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetLinkerMd5Sum() uint64 {
	if m != nil && m.LinkerMd5Sum != nil {
		return *m.LinkerMd5Sum
	}
	return 0
}

func (m *ExtraSystemInfo) GetRootDirLastAccessTimeEncrypted() []byte {
	if m != nil {
		return m.RootDirLastAccessTimeEncrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetRootDirLastAccessTimeSum() uint64 {
	if m != nil && m.RootDirLastAccessTimeSum != nil {
		return *m.RootDirLastAccessTimeSum
	}
	return 0
}

func (m *ExtraSystemInfo) GetSystemDirLastAccessTimeEncrypted() []byte {
	if m != nil {
		return m.SystemDirLastAccessTimeEncrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetSystemDirLastAccessTimeSum() uint64 {
	if m != nil && m.SystemDirLastAccessTimeSum != nil {
		return *m.SystemDirLastAccessTimeSum
	}
	return 0
}

func (m *ExtraSystemInfo) GetDataDirLastAccessTimeEncrypted() []byte {
	if m != nil {
		return m.DataDirLastAccessTimeEncrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetDataDirLastAccessTimeSum() uint64 {
	if m != nil && m.DataDirLastAccessTimeSum != nil {
		return *m.DataDirLastAccessTimeSum
	}
	return 0
}

func (m *ExtraSystemInfo) GetBuildFPEncrypted() []byte {
	if m != nil {
		return m.BuildFPEncrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetBuildFPSum() uint64 {
	if m != nil && m.BuildFPSum != nil {
		return *m.BuildFPSum
	}
	return 0
}

func (m *ExtraSystemInfo) GetKernelEncrypted() []byte {
	if m != nil {
		return m.KernelEncrypted
	}
	return nil
}

func (m *ExtraSystemInfo) GetKernelSum() uint64 {
	if m != nil && m.KernelSum != nil {
		return *m.KernelSum
	}
	return 0
}

func init() {
	proto.RegisterType((*SpamAndroidBody)(nil), "wechat_proto.SpamAndroidBody")
	proto.RegisterType((*ExtraSystemInfo)(nil), "wechat_proto.ExtraSystemInfo")
}

func init() { proto.RegisterFile("spamAndroid.proto", fileDescriptor_3e39aca74c6de0f1) }

var fileDescriptor_3e39aca74c6de0f1 = []byte{
	// 2028 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0x6b, 0x77, 0xdb, 0xc6,
	0x11, 0x3d, 0xf2, 0xdb, 0x2b, 0xd9, 0xb2, 0xe1, 0xd7, 0xc6, 0x76, 0x5c, 0xc6, 0xcd, 0xc9, 0x51,
	0xd3, 0x54, 0xc9, 0x71, 0x6c, 0x37, 0x4d, 0xdb, 0x34, 0x14, 0x29, 0xd9, 0x8c, 0x25, 0x99, 0x21,
	0x64, 0x3b, 0x4d, 0x1f, 0xe9, 0x12, 0x58, 0x52, 0x28, 0x41, 0x00, 0x5d, 0x00, 0x92, 0xd5, 0xe7,
	0x2f, 0xe9, 0xbf, 0xec, 0x0f, 0xe8, 0xb9, 0x33, 0x78, 0x13, 0x94, 0xf3, 0x0d, 0x73, 0xef, 0xe0,
	0xce, 0x60, 0x76, 0x67, 0x76, 0x49, 0x71, 0x3d, 0x8e, 0xd4, 0xbc, 0x1b, 0xb8, 0x26, 0xf4, 0xdc,
	0xcd, 0xc8, 0x84, 0x49, 0x68, 0xad, 0x1d, 0x6b, 0xe7, 0x50, 0x25, 0x3f, 0x90, 0x75, 0x37, 0xb3,
	0x98, 0x7b, 0xf8, 0xbf, 0x0f, 0xc4, 0xba, 0x5d, 0xbe, 0xb1, 0x15, 0xba, 0x27, 0xd6, 0x35, 0x71,
	0x76, 0x37, 0x74, 0xe4, 0x4a, 0x67, 0x65, 0xe3, 0xca, 0x08, 0x8f, 0x96, 0x25, 0xce, 0x8d, 0xc2,
	0x30, 0x91, 0x67, 0x08, 0xa2, 0x67, 0xeb, 0xa6, 0x38, 0xdf, 0xd7, 0xe3, 0x74, 0x2a, 0xcf, 0x12,
	0xc8, 0x86, 0xd5, 0x11, 0xab, 0x43, 0xe5, 0xcc, 0xd4, 0x54, 0xdb, 0xde, 0x34, 0x90, 0xe7, 0x3a,
	0x2b, 0x1b, 0x97, 0x47, 0x55, 0xc8, 0x7a, 0x28, 0xd6, 0x46, 0xca, 0xf5, 0xc2, 0xd7, 0xda, 0xc4,
	0x5e, 0x18, 0xc8, 0xf3, 0xe4, 0x52, 0xc3, 0xe0, 0xb3, 0x95, 0x7a, 0xbe, 0x9b, 0xfb, 0x5c, 0x60,
	0x9f, 0x2a, 0x66, 0xdd, 0x15, 0x97, 0xfa, 0xfa, 0xc8, 0x73, 0xf4, 0xc0, 0x95, 0x17, 0x89, 0x2f,
	0x6c, 0xeb, 0xbe, 0xb8, 0x9c, 0x7d, 0xd0, 0xc0, 0x95, 0x97, 0x88, 0x2c, 0x01, 0xbc, 0x69, 0x6b,
	0xe3, 0x29, 0x7f, 0xe0, 0xca, 0xcb, 0xfc, 0x66, 0x6e, 0xe3, 0xab, 0xf6, 0x42, 0x57, 0xfb, 0x52,
	0x10, 0xc1, 0x06, 0xde, 0xe8, 0x45, 0x69, 0x2f, 0x4c, 0x83, 0x44, 0xae, 0xd2, 0xe7, 0x16, 0x76,
	0xc6, 0x6d, 0x19, 0x15, 0xb8, 0x72, 0x8d, 0xd5, 0x72, 0xdb, 0xba, 0x2d, 0x2e, 0xf4, 0xa2, 0x74,
	0xfb, 0x6d, 0x22, 0xaf, 0x10, 0x93, 0x59, 0xa8, 0xd2, 0x1b, 0x5f, 0x05, 0x5d, 0xd7, 0x35, 0x3a,
	0x8e, 0xe5, 0x55, 0xae, 0x52, 0x05, 0x42, 0xc5, 0xed, 0xd8, 0x73, 0xe5, 0x3a, 0x51, 0xf4, 0x8c,
	0xdc, 0xb6, 0x62, 0x80, 0xd7, 0x38, 0x37, 0x32, 0xa0, 0x65, 0x7b, 0xf3, 0x97, 0x91, 0x36, 0x2a,
	0x09, 0x8d, 0xbc, 0xce, 0x5a, 0x15, 0x08, 0x19, 0xbe, 0xf1, 0x26, 0xde, 0xbe, 0x9a, 0x6b, 0x69,
	0x71, 0x86, 0xb9, 0x6d, 0x49, 0x71, 0x91, 0xaa, 0xba, 0x33, 0x94, 0x37, 0x88, 0xca, 0x4d, 0xeb,
	0x81, 0x10, 0xf4, 0xb8, 0x15, 0x2a, 0xe3, 0xca, 0x9b, 0x44, 0x56, 0x10, 0x6b, 0x43, 0xac, 0x67,
	0x56, 0x98, 0xec, 0x86, 0xca, 0xd5, 0x46, 0xde, 0x22, 0xa7, 0x26, 0x5c, 0x2a, 0x51, 0x8d, 0x6e,
	0x57, 0x95, 0xa8, 0x4a, 0x1d, 0xb1, 0x4a, 0x16, 0x2f, 0x9f, 0xbc, 0xc3, 0x5f, 0x50, 0x81, 0xac,
	0x0f, 0xc5, 0x15, 0x32, 0x9f, 0x2b, 0xe3, 0x1e, 0x2b, 0xa3, 0xa5, 0x24, 0x9f, 0x3a, 0x58, 0xec,
	0x9a, 0xa1, 0x09, 0xdd, 0xd4, 0x49, 0xe4, 0x7b, 0x95, 0x5d, 0x93, 0x61, 0xd6, 0x27, 0xe2, 0x3a,
	0xd9, 0x7b, 0x2a, 0x48, 0x27, 0xca, 0x49, 0x52, 0xa3, 0x8d, 0xbc, 0x4b, 0x8e, 0x8b, 0x04, 0x2a,
	0x37, 0x3c, 0x0c, 0x03, 0xbd, 0x9f, 0xce, 0xe5, 0x3d, 0xae, 0x5c, 0x6e, 0xa3, 0x72, 0xfb, 0x3a,
	0x39, 0x38, 0x89, 0xb4, 0xbc, 0xcf, 0x95, 0xcb, 0x4c, 0xac, 0xdd, 0xb7, 0x7a, 0x9e, 0xca, 0xf7,
	0x3b, 0x2b, 0x1b, 0xe7, 0x46, 0xf4, 0x0c, 0xa5, 0xbd, 0xd0, 0xf5, 0x26, 0x9e, 0x76, 0xe5, 0x03,
	0xc2, 0x0b, 0x1b, 0xfe, 0x07, 0x2a, 0x9e, 0xc9, 0x9f, 0xb0, 0x3f, 0x9e, 0x2b, 0x7d, 0x44, 0xcb,
	0xd6, 0xa9, 0xf5, 0x51, 0xbe, 0x72, 0xdd, 0x28, 0x22, 0xf6, 0x03, 0x8e, 0x9f, 0x99, 0x60, 0xfa,
	0x2a, 0x51, 0x7d, 0xcf, 0xc8, 0x87, 0xcc, 0x64, 0x26, 0x54, 0x7b, 0xbe, 0x8a, 0xe3, 0x6c, 0xbd,
	0x7e, 0xca, 0xaa, 0x15, 0x08, 0x35, 0xcc, 0xeb, 0xb9, 0x87, 0x9c, 0x3e, 0xa2, 0x9c, 0x6a, 0x18,
	0x56, 0x63, 0x37, 0x75, 0x66, 0x91, 0x72, 0x66, 0x0e, 0xb5, 0xc4, 0xcf, 0xc8, 0xa9, 0x0e, 0xd2,
	0xaa, 0xab, 0x58, 0x77, 0x87, 0x2f, 0xf6, 0xfa, 0x4f, 0xe4, 0xc7, 0xd9, 0xaa, 0x17, 0x08, 0x54,
	0x7a, 0xbe, 0xa7, 0x83, 0x24, 0x6f, 0xf2, 0x9f, 0xf3, 0x9a, 0xd6, 0x40, 0x74, 0xf2, 0xc1, 0x38,
	0xf7, 0xf8, 0x84, 0x3b, 0xb9, 0x00, 0xac, 0xab, 0xe2, 0xcc, 0x20, 0x92, 0xbf, 0x20, 0xf8, 0xcc,
	0x20, 0x42, 0xbf, 0xed, 0x86, 0x8e, 0xf2, 0xb5, 0xdc, 0xe4, 0x7e, 0x63, 0x0b, 0x2a, 0x3d, 0xe5,
	0xfb, 0x76, 0xa2, 0x12, 0x2d, 0x3f, 0xa5, 0x6c, 0x4b, 0xc0, 0xfa, 0x48, 0x5c, 0x7d, 0xa1, 0x4f,
	0x9e, 0xa5, 0xca, 0xb8, 0xb6, 0x76, 0x52, 0xa3, 0xe5, 0x67, 0xe4, 0xd2, 0x40, 0xa1, 0x8e, 0xbe,
	0x79, 0x19, 0xc8, 0x47, 0xc4, 0x67, 0x16, 0xd4, 0xbf, 0x8b, 0xc2, 0x58, 0x43, 0x51, 0x7e, 0xce,
	0xea, 0x05, 0x40, 0xb3, 0xc8, 0x1d, 0x6f, 0x07, 0x6a, 0xec, 0x6b, 0xf9, 0x84, 0xd9, 0x02, 0x80,
	0xe6, 0x5e, 0x18, 0xcc, 0xf4, 0x89, 0x7c, 0xca, 0x9a, 0x6c, 0xa1, 0x7a, 0x76, 0xe4, 0xab, 0xf8,
	0x90, 0x16, 0xf8, 0x97, 0x5c, 0xbd, 0x12, 0x41, 0xf5, 0x5e, 0xc6, 0x5b, 0x5e, 0xe0, 0x6a, 0x33,
	0x34, 0xe1, 0xdb, 0x13, 0xf9, 0x05, 0x57, 0xaf, 0x06, 0x22, 0xb6, 0x9d, 0xa4, 0x63, 0xf6, 0xf8,
	0x15, 0x57, 0xaf, 0x00, 0x10, 0xe3, 0xb5, 0x67, 0x92, 0x54, 0xf9, 0xfb, 0x3a, 0x91, 0x5f, 0x52,
	0xfc, 0x0a, 0x82, 0x73, 0xe0, 0x75, 0x14, 0xc8, 0x5f, 0x13, 0x81, 0x47, 0xec, 0x0e, 0x3b, 0x1d,
	0xdb, 0x8e, 0xf1, 0xc6, 0xda, 0x0c, 0x5c, 0xf9, 0x1b, 0xee, 0xb0, 0x2a, 0x06, 0xd5, 0x67, 0xf1,
	0xdc, 0xf6, 0xe6, 0x36, 0x8a, 0xfd, 0x5b, 0xce, 0xbc, 0x44, 0x50, 0x6d, 0xb6, 0x8a, 0x91, 0xf5,
	0x15, 0xf9, 0x34, 0x50, 0xeb, 0x91, 0xb8, 0x59, 0x47, 0xf6, 0xd3, 0xf9, 0x58, 0x1b, 0xf9, 0x3b,
	0xf2, 0x6e, 0xe5, 0xb0, 0xf3, 0xed, 0x30, 0xa1, 0xd4, 0xbe, 0xe6, 0x9d, 0x9f, 0x99, 0xd6, 0x67,
	0xe2, 0xc6, 0x0b, 0x6d, 0x02, 0xed, 0x8f, 0xb4, 0xaf, 0x55, 0xac, 0x33, 0xb1, 0x2e, 0x79, 0xb5,
	0x51, 0xe8, 0xd8, 0x57, 0xf1, 0x98, 0xb7, 0xcc, 0x16, 0x77, 0x6c, 0x6e, 0xd3, 0x74, 0xc6, 0xf1,
	0xd6, 0xcb, 0xa6, 0x33, 0xce, 0xb5, 0xb2, 0x63, 0x77, 0x7c, 0x35, 0x95, 0x7d, 0x7a, 0xa5, 0x0a,
	0xa1, 0x32, 0x5d, 0xc7, 0xd1, 0x71, 0x4c, 0x0e, 0xdb, 0x5c, 0xef, 0x12, 0x41, 0xf6, 0xaf, 0x82,
	0x59, 0x18, 0x1c, 0x07, 0x72, 0x87, 0xc8, 0xdc, 0x44, 0xdd, 0x8b, 0x4d, 0xdf, 0x33, 0x8e, 0x7c,
	0xc6, 0x5d, 0x59, 0xc5, 0x70, 0x3a, 0xd8, 0x13, 0xb4, 0xda, 0x73, 0x3e, 0x1d, 0xc8, 0xa0, 0xb3,
	0x6e, 0xd2, 0x35, 0x73, 0x10, 0x83, 0xec, 0xac, 0xcb, 0x6c, 0xda, 0x63, 0x78, 0x7e, 0xfa, 0x18,
	0xec, 0x37, 0xd9, 0x1e, 0x2b, 0x10, 0x52, 0x1c, 0x83, 0x7a, 0x91, 0x29, 0x8e, 0x73, 0x45, 0x2e,
	0xea, 0x23, 0xb9, 0x9b, 0x29, 0x66, 0xb6, 0xf5, 0xb1, 0xb8, 0xf6, 0xc6, 0x73, 0xf5, 0x91, 0x17,
	0xe8, 0xec, 0x2c, 0xee, 0xcb, 0x3d, 0xf2, 0x59, 0xc0, 0x51, 0xc3, 0x1d, 0x7b, 0xd0, 0x97, 0xfb,
	0x5c, 0x43, 0x3c, 0x03, 0x7b, 0xa9, 0x3c, 0x57, 0xbe, 0x64, 0x0c, 0xcf, 0x34, 0x01, 0xbc, 0xb9,
	0xee, 0x1d, 0x6a, 0x67, 0x26, 0x87, 0xdc, 0x3f, 0x05, 0x80, 0x6c, 0xf6, 0x55, 0x10, 0x02, 0x90,
	0xdf, 0xf2, 0x2a, 0xe5, 0x36, 0x56, 0x64, 0xa4, 0x27, 0x46, 0xc7, 0x87, 0x09, 0x68, 0x9b, 0x57,
	0xa4, 0x02, 0x51, 0x05, 0xc2, 0x49, 0xd2, 0x0b, 0x83, 0x89, 0x37, 0x95, 0x07, 0x9d, 0xb3, 0x1b,
	0x6b, 0xa3, 0x0a, 0xc2, 0xdf, 0x3a, 0x49, 0x30, 0x3e, 0xe5, 0x2b, 0x62, 0x0b, 0x1b, 0xef, 0xd2,
	0x95, 0x07, 0x4b, 0x17, 0xcb, 0xd7, 0xbc, 0x9a, 0x25, 0x02, 0x7e, 0x14, 0xa6, 0x89, 0x1e, 0xec,
	0x28, 0x47, 0xcb, 0x37, 0x5c, 0xdd, 0x12, 0x41, 0x75, 0x0f, 0x8e, 0x6c, 0xed, 0xc8, 0xef, 0xe8,
	0x55, 0x36, 0x30, 0x0f, 0x0e, 0x8e, 0x5e, 0xc5, 0xda, 0x91, 0xbf, 0xe7, 0x79, 0xc0, 0x16, 0xf6,
	0xc6, 0xc1, 0x11, 0xd7, 0xe0, 0x7b, 0xde, 0x1b, 0x99, 0x89, 0x13, 0x6d, 0x38, 0x9b, 0x3e, 0x57,
	0xf1, 0xe1, 0xe7, 0xdb, 0x81, 0x63, 0x4e, 0xa2, 0x44, 0xbb, 0xf2, 0x0f, 0x9d, 0x95, 0x8d, 0xb5,
	0xd1, 0x22, 0x81, 0x9a, 0x44, 0x19, 0x68, 0xa7, 0x73, 0xf9, 0x47, 0xae, 0x49, 0x05, 0xb2, 0xbe,
	0x11, 0x9d, 0xed, 0x20, 0x31, 0x2a, 0x70, 0x74, 0xe5, 0x60, 0xc0, 0xd0, 0x29, 0xe5, 0xff, 0x44,
	0xf2, 0xef, 0xf4, 0xb3, 0xbe, 0x12, 0x77, 0x97, 0xf8, 0x20, 0xf8, 0x9f, 0x29, 0xf8, 0x29, 0x1e,
	0xd6, 0x53, 0x71, 0xbb, 0x1b, 0xcd, 0x76, 0xb5, 0x72, 0xbd, 0x60, 0xba, 0xd7, 0x7f, 0x52, 0x66,
	0xf0, 0x03, 0x65, 0xb0, 0x84, 0xc5, 0x3e, 0xac, 0x31, 0x88, 0xf6, 0x17, 0x8a, 0xb6, 0x80, 0x5b,
	0x23, 0xf1, 0x61, 0x37, 0x8a, 0x06, 0x41, 0x9c, 0x98, 0x74, 0xae, 0x83, 0x44, 0x25, 0x68, 0x28,
	0xe4, 0x52, 0xff, 0x66, 0x45, 0x11, 0x7f, 0x94, 0xaf, 0xb5, 0x23, 0x1e, 0x9c, 0xe2, 0x87, 0x6c,
	0xc6, 0x94, 0xcd, 0x3b, 0xbc, 0xac, 0xaf, 0xc5, 0xbd, 0xee, 0x3c, 0x9b, 0xe8, 0x2d, 0x29, 0x39,
	0x94, 0xd2, 0x69, 0x2e, 0xd6, 0x63, 0x71, 0x6b, 0x91, 0x46, 0x02, 0x2e, 0x25, 0xd0, 0x4e, 0x52,
	0xfe, 0xf3, 0xd8, 0xf6, 0x82, 0xa9, 0xaf, 0x93, 0xd6, 0x6a, 0x68, 0x0a, 0xfd, 0x0e, 0x2f, 0xeb,
	0x4b, 0x21, 0x5b, 0x3d, 0x90, 0xc0, 0x84, 0x12, 0x58, 0xca, 0x53, 0xe6, 0xd1, 0x0c, 0xa3, 0x55,
	0xe1, 0x32, 0x56, 0x86, 0x9e, 0x52, 0xe8, 0x76, 0x12, 0xb7, 0xd2, 0x2a, 0x81, 0x40, 0x87, 0x14,
	0xa8, 0x09, 0x43, 0x7f, 0xc7, 0xa8, 0xb9, 0x3e, 0x0e, 0xcd, 0x6c, 0xcf, 0xad, 0x6c, 0x2d, 0x8f,
	0xf5, 0x5b, 0x49, 0xe8, 0x57, 0x09, 0xe8, 0xff, 0x95, 0xf5, 0x1b, 0x30, 0xbe, 0xbd, 0x80, 0x30,
	0x70, 0xab, 0x21, 0x66, 0x14, 0x62, 0x29, 0x6f, 0x6d, 0x0a, 0xab, 0xc1, 0x21, 0x90, 0x4f, 0x81,
	0x5a, 0x18, 0xf4, 0x59, 0x15, 0x7d, 0xfa, 0xb8, 0x16, 0x6d, 0x4e, 0xd1, 0x4e, 0xf1, 0xc0, 0x59,
	0xbb, 0xc0, 0x22, 0x62, 0x40, 0x11, 0x5b, 0x39, 0xba, 0xff, 0x7b, 0x41, 0x2d, 0x50, 0x48, 0x81,
	0x9a, 0x30, 0x26, 0x38, 0x43, 0x90, 0x8c, 0x78, 0x82, 0x17, 0x00, 0x6e, 0x32, 0x3b, 0xb1, 0xe7,
	0x96, 0x2a, 0x7f, 0x23, 0x95, 0x3a, 0x88, 0xf9, 0x07, 0x00, 0x0a, 0x86, 0xe7, 0x5f, 0x66, 0x42,
	0x1d, 0xbf, 0x47, 0x79, 0x0c, 0xc7, 0xac, 0x5e, 0x00, 0xb8, 0xc3, 0xa4, 0x9e, 0x2b, 0x13, 0xbe,
	0xc3, 0xa4, 0x9e, 0x8b, 0x78, 0x34, 0xa5, 0xa7, 0xda, 0xf0, 0x3b, 0x29, 0xdf, 0x5e, 0x6b, 0x60,
	0x36, 0x41, 0x86, 0x2a, 0x39, 0x2c, 0x13, 0x3b, 0xa2, 0xc4, 0x16, 0x70, 0xf8, 0xaa, 0xa6, 0xef,
	0x31, 0x4f, 0x9b, 0x26, 0x8e, 0x4a, 0x8f, 0xb4, 0xf2, 0x17, 0xb4, 0xdf, 0x92, 0x76, 0x2b, 0x87,
	0x1b, 0x93, 0x29, 0x71, 0x94, 0xe0, 0x84, 0xef, 0xa7, 0x75, 0xd4, 0xfa, 0x42, 0xdc, 0xf1, 0x7c,
	0x5f, 0x4f, 0x95, 0xbf, 0xeb, 0x8d, 0x8d, 0x32, 0x27, 0xa5, 0xfc, 0xdf, 0x49, 0x7e, 0x19, 0x8d,
	0x33, 0xa4, 0x4e, 0x21, 0xc8, 0x3f, 0x28, 0xc8, 0x22, 0x81, 0xbb, 0x54, 0x9c, 0x28, 0x67, 0x76,
	0x60, 0x94, 0x53, 0xe9, 0xcb, 0x7f, 0x52, 0x8c, 0x36, 0x0a, 0x35, 0x2f, 0x61, 0x68, 0xff, 0x8b,
	0x6b, 0x5e, 0x03, 0xad, 0x67, 0x62, 0x5d, 0xbf, 0x4d, 0x8c, 0xb2, 0x4f, 0xe2, 0x44, 0xcf, 0x07,
	0xc1, 0x24, 0x94, 0xff, 0xee, 0xac, 0x6c, 0xac, 0x3e, 0x7a, 0x7f, 0xb3, 0xfa, 0x0f, 0xc6, 0xe6,
	0x76, 0xdd, 0x69, 0xd4, 0x7c, 0x0b, 0x87, 0xdc, 0x98, 0x86, 0x1a, 0x2f, 0xf0, 0x7f, 0xf8, 0x90,
	0xab, 0x40, 0x0f, 0xff, 0xbb, 0x2a, 0xd6, 0x1b, 0x32, 0x68, 0xd8, 0x58, 0x1b, 0xdc, 0x4e, 0x30,
	0x82, 0xe2, 0xda, 0xce, 0x5e, 0xe1, 0x86, 0x5d, 0xc6, 0xa3, 0x61, 0x1b, 0x1c, 0xbe, 0xf2, 0x0c,
	0x37, 0xec, 0x22, 0x83, 0xe1, 0x13, 0x53, 0xe4, 0x6e, 0x14, 0xd5, 0x02, 0x9d, 0xe5, 0xe1, 0xd3,
	0x4a, 0xa2, 0xe5, 0xaa, 0x04, 0x42, 0x9c, 0xe3, 0xe1, 0xd3, 0x80, 0xad, 0x2d, 0x71, 0x9f, 0xa1,
	0xa1, 0xf1, 0x8e, 0x54, 0xa2, 0x9b, 0x61, 0xce, 0x53, 0x98, 0x53, 0x7d, 0x70, 0xf8, 0xb6, 0xf0,
	0x08, 0x7a, 0x81, 0x82, 0x2e, 0x61, 0xf1, 0x6d, 0x47, 0x3a, 0x70, 0x43, 0xd3, 0x0c, 0x7a, 0x91,
	0xbf, 0xad, 0x95, 0xc4, 0xb7, 0x55, 0x09, 0x84, 0xb9, 0xc4, 0xdf, 0xd6, 0x80, 0x91, 0x57, 0xc4,
	0xbf, 0xe6, 0x9b, 0x01, 0x2e, 0xf3, 0xa5, 0xa0, 0x9d, 0x45, 0x9b, 0xd6, 0x18, 0x84, 0x10, 0xdc,
	0xa6, 0x4d, 0x1c, 0x2d, 0xe7, 0xd7, 0x77, 0xc0, 0x2a, 0x69, 0x37, 0x50, 0x5c, 0x10, 0xfd, 0x7c,
	0xb5, 0xd7, 0xf8, 0xfa, 0x99, 0xdb, 0xd8, 0x4f, 0x93, 0x7c, 0x70, 0x8e, 0x1a, 0xfb, 0xe9, 0x0a,
	0xef, 0xa7, 0x65, 0x3c, 0xf6, 0x53, 0x83, 0x43, 0x84, 0xab, 0xbc, 0x9f, 0x16, 0x19, 0xf8, 0xfb,
	0xde, 0xb8, 0xd7, 0xa8, 0xc7, 0x3a, 0x45, 0x69, 0x61, 0xf0, 0x83, 0xa2, 0x40, 0xa1, 0x7c, 0x8d,
	0x7f, 0x50, 0x54, 0x31, 0xd6, 0x0c, 0x66, 0xda, 0xd4, 0x34, 0xaf, 0xe7, 0x9a, 0x4d, 0x86, 0x35,
	0x33, 0x14, 0x9a, 0x56, 0xae, 0x59, 0x62, 0xb8, 0x58, 0x98, 0x30, 0x4c, 0xfa, 0x9e, 0xd9, 0x55,
	0x71, 0xc2, 0xbf, 0x7d, 0x70, 0x57, 0x2f, 0xf5, 0x6f, 0xf0, 0xc5, 0xe2, 0x74, 0x2f, 0xd4, 0xb6,
	0xd5, 0x03, 0x71, 0x6f, 0xf2, 0xc5, 0x62, 0x19, 0x8f, 0x0b, 0x2e, 0xef, 0xdc, 0x53, 0xb2, 0xb8,
	0xc5, 0x17, 0xdc, 0x77, 0xf9, 0xe1, 0xe0, 0x5d, 0xe2, 0x83, 0x4c, 0x6e, 0xf3, 0x05, 0x77, 0xb9,
	0x07, 0xea, 0xe1, 0xf2, 0x7f, 0x33, 0xcb, 0x32, 0xb9, 0xc3, 0xf5, 0x38, 0xdd, 0x0b, 0xf5, 0x68,
	0xf5, 0x40, 0x16, 0x92, 0xeb, 0xb1, 0x8c, 0x47, 0x5f, 0x8c, 0xf9, 0x3f, 0xbf, 0x32, 0xea, 0x7b,
	0x7c, 0xd4, 0x35, 0x71, 0xfc, 0xa8, 0xc9, 0x30, 0x28, 0xdf, 0xe5, 0x1f, 0x3d, 0x25, 0x82, 0x2e,
	0x9e, 0xd1, 0x6f, 0xe9, 0x52, 0xea, 0x1e, 0x5f, 0x0a, 0x1a, 0x30, 0x8e, 0x6d, 0x86, 0x20, 0x74,
	0x9f, 0x8f, 0xed, 0x02, 0xd8, 0x5a, 0xfd, 0xfe, 0xf2, 0xe6, 0xe6, 0xa7, 0x3c, 0xf5, 0xff, 0x1f,
	0x00, 0x00, 0xff, 0xff, 0x0d, 0x10, 0x10, 0x05, 0xd3, 0x16, 0x00, 0x00,
}
