// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fpfresh.proto

package mmproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FPFresh struct {
	BaseReq              *BaseRequest `protobuf:"bytes,1,req,name=baseReq" json:"baseReq,omitempty"`
	SessKey              []byte       `protobuf:"bytes,2,req,name=sessKey" json:"sessKey,omitempty"`
	Ztdata               *ZTData      `protobuf:"bytes,3,req,name=ztdata" json:"ztdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FPFresh) Reset()         { *m = FPFresh{} }
func (m *FPFresh) String() string { return proto.CompactTextString(m) }
func (*FPFresh) ProtoMessage()    {}
func (*FPFresh) Descriptor() ([]byte, []int) {
	return fileDescriptor_f554f0ba3c0431bb, []int{0}
}

func (m *FPFresh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FPFresh.Unmarshal(m, b)
}
func (m *FPFresh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FPFresh.Marshal(b, m, deterministic)
}
func (m *FPFresh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FPFresh.Merge(m, src)
}
func (m *FPFresh) XXX_Size() int {
	return xxx_messageInfo_FPFresh.Size(m)
}
func (m *FPFresh) XXX_DiscardUnknown() {
	xxx_messageInfo_FPFresh.DiscardUnknown(m)
}

var xxx_messageInfo_FPFresh proto.InternalMessageInfo

func (m *FPFresh) GetBaseReq() *BaseRequest {
	if m != nil {
		return m.BaseReq
	}
	return nil
}

func (m *FPFresh) GetSessKey() []byte {
	if m != nil {
		return m.SessKey
	}
	return nil
}

func (m *FPFresh) GetZtdata() *ZTData {
	if m != nil {
		return m.Ztdata
	}
	return nil
}

func init() {
	proto.RegisterType((*FPFresh)(nil), "mmproto.FPFresh")
}

func init() {
	proto.RegisterFile("fpfresh.proto", fileDescriptor_f554f0ba3c0431bb)
}

var fileDescriptor_f554f0ba3c0431bb = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2b, 0x48, 0x2b,
	0x4a, 0x2d, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xcd, 0x05, 0x33, 0xa4,
	0xb8, 0x92, 0x12, 0x8b, 0x53, 0x21, 0x82, 0x4a, 0x35, 0x5c, 0xec, 0x6e, 0x01, 0x6e, 0x20, 0x55,
	0x42, 0x7a, 0x5c, 0xec, 0x20, 0x89, 0xa0, 0xd4, 0x42, 0x09, 0x46, 0x05, 0x26, 0x0d, 0x6e, 0x23,
	0x11, 0x3d, 0xa8, 0x0e, 0x3d, 0x27, 0x88, 0x78, 0x69, 0x6a, 0x71, 0x49, 0x10, 0x4c, 0x91, 0x90,
	0x04, 0x17, 0x7b, 0x71, 0x6a, 0x71, 0xb1, 0x77, 0x6a, 0xa5, 0x04, 0x93, 0x02, 0x93, 0x06, 0x4f,
	0x10, 0x8c, 0x2b, 0xa4, 0xce, 0xc5, 0x56, 0x55, 0x92, 0x92, 0x58, 0x92, 0x28, 0xc1, 0x0c, 0x36,
	0x88, 0x1f, 0x6e, 0x50, 0x54, 0x88, 0x4b, 0x62, 0x49, 0x62, 0x10, 0x54, 0x1a, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x94, 0xe3, 0xc5, 0x83, 0xa2, 0x00, 0x00, 0x00,
}
