// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hybridecdh.proto

package mmproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SecKey struct {
	Nid                  *int32   `protobuf:"varint,1,req,name=nid" json:"nid,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecKey) Reset()         { *m = SecKey{} }
func (m *SecKey) String() string { return proto.CompactTextString(m) }
func (*SecKey) ProtoMessage()    {}
func (*SecKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c06398fabab09a9, []int{0}
}

func (m *SecKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecKey.Unmarshal(m, b)
}
func (m *SecKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecKey.Marshal(b, m, deterministic)
}
func (m *SecKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecKey.Merge(m, src)
}
func (m *SecKey) XXX_Size() int {
	return xxx_messageInfo_SecKey.Size(m)
}
func (m *SecKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SecKey.DiscardUnknown(m)
}

var xxx_messageInfo_SecKey proto.InternalMessageInfo

func (m *SecKey) GetNid() int32 {
	if m != nil && m.Nid != nil {
		return *m.Nid
	}
	return 0
}

func (m *SecKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type HybridEcdhReq struct {
	Version              *int32   `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	SecKey               *SecKey  `protobuf:"bytes,2,req,name=secKey" json:"secKey,omitempty"`
	Gcm1                 []byte   `protobuf:"bytes,3,req,name=gcm1" json:"gcm1,omitempty"`
	Autokey              []byte   `protobuf:"bytes,4,req,name=autokey" json:"autokey,omitempty"`
	Gcm2                 []byte   `protobuf:"bytes,5,req,name=gcm2" json:"gcm2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HybridEcdhReq) Reset()         { *m = HybridEcdhReq{} }
func (m *HybridEcdhReq) String() string { return proto.CompactTextString(m) }
func (*HybridEcdhReq) ProtoMessage()    {}
func (*HybridEcdhReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c06398fabab09a9, []int{1}
}

func (m *HybridEcdhReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HybridEcdhReq.Unmarshal(m, b)
}
func (m *HybridEcdhReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HybridEcdhReq.Marshal(b, m, deterministic)
}
func (m *HybridEcdhReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HybridEcdhReq.Merge(m, src)
}
func (m *HybridEcdhReq) XXX_Size() int {
	return xxx_messageInfo_HybridEcdhReq.Size(m)
}
func (m *HybridEcdhReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HybridEcdhReq.DiscardUnknown(m)
}

var xxx_messageInfo_HybridEcdhReq proto.InternalMessageInfo

func (m *HybridEcdhReq) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *HybridEcdhReq) GetSecKey() *SecKey {
	if m != nil {
		return m.SecKey
	}
	return nil
}

func (m *HybridEcdhReq) GetGcm1() []byte {
	if m != nil {
		return m.Gcm1
	}
	return nil
}

func (m *HybridEcdhReq) GetAutokey() []byte {
	if m != nil {
		return m.Autokey
	}
	return nil
}

func (m *HybridEcdhReq) GetGcm2() []byte {
	if m != nil {
		return m.Gcm2
	}
	return nil
}

type HybridEcdhResp struct {
	SecKey               *SecKey  `protobuf:"bytes,1,req,name=secKey" json:"secKey,omitempty"`
	Version              *int32   `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	Gcm1                 []byte   `protobuf:"bytes,3,req,name=gcm1" json:"gcm1,omitempty"`
	Gcm2                 []byte   `protobuf:"bytes,4,req,name=gcm2" json:"gcm2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HybridEcdhResp) Reset()         { *m = HybridEcdhResp{} }
func (m *HybridEcdhResp) String() string { return proto.CompactTextString(m) }
func (*HybridEcdhResp) ProtoMessage()    {}
func (*HybridEcdhResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c06398fabab09a9, []int{2}
}

func (m *HybridEcdhResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HybridEcdhResp.Unmarshal(m, b)
}
func (m *HybridEcdhResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HybridEcdhResp.Marshal(b, m, deterministic)
}
func (m *HybridEcdhResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HybridEcdhResp.Merge(m, src)
}
func (m *HybridEcdhResp) XXX_Size() int {
	return xxx_messageInfo_HybridEcdhResp.Size(m)
}
func (m *HybridEcdhResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HybridEcdhResp.DiscardUnknown(m)
}

var xxx_messageInfo_HybridEcdhResp proto.InternalMessageInfo

func (m *HybridEcdhResp) GetSecKey() *SecKey {
	if m != nil {
		return m.SecKey
	}
	return nil
}

func (m *HybridEcdhResp) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *HybridEcdhResp) GetGcm1() []byte {
	if m != nil {
		return m.Gcm1
	}
	return nil
}

func (m *HybridEcdhResp) GetGcm2() []byte {
	if m != nil {
		return m.Gcm2
	}
	return nil
}

func init() {
	proto.RegisterType((*SecKey)(nil), "mmproto.SecKey")
	proto.RegisterType((*HybridEcdhReq)(nil), "mmproto.HybridEcdhReq")
	proto.RegisterType((*HybridEcdhResp)(nil), "mmproto.HybridEcdhResp")
}

func init() {
	proto.RegisterFile("hybridecdh.proto", fileDescriptor_4c06398fabab09a9)
}

var fileDescriptor_4c06398fabab09a9 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xa8, 0x4c, 0x2a,
	0xca, 0x4c, 0x49, 0x4d, 0x4e, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xcd,
	0x05, 0x33, 0x94, 0x74, 0xb8, 0xd8, 0x82, 0x53, 0x93, 0xbd, 0x53, 0x2b, 0x85, 0x04, 0xb8, 0x98,
	0xf3, 0x32, 0x53, 0x24, 0x18, 0x15, 0x98, 0x34, 0x58, 0x83, 0x40, 0x4c, 0x90, 0x48, 0x76, 0x6a,
	0xa5, 0x04, 0x93, 0x02, 0x93, 0x06, 0x4f, 0x10, 0x88, 0xa9, 0x34, 0x85, 0x91, 0x8b, 0xd7, 0x03,
	0x6c, 0x96, 0x6b, 0x72, 0x4a, 0x46, 0x50, 0x6a, 0xa1, 0x90, 0x04, 0x17, 0x7b, 0x59, 0x6a, 0x51,
	0x71, 0x66, 0x7e, 0x1e, 0x54, 0x27, 0x8c, 0x2b, 0xa4, 0xce, 0xc5, 0x56, 0x0c, 0x36, 0x19, 0x6c,
	0x00, 0xb7, 0x11, 0xbf, 0x1e, 0xd4, 0x4e, 0x3d, 0x88, 0x85, 0x41, 0x50, 0x69, 0x21, 0x21, 0x2e,
	0x96, 0xf4, 0xe4, 0x5c, 0x43, 0x09, 0x66, 0xb0, 0x3d, 0x60, 0x36, 0xc8, 0xd8, 0xc4, 0xd2, 0x92,
	0x7c, 0x90, 0xf5, 0x2c, 0x60, 0x61, 0x18, 0x17, 0xaa, 0xda, 0x48, 0x82, 0x15, 0xae, 0xda, 0x48,
	0xa9, 0x9a, 0x8b, 0x0f, 0xd9, 0x55, 0xc5, 0x05, 0x48, 0x96, 0x33, 0xe2, 0xb7, 0x1c, 0xc9, 0xfd,
	0x4c, 0xa8, 0xee, 0xc7, 0xe6, 0x2c, 0x98, 0xe5, 0x2c, 0x08, 0xcb, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x9e, 0xd5, 0x09, 0xdb, 0x5d, 0x01, 0x00, 0x00,
}
