// Code generated by protoc-gen-go. DO NOT EDIT.
// source: secmanualauth.proto

package mmproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WTLoginImgReqInfo struct {
	ImgSid               *string           `protobuf:"bytes,1,opt,name=ImgSid" json:"ImgSid,omitempty"`
	ImgCode              *string           `protobuf:"bytes,2,opt,name=ImgCode" json:"ImgCode,omitempty"`
	ImgEncryptKey        *string           `protobuf:"bytes,3,opt,name=ImgEncryptKey" json:"ImgEncryptKey,omitempty"`
	KSid                 *SKBuiltinBuffert `protobuf:"bytes,4,req,name=KSid" json:"KSid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WTLoginImgReqInfo) Reset()         { *m = WTLoginImgReqInfo{} }
func (m *WTLoginImgReqInfo) String() string { return proto.CompactTextString(m) }
func (*WTLoginImgReqInfo) ProtoMessage()    {}
func (*WTLoginImgReqInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{0}
}

func (m *WTLoginImgReqInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WTLoginImgReqInfo.Unmarshal(m, b)
}
func (m *WTLoginImgReqInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WTLoginImgReqInfo.Marshal(b, m, deterministic)
}
func (m *WTLoginImgReqInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WTLoginImgReqInfo.Merge(m, src)
}
func (m *WTLoginImgReqInfo) XXX_Size() int {
	return xxx_messageInfo_WTLoginImgReqInfo.Size(m)
}
func (m *WTLoginImgReqInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WTLoginImgReqInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WTLoginImgReqInfo proto.InternalMessageInfo

func (m *WTLoginImgReqInfo) GetImgSid() string {
	if m != nil && m.ImgSid != nil {
		return *m.ImgSid
	}
	return ""
}

func (m *WTLoginImgReqInfo) GetImgCode() string {
	if m != nil && m.ImgCode != nil {
		return *m.ImgCode
	}
	return ""
}

func (m *WTLoginImgReqInfo) GetImgEncryptKey() string {
	if m != nil && m.ImgEncryptKey != nil {
		return *m.ImgEncryptKey
	}
	return ""
}

func (m *WTLoginImgReqInfo) GetKSid() *SKBuiltinBuffert {
	if m != nil {
		return m.KSid
	}
	return nil
}

type WxVerifyCodeReqInfo struct {
	VerifySignature      *string  `protobuf:"bytes,1,opt,name=VerifySignature" json:"VerifySignature,omitempty"`
	VerifyContent        *string  `protobuf:"bytes,2,opt,name=VerifyContent" json:"VerifyContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxVerifyCodeReqInfo) Reset()         { *m = WxVerifyCodeReqInfo{} }
func (m *WxVerifyCodeReqInfo) String() string { return proto.CompactTextString(m) }
func (*WxVerifyCodeReqInfo) ProtoMessage()    {}
func (*WxVerifyCodeReqInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{1}
}

func (m *WxVerifyCodeReqInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxVerifyCodeReqInfo.Unmarshal(m, b)
}
func (m *WxVerifyCodeReqInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxVerifyCodeReqInfo.Marshal(b, m, deterministic)
}
func (m *WxVerifyCodeReqInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxVerifyCodeReqInfo.Merge(m, src)
}
func (m *WxVerifyCodeReqInfo) XXX_Size() int {
	return xxx_messageInfo_WxVerifyCodeReqInfo.Size(m)
}
func (m *WxVerifyCodeReqInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WxVerifyCodeReqInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WxVerifyCodeReqInfo proto.InternalMessageInfo

func (m *WxVerifyCodeReqInfo) GetVerifySignature() string {
	if m != nil && m.VerifySignature != nil {
		return *m.VerifySignature
	}
	return ""
}

func (m *WxVerifyCodeReqInfo) GetVerifyContent() string {
	if m != nil && m.VerifyContent != nil {
		return *m.VerifyContent
	}
	return ""
}

type BaseAuthReqInfo struct {
	WTLoginReqBuff       *SKBuiltinBuffert    `protobuf:"bytes,1,opt,name=WTLoginReqBuff" json:"WTLoginReqBuff,omitempty"`
	WTLoginImgReqInfo    *WTLoginImgReqInfo   `protobuf:"bytes,2,opt,name=WTLoginImgReqInfo" json:"WTLoginImgReqInfo,omitempty"`
	WxVerifyCodeReqInfo  *WxVerifyCodeReqInfo `protobuf:"bytes,3,opt,name=WxVerifyCodeReqInfo" json:"WxVerifyCodeReqInfo,omitempty"`
	CliDBEncryptKey      *SKBuiltinBuffert    `protobuf:"bytes,4,opt,name=CliDBEncryptKey" json:"CliDBEncryptKey,omitempty"`
	CliDBEncryptInfo     *SKBuiltinBuffert    `protobuf:"bytes,5,opt,name=CliDBEncryptInfo" json:"CliDBEncryptInfo,omitempty"`
	AuthReqFlag          *uint32              `protobuf:"varint,6,opt,name=AuthReqFlag" json:"AuthReqFlag,omitempty"`
	AuthTicket           *string              `protobuf:"bytes,7,opt,name=AuthTicket" json:"AuthTicket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BaseAuthReqInfo) Reset()         { *m = BaseAuthReqInfo{} }
func (m *BaseAuthReqInfo) String() string { return proto.CompactTextString(m) }
func (*BaseAuthReqInfo) ProtoMessage()    {}
func (*BaseAuthReqInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{2}
}

func (m *BaseAuthReqInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseAuthReqInfo.Unmarshal(m, b)
}
func (m *BaseAuthReqInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseAuthReqInfo.Marshal(b, m, deterministic)
}
func (m *BaseAuthReqInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseAuthReqInfo.Merge(m, src)
}
func (m *BaseAuthReqInfo) XXX_Size() int {
	return xxx_messageInfo_BaseAuthReqInfo.Size(m)
}
func (m *BaseAuthReqInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseAuthReqInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseAuthReqInfo proto.InternalMessageInfo

func (m *BaseAuthReqInfo) GetWTLoginReqBuff() *SKBuiltinBuffert {
	if m != nil {
		return m.WTLoginReqBuff
	}
	return nil
}

func (m *BaseAuthReqInfo) GetWTLoginImgReqInfo() *WTLoginImgReqInfo {
	if m != nil {
		return m.WTLoginImgReqInfo
	}
	return nil
}

func (m *BaseAuthReqInfo) GetWxVerifyCodeReqInfo() *WxVerifyCodeReqInfo {
	if m != nil {
		return m.WxVerifyCodeReqInfo
	}
	return nil
}

func (m *BaseAuthReqInfo) GetCliDBEncryptKey() *SKBuiltinBuffert {
	if m != nil {
		return m.CliDBEncryptKey
	}
	return nil
}

func (m *BaseAuthReqInfo) GetCliDBEncryptInfo() *SKBuiltinBuffert {
	if m != nil {
		return m.CliDBEncryptInfo
	}
	return nil
}

func (m *BaseAuthReqInfo) GetAuthReqFlag() uint32 {
	if m != nil && m.AuthReqFlag != nil {
		return *m.AuthReqFlag
	}
	return 0
}

func (m *BaseAuthReqInfo) GetAuthTicket() string {
	if m != nil && m.AuthTicket != nil {
		return *m.AuthTicket
	}
	return ""
}

type ManualAuthRsaReqData struct {
	RandomEncryKey       *SKBuiltinBuffert `protobuf:"bytes,1,req,name=RandomEncryKey" json:"RandomEncryKey,omitempty"`
	CliPubECDHKey        *ECDHKey          `protobuf:"bytes,2,req,name=CliPubECDHKey" json:"CliPubECDHKey,omitempty"`
	UserName             *string           `protobuf:"bytes,3,opt,name=UserName" json:"UserName,omitempty"`
	Pwd                  *string           `protobuf:"bytes,4,opt,name=Pwd" json:"Pwd,omitempty"`
	Pwd2                 *string           `protobuf:"bytes,5,opt,name=Pwd2" json:"Pwd2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ManualAuthRsaReqData) Reset()         { *m = ManualAuthRsaReqData{} }
func (m *ManualAuthRsaReqData) String() string { return proto.CompactTextString(m) }
func (*ManualAuthRsaReqData) ProtoMessage()    {}
func (*ManualAuthRsaReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{3}
}

func (m *ManualAuthRsaReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManualAuthRsaReqData.Unmarshal(m, b)
}
func (m *ManualAuthRsaReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManualAuthRsaReqData.Marshal(b, m, deterministic)
}
func (m *ManualAuthRsaReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManualAuthRsaReqData.Merge(m, src)
}
func (m *ManualAuthRsaReqData) XXX_Size() int {
	return xxx_messageInfo_ManualAuthRsaReqData.Size(m)
}
func (m *ManualAuthRsaReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_ManualAuthRsaReqData.DiscardUnknown(m)
}

var xxx_messageInfo_ManualAuthRsaReqData proto.InternalMessageInfo

func (m *ManualAuthRsaReqData) GetRandomEncryKey() *SKBuiltinBuffert {
	if m != nil {
		return m.RandomEncryKey
	}
	return nil
}

func (m *ManualAuthRsaReqData) GetCliPubECDHKey() *ECDHKey {
	if m != nil {
		return m.CliPubECDHKey
	}
	return nil
}

func (m *ManualAuthRsaReqData) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *ManualAuthRsaReqData) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *ManualAuthRsaReqData) GetPwd2() string {
	if m != nil && m.Pwd2 != nil {
		return *m.Pwd2
	}
	return ""
}

type ManualAuthAesReqData struct {
	BaseRequest          *BaseRequest      `protobuf:"bytes,1,req,name=BaseRequest" json:"BaseRequest,omitempty"`
	BaseReqInfo          *BaseAuthReqInfo  `protobuf:"bytes,2,opt,name=BaseReqInfo" json:"BaseReqInfo,omitempty"`
	Imei                 *string           `protobuf:"bytes,3,opt,name=Imei" json:"Imei,omitempty"`
	SoftType             *string           `protobuf:"bytes,4,opt,name=SoftType" json:"SoftType,omitempty"`
	BuiltinIPSeq         *uint32           `protobuf:"varint,5,req,name=BuiltinIPSeq" json:"BuiltinIPSeq,omitempty"`
	ClientSeqID          *string           `protobuf:"bytes,6,opt,name=ClientSeqID" json:"ClientSeqID,omitempty"`
	Signature            *string           `protobuf:"bytes,7,opt,name=Signature" json:"Signature,omitempty"`
	DeviceName           *string           `protobuf:"bytes,8,opt,name=DeviceName" json:"DeviceName,omitempty"`
	DeviceType           *string           `protobuf:"bytes,9,opt,name=DeviceType" json:"DeviceType,omitempty"`
	Language             *string           `protobuf:"bytes,10,opt,name=Language" json:"Language,omitempty"`
	TimeZone             *string           `protobuf:"bytes,11,opt,name=TimeZone" json:"TimeZone,omitempty"`
	Channel              *int32            `protobuf:"varint,13,opt,name=Channel" json:"Channel,omitempty"`
	TimeStamp            *uint32           `protobuf:"varint,14,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	DeviceBrand          *string           `protobuf:"bytes,15,opt,name=DeviceBrand" json:"DeviceBrand,omitempty"`
	DeviceModel          *string           `protobuf:"bytes,16,opt,name=DeviceModel" json:"DeviceModel,omitempty"`
	OSType               *string           `protobuf:"bytes,17,opt,name=OSType" json:"OSType,omitempty"`
	RealCountry          *string           `protobuf:"bytes,18,opt,name=RealCountry" json:"RealCountry,omitempty"`
	BundleID             *string           `protobuf:"bytes,19,opt,name=BundleID" json:"BundleID,omitempty"`
	AdSource             *string           `protobuf:"bytes,20,opt,name=AdSource" json:"AdSource,omitempty"`
	IPhoneVer            *string           `protobuf:"bytes,21,opt,name=IPhoneVer" json:"IPhoneVer,omitempty"`
	InputType            *uint32           `protobuf:"varint,22,req,name=InputType" json:"InputType,omitempty"`
	Clientcheckdat       *SKBuiltinBuffert `protobuf:"bytes,23,opt,name=Clientcheckdat" json:"Clientcheckdat,omitempty"`
	SpamData             *SpamData         `protobuf:"bytes,24,opt,name=spamData" json:"spamData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ManualAuthAesReqData) Reset()         { *m = ManualAuthAesReqData{} }
func (m *ManualAuthAesReqData) String() string { return proto.CompactTextString(m) }
func (*ManualAuthAesReqData) ProtoMessage()    {}
func (*ManualAuthAesReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{4}
}

func (m *ManualAuthAesReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManualAuthAesReqData.Unmarshal(m, b)
}
func (m *ManualAuthAesReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManualAuthAesReqData.Marshal(b, m, deterministic)
}
func (m *ManualAuthAesReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManualAuthAesReqData.Merge(m, src)
}
func (m *ManualAuthAesReqData) XXX_Size() int {
	return xxx_messageInfo_ManualAuthAesReqData.Size(m)
}
func (m *ManualAuthAesReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_ManualAuthAesReqData.DiscardUnknown(m)
}

var xxx_messageInfo_ManualAuthAesReqData proto.InternalMessageInfo

func (m *ManualAuthAesReqData) GetBaseRequest() *BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *ManualAuthAesReqData) GetBaseReqInfo() *BaseAuthReqInfo {
	if m != nil {
		return m.BaseReqInfo
	}
	return nil
}

func (m *ManualAuthAesReqData) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *ManualAuthAesReqData) GetSoftType() string {
	if m != nil && m.SoftType != nil {
		return *m.SoftType
	}
	return ""
}

func (m *ManualAuthAesReqData) GetBuiltinIPSeq() uint32 {
	if m != nil && m.BuiltinIPSeq != nil {
		return *m.BuiltinIPSeq
	}
	return 0
}

func (m *ManualAuthAesReqData) GetClientSeqID() string {
	if m != nil && m.ClientSeqID != nil {
		return *m.ClientSeqID
	}
	return ""
}

func (m *ManualAuthAesReqData) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *ManualAuthAesReqData) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *ManualAuthAesReqData) GetDeviceType() string {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return ""
}

func (m *ManualAuthAesReqData) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *ManualAuthAesReqData) GetTimeZone() string {
	if m != nil && m.TimeZone != nil {
		return *m.TimeZone
	}
	return ""
}

func (m *ManualAuthAesReqData) GetChannel() int32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return 0
}

func (m *ManualAuthAesReqData) GetTimeStamp() uint32 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *ManualAuthAesReqData) GetDeviceBrand() string {
	if m != nil && m.DeviceBrand != nil {
		return *m.DeviceBrand
	}
	return ""
}

func (m *ManualAuthAesReqData) GetDeviceModel() string {
	if m != nil && m.DeviceModel != nil {
		return *m.DeviceModel
	}
	return ""
}

func (m *ManualAuthAesReqData) GetOSType() string {
	if m != nil && m.OSType != nil {
		return *m.OSType
	}
	return ""
}

func (m *ManualAuthAesReqData) GetRealCountry() string {
	if m != nil && m.RealCountry != nil {
		return *m.RealCountry
	}
	return ""
}

func (m *ManualAuthAesReqData) GetBundleID() string {
	if m != nil && m.BundleID != nil {
		return *m.BundleID
	}
	return ""
}

func (m *ManualAuthAesReqData) GetAdSource() string {
	if m != nil && m.AdSource != nil {
		return *m.AdSource
	}
	return ""
}

func (m *ManualAuthAesReqData) GetIPhoneVer() string {
	if m != nil && m.IPhoneVer != nil {
		return *m.IPhoneVer
	}
	return ""
}

func (m *ManualAuthAesReqData) GetInputType() uint32 {
	if m != nil && m.InputType != nil {
		return *m.InputType
	}
	return 0
}

func (m *ManualAuthAesReqData) GetClientcheckdat() *SKBuiltinBuffert {
	if m != nil {
		return m.Clientcheckdat
	}
	return nil
}

func (m *ManualAuthAesReqData) GetSpamData() *SpamData {
	if m != nil {
		return m.SpamData
	}
	return nil
}

type ManualAuthRequest struct {
	RsaReqData           *ManualAuthRsaReqData `protobuf:"bytes,1,req,name=RsaReqData" json:"RsaReqData,omitempty"`
	AesReqData           *ManualAuthAesReqData `protobuf:"bytes,2,req,name=AesReqData" json:"AesReqData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ManualAuthRequest) Reset()         { *m = ManualAuthRequest{} }
func (m *ManualAuthRequest) String() string { return proto.CompactTextString(m) }
func (*ManualAuthRequest) ProtoMessage()    {}
func (*ManualAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{5}
}

func (m *ManualAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManualAuthRequest.Unmarshal(m, b)
}
func (m *ManualAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManualAuthRequest.Marshal(b, m, deterministic)
}
func (m *ManualAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManualAuthRequest.Merge(m, src)
}
func (m *ManualAuthRequest) XXX_Size() int {
	return xxx_messageInfo_ManualAuthRequest.Size(m)
}
func (m *ManualAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ManualAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ManualAuthRequest proto.InternalMessageInfo

func (m *ManualAuthRequest) GetRsaReqData() *ManualAuthRsaReqData {
	if m != nil {
		return m.RsaReqData
	}
	return nil
}

func (m *ManualAuthRequest) GetAesReqData() *ManualAuthAesReqData {
	if m != nil {
		return m.AesReqData
	}
	return nil
}

type Host struct {
	Origin               *string  `protobuf:"bytes,1,opt,name=Origin" json:"Origin,omitempty"`
	Substitute           *string  `protobuf:"bytes,2,opt,name=Substitute" json:"Substitute,omitempty"`
	Priority             *int32   `protobuf:"varint,3,opt,name=Priority" json:"Priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{6}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetOrigin() string {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return ""
}

func (m *Host) GetSubstitute() string {
	if m != nil && m.Substitute != nil {
		return *m.Substitute
	}
	return ""
}

func (m *Host) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

type HostList struct {
	Count                *uint32  `protobuf:"varint,1,req,name=Count" json:"Count,omitempty"`
	List                 []*Host  `protobuf:"bytes,2,rep,name=List" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostList) Reset()         { *m = HostList{} }
func (m *HostList) String() string { return proto.CompactTextString(m) }
func (*HostList) ProtoMessage()    {}
func (*HostList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{7}
}

func (m *HostList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostList.Unmarshal(m, b)
}
func (m *HostList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostList.Marshal(b, m, deterministic)
}
func (m *HostList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostList.Merge(m, src)
}
func (m *HostList) XXX_Size() int {
	return xxx_messageInfo_HostList.Size(m)
}
func (m *HostList) XXX_DiscardUnknown() {
	xxx_messageInfo_HostList.DiscardUnknown(m)
}

var xxx_messageInfo_HostList proto.InternalMessageInfo

func (m *HostList) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *HostList) GetList() []*Host {
	if m != nil {
		return m.List
	}
	return nil
}

type NetworkControl struct {
	PortList             *string  `protobuf:"bytes,1,opt,name=PortList" json:"PortList,omitempty"`
	TimeoutList          *string  `protobuf:"bytes,2,opt,name=TimeoutList" json:"TimeoutList,omitempty"`
	MinNoopInterval      *uint32  `protobuf:"varint,3,opt,name=MinNoopInterval" json:"MinNoopInterval,omitempty"`
	MaxNoopInterval      *uint32  `protobuf:"varint,4,opt,name=MaxNoopInterval" json:"MaxNoopInterval,omitempty"`
	TypingInterval       *int32   `protobuf:"varint,5,opt,name=TypingInterval" json:"TypingInterval,omitempty"`
	NoopIntervalTime     *int32   `protobuf:"varint,7,opt,name=NoopIntervalTime" json:"NoopIntervalTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkControl) Reset()         { *m = NetworkControl{} }
func (m *NetworkControl) String() string { return proto.CompactTextString(m) }
func (*NetworkControl) ProtoMessage()    {}
func (*NetworkControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{8}
}

func (m *NetworkControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkControl.Unmarshal(m, b)
}
func (m *NetworkControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkControl.Marshal(b, m, deterministic)
}
func (m *NetworkControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkControl.Merge(m, src)
}
func (m *NetworkControl) XXX_Size() int {
	return xxx_messageInfo_NetworkControl.Size(m)
}
func (m *NetworkControl) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkControl.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkControl proto.InternalMessageInfo

func (m *NetworkControl) GetPortList() string {
	if m != nil && m.PortList != nil {
		return *m.PortList
	}
	return ""
}

func (m *NetworkControl) GetTimeoutList() string {
	if m != nil && m.TimeoutList != nil {
		return *m.TimeoutList
	}
	return ""
}

func (m *NetworkControl) GetMinNoopInterval() uint32 {
	if m != nil && m.MinNoopInterval != nil {
		return *m.MinNoopInterval
	}
	return 0
}

func (m *NetworkControl) GetMaxNoopInterval() uint32 {
	if m != nil && m.MaxNoopInterval != nil {
		return *m.MaxNoopInterval
	}
	return 0
}

func (m *NetworkControl) GetTypingInterval() int32 {
	if m != nil && m.TypingInterval != nil {
		return *m.TypingInterval
	}
	return 0
}

func (m *NetworkControl) GetNoopIntervalTime() int32 {
	if m != nil && m.NoopIntervalTime != nil {
		return *m.NoopIntervalTime
	}
	return 0
}

type BuiltinIP struct {
	Type                 *uint32  `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Port                 *uint32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	IP                   []byte   `protobuf:"bytes,3,opt,name=IP" json:"IP,omitempty"`
	Domain               []byte   `protobuf:"bytes,4,opt,name=Domain" json:"Domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuiltinIP) Reset()         { *m = BuiltinIP{} }
func (m *BuiltinIP) String() string { return proto.CompactTextString(m) }
func (*BuiltinIP) ProtoMessage()    {}
func (*BuiltinIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{9}
}

func (m *BuiltinIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinIP.Unmarshal(m, b)
}
func (m *BuiltinIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinIP.Marshal(b, m, deterministic)
}
func (m *BuiltinIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinIP.Merge(m, src)
}
func (m *BuiltinIP) XXX_Size() int {
	return xxx_messageInfo_BuiltinIP.Size(m)
}
func (m *BuiltinIP) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinIP.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinIP proto.InternalMessageInfo

func (m *BuiltinIP) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *BuiltinIP) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *BuiltinIP) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *BuiltinIP) GetDomain() []byte {
	if m != nil {
		return m.Domain
	}
	return nil
}

type AcctSectResp struct {
	UserName             *string  `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	NickName             *string  `protobuf:"bytes,2,opt,name=NickName" json:"NickName,omitempty"`
	BindUin              *uint32  `protobuf:"varint,3,req,name=BindUin" json:"BindUin,omitempty"`
	BindEmail            *string  `protobuf:"bytes,4,opt,name=BindEmail" json:"BindEmail,omitempty"`
	BindMobile           *string  `protobuf:"bytes,5,opt,name=BindMobile" json:"BindMobile,omitempty"`
	Alias                *string  `protobuf:"bytes,6,opt,name=Alias" json:"Alias,omitempty"`
	Status               *uint32  `protobuf:"varint,8,req,name=Status" json:"Status,omitempty"`
	PluginFlag           *uint32  `protobuf:"varint,9,opt,name=PluginFlag" json:"PluginFlag,omitempty"`
	RegType              *uint32  `protobuf:"varint,10,opt,name=RegType" json:"RegType,omitempty"`
	DeviceInfoXml        *string  `protobuf:"bytes,11,opt,name=DeviceInfoXml" json:"DeviceInfoXml,omitempty"`
	SafeDevice           *uint32  `protobuf:"varint,12,opt,name=SafeDevice" json:"SafeDevice,omitempty"`
	OfficialUserName     *string  `protobuf:"bytes,13,opt,name=OfficialUserName" json:"OfficialUserName,omitempty"`
	OfficialNickName     *string  `protobuf:"bytes,14,opt,name=OfficialNickName" json:"OfficialNickName,omitempty"`
	PushMailStatus       *uint32  `protobuf:"varint,15,opt,name=PushMailStatus" json:"PushMailStatus,omitempty"`
	FSURL                *string  `protobuf:"bytes,16,opt,name=FSURL" json:"FSURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcctSectResp) Reset()         { *m = AcctSectResp{} }
func (m *AcctSectResp) String() string { return proto.CompactTextString(m) }
func (*AcctSectResp) ProtoMessage()    {}
func (*AcctSectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{10}
}

func (m *AcctSectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcctSectResp.Unmarshal(m, b)
}
func (m *AcctSectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcctSectResp.Marshal(b, m, deterministic)
}
func (m *AcctSectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcctSectResp.Merge(m, src)
}
func (m *AcctSectResp) XXX_Size() int {
	return xxx_messageInfo_AcctSectResp.Size(m)
}
func (m *AcctSectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AcctSectResp.DiscardUnknown(m)
}

var xxx_messageInfo_AcctSectResp proto.InternalMessageInfo

func (m *AcctSectResp) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *AcctSectResp) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *AcctSectResp) GetBindUin() uint32 {
	if m != nil && m.BindUin != nil {
		return *m.BindUin
	}
	return 0
}

func (m *AcctSectResp) GetBindEmail() string {
	if m != nil && m.BindEmail != nil {
		return *m.BindEmail
	}
	return ""
}

func (m *AcctSectResp) GetBindMobile() string {
	if m != nil && m.BindMobile != nil {
		return *m.BindMobile
	}
	return ""
}

func (m *AcctSectResp) GetAlias() string {
	if m != nil && m.Alias != nil {
		return *m.Alias
	}
	return ""
}

func (m *AcctSectResp) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *AcctSectResp) GetPluginFlag() uint32 {
	if m != nil && m.PluginFlag != nil {
		return *m.PluginFlag
	}
	return 0
}

func (m *AcctSectResp) GetRegType() uint32 {
	if m != nil && m.RegType != nil {
		return *m.RegType
	}
	return 0
}

func (m *AcctSectResp) GetDeviceInfoXml() string {
	if m != nil && m.DeviceInfoXml != nil {
		return *m.DeviceInfoXml
	}
	return ""
}

func (m *AcctSectResp) GetSafeDevice() uint32 {
	if m != nil && m.SafeDevice != nil {
		return *m.SafeDevice
	}
	return 0
}

func (m *AcctSectResp) GetOfficialUserName() string {
	if m != nil && m.OfficialUserName != nil {
		return *m.OfficialUserName
	}
	return ""
}

func (m *AcctSectResp) GetOfficialNickName() string {
	if m != nil && m.OfficialNickName != nil {
		return *m.OfficialNickName
	}
	return ""
}

func (m *AcctSectResp) GetPushMailStatus() uint32 {
	if m != nil && m.PushMailStatus != nil {
		return *m.PushMailStatus
	}
	return 0
}

func (m *AcctSectResp) GetFSURL() string {
	if m != nil && m.FSURL != nil {
		return *m.FSURL
	}
	return ""
}

type BuiltinIPList struct {
	LongConnectIPCount   *uint32      `protobuf:"varint,1,req,name=LongConnectIPCount" json:"LongConnectIPCount,omitempty"`
	ShortConnectIPCount  *uint32      `protobuf:"varint,2,req,name=ShortConnectIPCount" json:"ShortConnectIPCount,omitempty"`
	Seq                  *uint32      `protobuf:"varint,5,req,name=Seq" json:"Seq,omitempty"`
	LongConnectIPList    []*BuiltinIP `protobuf:"bytes,3,rep,name=LongConnectIPList" json:"LongConnectIPList,omitempty"`
	ShortConnectIPList   []*BuiltinIP `protobuf:"bytes,4,rep,name=ShortConnectIPList" json:"ShortConnectIPList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BuiltinIPList) Reset()         { *m = BuiltinIPList{} }
func (m *BuiltinIPList) String() string { return proto.CompactTextString(m) }
func (*BuiltinIPList) ProtoMessage()    {}
func (*BuiltinIPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{11}
}

func (m *BuiltinIPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinIPList.Unmarshal(m, b)
}
func (m *BuiltinIPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinIPList.Marshal(b, m, deterministic)
}
func (m *BuiltinIPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinIPList.Merge(m, src)
}
func (m *BuiltinIPList) XXX_Size() int {
	return xxx_messageInfo_BuiltinIPList.Size(m)
}
func (m *BuiltinIPList) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinIPList.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinIPList proto.InternalMessageInfo

func (m *BuiltinIPList) GetLongConnectIPCount() uint32 {
	if m != nil && m.LongConnectIPCount != nil {
		return *m.LongConnectIPCount
	}
	return 0
}

func (m *BuiltinIPList) GetShortConnectIPCount() uint32 {
	if m != nil && m.ShortConnectIPCount != nil {
		return *m.ShortConnectIPCount
	}
	return 0
}

func (m *BuiltinIPList) GetSeq() uint32 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *BuiltinIPList) GetLongConnectIPList() []*BuiltinIP {
	if m != nil {
		return m.LongConnectIPList
	}
	return nil
}

func (m *BuiltinIPList) GetShortConnectIPList() []*BuiltinIP {
	if m != nil {
		return m.ShortConnectIPList
	}
	return nil
}

type WTLoginImgRespInfo struct {
	ImgEncryptKey        *string           `protobuf:"bytes,1,opt,name=ImgEncryptKey" json:"ImgEncryptKey,omitempty"`
	KSid                 *SKBuiltinBuffert `protobuf:"bytes,2,req,name=KSid" json:"KSid,omitempty"`
	ImgSid               *string           `protobuf:"bytes,3,opt,name=ImgSid" json:"ImgSid,omitempty"`
	ImgBuf               *SKBuiltinBuffert `protobuf:"bytes,4,req,name=ImgBuf" json:"ImgBuf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WTLoginImgRespInfo) Reset()         { *m = WTLoginImgRespInfo{} }
func (m *WTLoginImgRespInfo) String() string { return proto.CompactTextString(m) }
func (*WTLoginImgRespInfo) ProtoMessage()    {}
func (*WTLoginImgRespInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{12}
}

func (m *WTLoginImgRespInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WTLoginImgRespInfo.Unmarshal(m, b)
}
func (m *WTLoginImgRespInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WTLoginImgRespInfo.Marshal(b, m, deterministic)
}
func (m *WTLoginImgRespInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WTLoginImgRespInfo.Merge(m, src)
}
func (m *WTLoginImgRespInfo) XXX_Size() int {
	return xxx_messageInfo_WTLoginImgRespInfo.Size(m)
}
func (m *WTLoginImgRespInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WTLoginImgRespInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WTLoginImgRespInfo proto.InternalMessageInfo

func (m *WTLoginImgRespInfo) GetImgEncryptKey() string {
	if m != nil && m.ImgEncryptKey != nil {
		return *m.ImgEncryptKey
	}
	return ""
}

func (m *WTLoginImgRespInfo) GetKSid() *SKBuiltinBuffert {
	if m != nil {
		return m.KSid
	}
	return nil
}

func (m *WTLoginImgRespInfo) GetImgSid() string {
	if m != nil && m.ImgSid != nil {
		return *m.ImgSid
	}
	return ""
}

func (m *WTLoginImgRespInfo) GetImgBuf() *SKBuiltinBuffert {
	if m != nil {
		return m.ImgBuf
	}
	return nil
}

type NetworkSectResp struct {
	NewHostList          *HostList       `protobuf:"bytes,1,opt,name=NewHostList" json:"NewHostList,omitempty"`
	NetworkControl       *NetworkControl `protobuf:"bytes,2,opt,name=NetworkControl" json:"NetworkControl,omitempty"`
	BuiltinIPList        *BuiltinIPList  `protobuf:"bytes,3,opt,name=BuiltinIPList" json:"BuiltinIPList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NetworkSectResp) Reset()         { *m = NetworkSectResp{} }
func (m *NetworkSectResp) String() string { return proto.CompactTextString(m) }
func (*NetworkSectResp) ProtoMessage()    {}
func (*NetworkSectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{13}
}

func (m *NetworkSectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkSectResp.Unmarshal(m, b)
}
func (m *NetworkSectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkSectResp.Marshal(b, m, deterministic)
}
func (m *NetworkSectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkSectResp.Merge(m, src)
}
func (m *NetworkSectResp) XXX_Size() int {
	return xxx_messageInfo_NetworkSectResp.Size(m)
}
func (m *NetworkSectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkSectResp.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkSectResp proto.InternalMessageInfo

func (m *NetworkSectResp) GetNewHostList() *HostList {
	if m != nil {
		return m.NewHostList
	}
	return nil
}

func (m *NetworkSectResp) GetNetworkControl() *NetworkControl {
	if m != nil {
		return m.NetworkControl
	}
	return nil
}

func (m *NetworkSectResp) GetBuiltinIPList() *BuiltinIPList {
	if m != nil {
		return m.BuiltinIPList
	}
	return nil
}

type StyleKeyVal struct {
	Key                  *uint32  `protobuf:"varint,1,req,name=Key" json:"Key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=Val" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StyleKeyVal) Reset()         { *m = StyleKeyVal{} }
func (m *StyleKeyVal) String() string { return proto.CompactTextString(m) }
func (*StyleKeyVal) ProtoMessage()    {}
func (*StyleKeyVal) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{14}
}

func (m *StyleKeyVal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StyleKeyVal.Unmarshal(m, b)
}
func (m *StyleKeyVal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StyleKeyVal.Marshal(b, m, deterministic)
}
func (m *StyleKeyVal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StyleKeyVal.Merge(m, src)
}
func (m *StyleKeyVal) XXX_Size() int {
	return xxx_messageInfo_StyleKeyVal.Size(m)
}
func (m *StyleKeyVal) XXX_DiscardUnknown() {
	xxx_messageInfo_StyleKeyVal.DiscardUnknown(m)
}

var xxx_messageInfo_StyleKeyVal proto.InternalMessageInfo

func (m *StyleKeyVal) GetKey() uint32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *StyleKeyVal) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type ShowStyleKey struct {
	KeyCount             *uint32        `protobuf:"varint,1,req,name=KeyCount" json:"KeyCount,omitempty"`
	Key                  []*StyleKeyVal `protobuf:"bytes,2,rep,name=Key" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShowStyleKey) Reset()         { *m = ShowStyleKey{} }
func (m *ShowStyleKey) String() string { return proto.CompactTextString(m) }
func (*ShowStyleKey) ProtoMessage()    {}
func (*ShowStyleKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{15}
}

func (m *ShowStyleKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowStyleKey.Unmarshal(m, b)
}
func (m *ShowStyleKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowStyleKey.Marshal(b, m, deterministic)
}
func (m *ShowStyleKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowStyleKey.Merge(m, src)
}
func (m *ShowStyleKey) XXX_Size() int {
	return xxx_messageInfo_ShowStyleKey.Size(m)
}
func (m *ShowStyleKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowStyleKey.DiscardUnknown(m)
}

var xxx_messageInfo_ShowStyleKey proto.InternalMessageInfo

func (m *ShowStyleKey) GetKeyCount() uint32 {
	if m != nil && m.KeyCount != nil {
		return *m.KeyCount
	}
	return 0
}

func (m *ShowStyleKey) GetKey() []*StyleKeyVal {
	if m != nil {
		return m.Key
	}
	return nil
}

type WxVerifyCodeRespInfo struct {
	VerifySignature      *string           `protobuf:"bytes,1,opt,name=VerifySignature" json:"VerifySignature,omitempty"`
	VerifyBuff           *SKBuiltinBuffert `protobuf:"bytes,2,req,name=VerifyBuff" json:"VerifyBuff,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WxVerifyCodeRespInfo) Reset()         { *m = WxVerifyCodeRespInfo{} }
func (m *WxVerifyCodeRespInfo) String() string { return proto.CompactTextString(m) }
func (*WxVerifyCodeRespInfo) ProtoMessage()    {}
func (*WxVerifyCodeRespInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{16}
}

func (m *WxVerifyCodeRespInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxVerifyCodeRespInfo.Unmarshal(m, b)
}
func (m *WxVerifyCodeRespInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxVerifyCodeRespInfo.Marshal(b, m, deterministic)
}
func (m *WxVerifyCodeRespInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxVerifyCodeRespInfo.Merge(m, src)
}
func (m *WxVerifyCodeRespInfo) XXX_Size() int {
	return xxx_messageInfo_WxVerifyCodeRespInfo.Size(m)
}
func (m *WxVerifyCodeRespInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WxVerifyCodeRespInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WxVerifyCodeRespInfo proto.InternalMessageInfo

func (m *WxVerifyCodeRespInfo) GetVerifySignature() string {
	if m != nil && m.VerifySignature != nil {
		return *m.VerifySignature
	}
	return ""
}

func (m *WxVerifyCodeRespInfo) GetVerifyBuff() *SKBuiltinBuffert {
	if m != nil {
		return m.VerifyBuff
	}
	return nil
}

type AuthSectResp struct {
	Uin                  *uint32               `protobuf:"varint,1,req,name=Uin" json:"Uin,omitempty"`
	SvrPubECDHKey        *ECDHKey              `protobuf:"bytes,2,req,name=SvrPubECDHKey" json:"SvrPubECDHKey,omitempty"`
	SessionKey           *SKBuiltinBuffert     `protobuf:"bytes,3,req,name=SessionKey" json:"SessionKey,omitempty"`
	AutoAuthKey          *SKBuiltinBuffert     `protobuf:"bytes,4,req,name=AutoAuthKey" json:"AutoAuthKey,omitempty"`
	WTLoginRspBuffFlag   *uint32               `protobuf:"varint,5,req,name=WTLoginRspBuffFlag" json:"WTLoginRspBuffFlag,omitempty"`
	WTLoginRspBuff       *SKBuiltinBuffert     `protobuf:"bytes,6,opt,name=WTLoginRspBuff" json:"WTLoginRspBuff,omitempty"`
	WTLoginImgRespInfo   *WTLoginImgRespInfo   `protobuf:"bytes,7,opt,name=WTLoginImgRespInfo" json:"WTLoginImgRespInfo,omitempty"`
	WxVerifyCodeRespInfo *WxVerifyCodeRespInfo `protobuf:"bytes,8,opt,name=WxVerifyCodeRespInfo" json:"WxVerifyCodeRespInfo,omitempty"`
	CliDBEncryptKey      *SKBuiltinBuffert     `protobuf:"bytes,9,opt,name=CliDBEncryptKey" json:"CliDBEncryptKey,omitempty"`
	CliDBEncryptInfo     *SKBuiltinBuffert     `protobuf:"bytes,10,opt,name=CliDBEncryptInfo" json:"CliDBEncryptInfo,omitempty"`
	AuthKey              *string               `protobuf:"bytes,11,opt,name=AuthKey" json:"AuthKey,omitempty"`
	A2Key                *SKBuiltinBuffert     `protobuf:"bytes,12,opt,name=A2Key" json:"A2Key,omitempty"`
	ApplyBetaUrl         *string               `protobuf:"bytes,14,opt,name=ApplyBetaUrl" json:"ApplyBetaUrl,omitempty"`
	ShowStyle            *ShowStyleKey         `protobuf:"bytes,15,opt,name=ShowStyle" json:"ShowStyle,omitempty"`
	AuthTicket           *string               `protobuf:"bytes,16,opt,name=AuthTicket" json:"AuthTicket,omitempty"`
	NewVersion           *uint32               `protobuf:"varint,17,opt,name=NewVersion" json:"NewVersion,omitempty"`
	UpdateFlag           *uint32               `protobuf:"varint,18,opt,name=UpdateFlag" json:"UpdateFlag,omitempty"`
	AuthResultFlag       *uint32               `protobuf:"varint,19,opt,name=AuthResultFlag" json:"AuthResultFlag,omitempty"`
	FSURL                *string               `protobuf:"bytes,20,opt,name=FSURL" json:"FSURL,omitempty"`
	MmtlsControlBitFlag  *uint32               `protobuf:"varint,21,opt,name=MmtlsControlBitFlag" json:"MmtlsControlBitFlag,omitempty"`
	ServerTime           *uint32               `protobuf:"varint,22,opt,name=ServerTime" json:"ServerTime,omitempty"`
	ClientSessionKey     *SKBuiltinBuffert     `protobuf:"bytes,23,opt,name=ClientSessionKey" json:"ClientSessionKey,omitempty"`
	ServerSessionKey     *SKBuiltinBuffert     `protobuf:"bytes,24,opt,name=ServerSessionKey" json:"ServerSessionKey,omitempty"`
	EcdhControlFlag      *uint32               `protobuf:"varint,25,opt,name=EcdhControlFlag" json:"EcdhControlFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AuthSectResp) Reset()         { *m = AuthSectResp{} }
func (m *AuthSectResp) String() string { return proto.CompactTextString(m) }
func (*AuthSectResp) ProtoMessage()    {}
func (*AuthSectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{17}
}

func (m *AuthSectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSectResp.Unmarshal(m, b)
}
func (m *AuthSectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSectResp.Marshal(b, m, deterministic)
}
func (m *AuthSectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSectResp.Merge(m, src)
}
func (m *AuthSectResp) XXX_Size() int {
	return xxx_messageInfo_AuthSectResp.Size(m)
}
func (m *AuthSectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSectResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSectResp proto.InternalMessageInfo

func (m *AuthSectResp) GetUin() uint32 {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return 0
}

func (m *AuthSectResp) GetSvrPubECDHKey() *ECDHKey {
	if m != nil {
		return m.SvrPubECDHKey
	}
	return nil
}

func (m *AuthSectResp) GetSessionKey() *SKBuiltinBuffert {
	if m != nil {
		return m.SessionKey
	}
	return nil
}

func (m *AuthSectResp) GetAutoAuthKey() *SKBuiltinBuffert {
	if m != nil {
		return m.AutoAuthKey
	}
	return nil
}

func (m *AuthSectResp) GetWTLoginRspBuffFlag() uint32 {
	if m != nil && m.WTLoginRspBuffFlag != nil {
		return *m.WTLoginRspBuffFlag
	}
	return 0
}

func (m *AuthSectResp) GetWTLoginRspBuff() *SKBuiltinBuffert {
	if m != nil {
		return m.WTLoginRspBuff
	}
	return nil
}

func (m *AuthSectResp) GetWTLoginImgRespInfo() *WTLoginImgRespInfo {
	if m != nil {
		return m.WTLoginImgRespInfo
	}
	return nil
}

func (m *AuthSectResp) GetWxVerifyCodeRespInfo() *WxVerifyCodeRespInfo {
	if m != nil {
		return m.WxVerifyCodeRespInfo
	}
	return nil
}

func (m *AuthSectResp) GetCliDBEncryptKey() *SKBuiltinBuffert {
	if m != nil {
		return m.CliDBEncryptKey
	}
	return nil
}

func (m *AuthSectResp) GetCliDBEncryptInfo() *SKBuiltinBuffert {
	if m != nil {
		return m.CliDBEncryptInfo
	}
	return nil
}

func (m *AuthSectResp) GetAuthKey() string {
	if m != nil && m.AuthKey != nil {
		return *m.AuthKey
	}
	return ""
}

func (m *AuthSectResp) GetA2Key() *SKBuiltinBuffert {
	if m != nil {
		return m.A2Key
	}
	return nil
}

func (m *AuthSectResp) GetApplyBetaUrl() string {
	if m != nil && m.ApplyBetaUrl != nil {
		return *m.ApplyBetaUrl
	}
	return ""
}

func (m *AuthSectResp) GetShowStyle() *ShowStyleKey {
	if m != nil {
		return m.ShowStyle
	}
	return nil
}

func (m *AuthSectResp) GetAuthTicket() string {
	if m != nil && m.AuthTicket != nil {
		return *m.AuthTicket
	}
	return ""
}

func (m *AuthSectResp) GetNewVersion() uint32 {
	if m != nil && m.NewVersion != nil {
		return *m.NewVersion
	}
	return 0
}

func (m *AuthSectResp) GetUpdateFlag() uint32 {
	if m != nil && m.UpdateFlag != nil {
		return *m.UpdateFlag
	}
	return 0
}

func (m *AuthSectResp) GetAuthResultFlag() uint32 {
	if m != nil && m.AuthResultFlag != nil {
		return *m.AuthResultFlag
	}
	return 0
}

func (m *AuthSectResp) GetFSURL() string {
	if m != nil && m.FSURL != nil {
		return *m.FSURL
	}
	return ""
}

func (m *AuthSectResp) GetMmtlsControlBitFlag() uint32 {
	if m != nil && m.MmtlsControlBitFlag != nil {
		return *m.MmtlsControlBitFlag
	}
	return 0
}

func (m *AuthSectResp) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *AuthSectResp) GetClientSessionKey() *SKBuiltinBuffert {
	if m != nil {
		return m.ClientSessionKey
	}
	return nil
}

func (m *AuthSectResp) GetServerSessionKey() *SKBuiltinBuffert {
	if m != nil {
		return m.ServerSessionKey
	}
	return nil
}

func (m *AuthSectResp) GetEcdhControlFlag() uint32 {
	if m != nil && m.EcdhControlFlag != nil {
		return *m.EcdhControlFlag
	}
	return 0
}

type UnifyAuthResponse struct {
	baseResponse         *BaseResponse    `protobuf:"bytes,1,req,name=BaseResponse" json:"BaseResponse,omitempty"`
	UnifyAuthSectFlag    *uint32          `protobuf:"varint,2,opt,name=UnifyAuthSectFlag" json:"UnifyAuthSectFlag,omitempty"`
	AuthSectResp         *AuthSectResp    `protobuf:"bytes,3,opt,name=AuthSectResp" json:"AuthSectResp,omitempty"`
	AcctSectResp         *AcctSectResp    `protobuf:"bytes,4,opt,name=AcctSectResp" json:"AcctSectResp,omitempty"`
	NetworkSectResp      *NetworkSectResp `protobuf:"bytes,5,opt,name=NetworkSectResp" json:"NetworkSectResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UnifyAuthResponse) Reset()         { *m = UnifyAuthResponse{} }
func (m *UnifyAuthResponse) String() string { return proto.CompactTextString(m) }
func (*UnifyAuthResponse) ProtoMessage()    {}
func (*UnifyAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bbab45bb686d788, []int{18}
}

func (m *UnifyAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnifyAuthResponse.Unmarshal(m, b)
}
func (m *UnifyAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnifyAuthResponse.Marshal(b, m, deterministic)
}
func (m *UnifyAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnifyAuthResponse.Merge(m, src)
}
func (m *UnifyAuthResponse) XXX_Size() int {
	return xxx_messageInfo_UnifyAuthResponse.Size(m)
}
func (m *UnifyAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnifyAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnifyAuthResponse proto.InternalMessageInfo

func (m *UnifyAuthResponse) GetBaseResponse() *BaseResponse {
	if m != nil {
		return m.baseResponse
	}
	return nil
}

func (m *UnifyAuthResponse) GetUnifyAuthSectFlag() uint32 {
	if m != nil && m.UnifyAuthSectFlag != nil {
		return *m.UnifyAuthSectFlag
	}
	return 0
}

func (m *UnifyAuthResponse) GetAuthSectResp() *AuthSectResp {
	if m != nil {
		return m.AuthSectResp
	}
	return nil
}

func (m *UnifyAuthResponse) GetAcctSectResp() *AcctSectResp {
	if m != nil {
		return m.AcctSectResp
	}
	return nil
}

func (m *UnifyAuthResponse) GetNetworkSectResp() *NetworkSectResp {
	if m != nil {
		return m.NetworkSectResp
	}
	return nil
}

func init() {
	proto.RegisterType((*WTLoginImgReqInfo)(nil), "mmproto.WTLoginImgReqInfo")
	proto.RegisterType((*WxVerifyCodeReqInfo)(nil), "mmproto.WxVerifyCodeReqInfo")
	proto.RegisterType((*BaseAuthReqInfo)(nil), "mmproto.BaseAuthReqInfo")
	proto.RegisterType((*ManualAuthRsaReqData)(nil), "mmproto.ManualAuthRsaReqData")
	proto.RegisterType((*ManualAuthAesReqData)(nil), "mmproto.ManualAuthAesReqData")
	proto.RegisterType((*ManualAuthRequest)(nil), "mmproto.ManualAuthRequest")
	proto.RegisterType((*Host)(nil), "mmproto.Host")
	proto.RegisterType((*HostList)(nil), "mmproto.HostList")
	proto.RegisterType((*NetworkControl)(nil), "mmproto.NetworkControl")
	proto.RegisterType((*BuiltinIP)(nil), "mmproto.BuiltinIP")
	proto.RegisterType((*AcctSectResp)(nil), "mmproto.AcctSectResp")
	proto.RegisterType((*BuiltinIPList)(nil), "mmproto.BuiltinIPList")
	proto.RegisterType((*WTLoginImgRespInfo)(nil), "mmproto.WTLoginImgRespInfo")
	proto.RegisterType((*NetworkSectResp)(nil), "mmproto.NetworkSectResp")
	proto.RegisterType((*StyleKeyVal)(nil), "mmproto.StyleKeyVal")
	proto.RegisterType((*ShowStyleKey)(nil), "mmproto.ShowStyleKey")
	proto.RegisterType((*WxVerifyCodeRespInfo)(nil), "mmproto.WxVerifyCodeRespInfo")
	proto.RegisterType((*AuthSectResp)(nil), "mmproto.AuthSectResp")
	proto.RegisterType((*UnifyAuthResponse)(nil), "mmproto.UnifyAuthResponse")
}

func init() {
	proto.RegisterFile("secmanualauth.proto", fileDescriptor_9bbab45bb686d788)
}

var fileDescriptor_9bbab45bb686d788 = []byte{
	// 1850 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x6e, 0xe3, 0xc8,
	0x11, 0x86, 0x24, 0x7b, 0xc6, 0x6a, 0x49, 0xfe, 0x69, 0x7b, 0x66, 0xb8, 0xce, 0x26, 0x70, 0x88,
	0x60, 0x60, 0x04, 0xd9, 0x49, 0xd6, 0x0b, 0x0c, 0xb0, 0xf9, 0x41, 0x62, 0xc9, 0x5e, 0x8c, 0xe0,
	0x9f, 0x55, 0x9a, 0xb6, 0x37, 0xd8, 0x9c, 0x38, 0x52, 0x4b, 0x6a, 0x0c, 0xd9, 0x94, 0xc9, 0xa6,
	0xbd, 0x42, 0x9e, 0x20, 0xc7, 0x5c, 0xf3, 0x18, 0x41, 0x90, 0x4b, 0x72, 0xcd, 0x13, 0xe4, 0x0d,
	0xf2, 0x10, 0x39, 0x07, 0x55, 0xdd, 0x24, 0x9b, 0x14, 0xb3, 0x72, 0x80, 0xbd, 0xb1, 0xbe, 0xfa,
	0xe9, 0xea, 0xae, 0xea, 0xaa, 0x2e, 0x92, 0xfd, 0x84, 0x8f, 0x43, 0x5f, 0xa6, 0x7e, 0xe0, 0xa7,
	0x6a, 0xfe, 0x66, 0x11, 0x47, 0x2a, 0xa2, 0xcf, 0xc3, 0x10, 0x3f, 0x0e, 0xc9, 0x7b, 0x3f, 0xe1,
	0x1a, 0x74, 0xff, 0xdc, 0x20, 0x7b, 0x5f, 0xdd, 0x5c, 0x46, 0x33, 0x21, 0x87, 0xe1, 0x8c, 0xf1,
	0xfb, 0xa1, 0x9c, 0x46, 0xf4, 0x25, 0x79, 0x36, 0x0c, 0x67, 0x9e, 0x98, 0x38, 0x8d, 0xa3, 0xc6,
	0x71, 0x9b, 0x19, 0x8a, 0x3a, 0xe4, 0xf9, 0x30, 0x9c, 0x0d, 0xa2, 0x09, 0x77, 0x9a, 0xc8, 0xc8,
	0x48, 0xfa, 0x23, 0xd2, 0x1b, 0x86, 0xb3, 0x73, 0x39, 0x8e, 0x97, 0x0b, 0x75, 0xc1, 0x97, 0x4e,
	0x0b, 0xf9, 0x65, 0x90, 0x7e, 0x42, 0x36, 0x2e, 0xc0, 0xea, 0xc6, 0x51, 0xf3, 0xb8, 0x73, 0xf2,
	0xd1, 0x1b, 0xe3, 0xd1, 0x1b, 0xef, 0xa2, 0x9f, 0x8a, 0x40, 0x09, 0xd9, 0x4f, 0xa7, 0x53, 0x1e,
	0x2b, 0x86, 0x62, 0x2e, 0x27, 0xfb, 0x5f, 0x7d, 0x73, 0xc7, 0x63, 0x31, 0x5d, 0xc2, 0x22, 0x99,
	0x77, 0xc7, 0x64, 0x47, 0x83, 0x9e, 0x98, 0x49, 0x5f, 0xa5, 0x31, 0x37, 0x6e, 0x56, 0x61, 0xf0,
	0x2a, 0x53, 0x97, 0x8a, 0x4b, 0x65, 0xbc, 0x2e, 0x83, 0xee, 0x3f, 0x5a, 0x64, 0xa7, 0xef, 0x27,
	0xfc, 0x34, 0x55, 0xf3, 0x6c, 0x8d, 0x53, 0xb2, 0x6d, 0x8e, 0x85, 0xf1, 0x7b, 0xf0, 0x0a, 0x97,
	0xf8, 0x56, 0x9f, 0x2b, 0x0a, 0xf4, 0x5d, 0xcd, 0xc9, 0xa2, 0x03, 0x9d, 0x93, 0xc3, 0xdc, 0xca,
	0x8a, 0x04, 0xab, 0x09, 0xc7, 0x75, 0xed, 0x39, 0xe0, 0x11, 0x77, 0x4e, 0x3e, 0x2e, 0x6c, 0xad,
	0xca, 0xb0, 0xda, 0x03, 0x1c, 0x90, 0x9d, 0x41, 0x20, 0xce, 0xfa, 0x56, 0xb8, 0x36, 0xd6, 0xed,
	0xae, 0xaa, 0x41, 0xcf, 0xc9, 0xae, 0x0d, 0xa1, 0x47, 0x9b, 0xeb, 0xac, 0xac, 0xa8, 0xd0, 0x23,
	0xd2, 0x31, 0xe7, 0xfe, 0x45, 0xe0, 0xcf, 0x9c, 0x67, 0x47, 0x8d, 0xe3, 0x1e, 0xb3, 0x21, 0xfa,
	0x03, 0x42, 0x80, 0xbc, 0x11, 0xe3, 0x0f, 0x5c, 0x39, 0xcf, 0x31, 0x82, 0x16, 0xe2, 0xfe, 0xab,
	0x41, 0x0e, 0xae, 0x30, 0xd9, 0x51, 0x2b, 0xf1, 0x19, 0xbf, 0x3f, 0xf3, 0x95, 0x0f, 0x31, 0x64,
	0xbe, 0x9c, 0x44, 0x21, 0xae, 0x07, 0xbb, 0x6c, 0xac, 0xcb, 0xbb, 0x8a, 0x02, 0x7d, 0x4b, 0x7a,
	0x83, 0x40, 0x8c, 0xd2, 0xf7, 0xe7, 0x83, 0xb3, 0x77, 0x60, 0xa1, 0x89, 0x16, 0x76, 0x73, 0x0b,
	0x06, 0x67, 0x65, 0x31, 0x7a, 0x48, 0xb6, 0x6e, 0x13, 0x1e, 0x5f, 0xfb, 0x21, 0x37, 0x37, 0x21,
	0xa7, 0xe9, 0x2e, 0x69, 0x8d, 0x1e, 0x27, 0x78, 0xe2, 0x6d, 0x06, 0x9f, 0x94, 0x92, 0x8d, 0xd1,
	0xe3, 0xe4, 0x04, 0x8f, 0xaf, 0xcd, 0xf0, 0xdb, 0xfd, 0xcb, 0x33, 0x7b, 0x57, 0xa7, 0x3c, 0xc9,
	0x76, 0xf5, 0x96, 0x74, 0x20, 0x59, 0x19, 0xbf, 0x4f, 0x79, 0xa2, 0xcc, 0x96, 0x0e, 0x72, 0x87,
	0x2c, 0x1e, 0xb3, 0x05, 0xe9, 0xcf, 0x73, 0x3d, 0x2b, 0x11, 0x9d, 0x92, 0x9e, 0x75, 0x01, 0x98,
	0x2d, 0x0c, 0x0e, 0x0e, 0x43, 0x2e, 0xcc, 0x56, 0xf0, 0x1b, 0xb6, 0xe8, 0x45, 0x53, 0x75, 0xb3,
	0x5c, 0x70, 0xb3, 0x97, 0x9c, 0xa6, 0x2e, 0xe9, 0x9a, 0x83, 0x1d, 0x8e, 0x3c, 0x7e, 0xef, 0x6c,
	0x1e, 0x35, 0x8f, 0x7b, 0xac, 0x84, 0x41, 0xe0, 0x07, 0x81, 0xe0, 0x52, 0x79, 0xfc, 0x7e, 0x78,
	0x86, 0x81, 0x6f, 0x33, 0x1b, 0xa2, 0x1f, 0x93, 0x76, 0x71, 0xc3, 0x75, 0xdc, 0x0b, 0x00, 0xd2,
	0xe2, 0x8c, 0x3f, 0x88, 0x31, 0xc7, 0x43, 0xde, 0xd2, 0x69, 0x51, 0x20, 0x05, 0x1f, 0x3d, 0x6c,
	0xdb, 0x7c, 0xf4, 0xf1, 0x90, 0x6c, 0x5d, 0xfa, 0x72, 0x96, 0xfa, 0x33, 0xee, 0x10, 0xed, 0x7f,
	0x46, 0x03, 0xef, 0x46, 0x84, 0xfc, 0xeb, 0x48, 0x72, 0xa7, 0xa3, 0x79, 0x19, 0x0d, 0x35, 0x70,
	0x30, 0xf7, 0xa5, 0xe4, 0x81, 0xd3, 0x3b, 0x6a, 0x1c, 0x6f, 0xb2, 0x8c, 0x04, 0x7f, 0x41, 0xca,
	0x53, 0x7e, 0xb8, 0x70, 0xb6, 0x31, 0x91, 0x0b, 0x00, 0xf6, 0xab, 0x57, 0xef, 0xc7, 0xbe, 0x9c,
	0x38, 0x3b, 0x7a, 0xbf, 0x16, 0x54, 0x48, 0x5c, 0x45, 0x13, 0x1e, 0x38, 0xbb, 0xb6, 0x04, 0x42,
	0x50, 0x97, 0xbf, 0xf4, 0x70, 0x3f, 0x7b, 0xba, 0x2e, 0x6b, 0x0a, 0x34, 0x19, 0xf7, 0x83, 0x41,
	0x94, 0x4a, 0x15, 0x2f, 0x1d, 0xaa, 0x35, 0x2d, 0x08, 0x76, 0xd4, 0x4f, 0xe5, 0x24, 0xe0, 0xc3,
	0x33, 0x67, 0x5f, 0xef, 0x28, 0xa3, 0x81, 0x77, 0x3a, 0xf1, 0xa2, 0x34, 0x1e, 0x73, 0xe7, 0x40,
	0xf3, 0x32, 0x1a, 0xf6, 0x34, 0x1c, 0xcd, 0x23, 0xc9, 0xef, 0x78, 0xec, 0xbc, 0xd0, 0x31, 0xc8,
	0x01, 0xe4, 0xca, 0x45, 0xaa, 0x93, 0xe0, 0x25, 0x06, 0xb9, 0x00, 0xe0, 0xfe, 0xe9, 0x70, 0x8e,
	0xe7, 0x7c, 0xfc, 0x61, 0xe2, 0x2b, 0xe7, 0xd5, 0xda, 0x1a, 0x5a, 0x56, 0xa0, 0x9f, 0x90, 0xad,
	0x64, 0xe1, 0x87, 0x90, 0xf8, 0x8e, 0x83, 0xca, 0x7b, 0x85, 0xb2, 0x61, 0xb0, 0x5c, 0xc4, 0xfd,
	0x53, 0x83, 0xec, 0x59, 0xa5, 0xc0, 0x64, 0xfe, 0xaf, 0x08, 0x29, 0xaa, 0x82, 0xb9, 0x30, 0xdf,
	0xcf, 0xcd, 0xd4, 0x95, 0x0e, 0x66, 0x29, 0x80, 0x7a, 0x71, 0xfd, 0x4c, 0x01, 0xa8, 0x53, 0x2f,
	0x84, 0x98, 0xa5, 0xe0, 0x7e, 0x4d, 0x36, 0xde, 0x45, 0x89, 0xc2, 0xd8, 0xc5, 0x62, 0x26, 0x64,
	0xd6, 0x53, 0x35, 0x05, 0x79, 0xea, 0xa5, 0xef, 0x13, 0x25, 0x54, 0xaa, 0xb2, 0xb6, 0x6a, 0x21,
	0x10, 0x9d, 0x51, 0x2c, 0xa2, 0x58, 0x28, 0xdd, 0x54, 0x37, 0x59, 0x4e, 0xbb, 0x03, 0xb2, 0x05,
	0xb6, 0x2f, 0x45, 0xa2, 0xe8, 0x01, 0xd9, 0xc4, 0x60, 0xe3, 0x06, 0x7b, 0x4c, 0x13, 0xf4, 0x87,
	0x64, 0x03, 0xb8, 0x4e, 0xf3, 0xa8, 0x75, 0xdc, 0x39, 0xe9, 0xe5, 0x6e, 0x83, 0x1a, 0x43, 0x96,
	0xfb, 0x9f, 0x06, 0xd9, 0xbe, 0xe6, 0xea, 0x31, 0x8a, 0x3f, 0x40, 0x47, 0x8c, 0xa3, 0x00, 0xd7,
	0x8c, 0x62, 0xb4, 0x6b, 0xbc, 0xcd, 0x69, 0xc8, 0x35, 0x48, 0xea, 0x28, 0x55, 0xc6, 0x30, 0xe6,
	0x9a, 0x05, 0x41, 0x7f, 0xbe, 0x12, 0xf2, 0x3a, 0x8a, 0x16, 0x43, 0xa9, 0x78, 0xfc, 0xe0, 0x07,
	0xe8, 0x78, 0x8f, 0x55, 0x61, 0x94, 0xf4, 0xbf, 0x29, 0x49, 0x6e, 0x18, 0xc9, 0x32, 0x4c, 0x5f,
	0x93, 0xed, 0x9b, 0xe5, 0x42, 0xc8, 0x59, 0x2e, 0xb8, 0x89, 0x67, 0x51, 0x41, 0xe9, 0x8f, 0xc9,
	0xae, 0xad, 0x07, 0x6e, 0x61, 0xe9, 0xd8, 0x64, 0x2b, 0xb8, 0xfb, 0x7b, 0xd2, 0xce, 0x2b, 0x12,
	0x94, 0x38, 0x05, 0x59, 0xac, 0x4f, 0x0f, 0xbf, 0x01, 0x5b, 0x44, 0xb1, 0xc2, 0x98, 0xf7, 0x18,
	0x7e, 0xd3, 0x6d, 0xd2, 0x1c, 0x8e, 0x70, 0x3f, 0x5d, 0xd6, 0x1c, 0x8e, 0x20, 0xac, 0x67, 0x51,
	0xe8, 0x0b, 0x89, 0x9e, 0x77, 0x99, 0xa1, 0xdc, 0x7f, 0xb7, 0x48, 0xf7, 0x74, 0x3c, 0x56, 0x1e,
	0x1f, 0x2b, 0xc6, 0x93, 0x45, 0xa9, 0x25, 0x34, 0x2a, 0x2d, 0xe1, 0x90, 0x6c, 0x5d, 0x8b, 0xf1,
	0x07, 0xe4, 0xe9, 0x03, 0xcd, 0x69, 0xa8, 0x37, 0x7d, 0x21, 0x27, 0xb7, 0x42, 0x3a, 0x2d, 0xf4,
	0x23, 0x23, 0xe1, 0xf6, 0xc1, 0xe7, 0x79, 0xe8, 0x8b, 0xc0, 0x94, 0xe0, 0x02, 0x80, 0xbc, 0x02,
	0xe2, 0x2a, 0x7a, 0x2f, 0x02, 0x6e, 0x5a, 0x8b, 0x85, 0x40, 0xbe, 0x9c, 0x06, 0xc2, 0x4f, 0x4c,
	0xe5, 0xd5, 0x04, 0x6c, 0xc7, 0x53, 0xbe, 0x4a, 0x13, 0x67, 0x0b, 0x17, 0x33, 0x14, 0x58, 0x1b,
	0x05, 0xe9, 0x4c, 0x48, 0xec, 0xd2, 0x6d, 0x0c, 0x92, 0x85, 0x80, 0x97, 0x8c, 0xcf, 0xb0, 0x0e,
	0x10, 0x64, 0x66, 0x24, 0xbc, 0xc1, 0x74, 0x09, 0x83, 0x4e, 0xf2, 0xbb, 0x30, 0x30, 0x05, 0xb5,
	0x0c, 0xe2, 0x2d, 0xf0, 0xa7, 0x5c, 0x83, 0x4e, 0x57, 0xdb, 0x2f, 0x10, 0x88, 0xeb, 0x97, 0xd3,
	0xa9, 0x18, 0x0b, 0x3f, 0xc8, 0x4f, 0xb1, 0x87, 0x86, 0x56, 0x70, 0x5b, 0x36, 0x3f, 0xd5, 0xed,
	0xb2, 0x6c, 0x7e, 0xba, 0xaf, 0xc9, 0xf6, 0x28, 0x4d, 0xe6, 0x57, 0xbe, 0x08, 0xcc, 0xbe, 0x77,
	0x70, 0xed, 0x0a, 0x0a, 0xa7, 0xf5, 0x85, 0x77, 0xcb, 0x2e, 0x4d, 0x55, 0xd6, 0x84, 0xfb, 0xc7,
	0x26, 0xe9, 0xe5, 0x29, 0x84, 0xb9, 0xff, 0x86, 0xd0, 0xcb, 0x48, 0xce, 0x06, 0x91, 0x94, 0x7c,
	0xac, 0x86, 0x23, 0xfb, 0x4a, 0xd6, 0x70, 0xe8, 0xcf, 0xc8, 0xbe, 0x37, 0x8f, 0x62, 0x55, 0x51,
	0xd0, 0x19, 0x57, 0xc7, 0x82, 0xe7, 0x43, 0xd1, 0x52, 0xe1, 0x93, 0xfe, 0x86, 0xec, 0x95, 0x2c,
	0xe3, 0xbd, 0x6c, 0xe1, 0x85, 0xa7, 0x45, 0x7f, 0xcf, 0xdc, 0x64, 0xab, 0xc2, 0xb4, 0x4f, 0x68,
	0x79, 0x29, 0x34, 0xb1, 0xf1, 0x3f, 0x4d, 0xd4, 0x48, 0xbb, 0x7f, 0x6d, 0x10, 0x6a, 0x3f, 0x5d,
	0x93, 0x05, 0x3e, 0x1d, 0x56, 0x06, 0x83, 0xc6, 0xb7, 0x0d, 0x06, 0xcd, 0x27, 0x0d, 0x06, 0xd6,
	0x7c, 0xd2, 0x2a, 0xcd, 0x27, 0x9f, 0x22, 0xde, 0x4f, 0xa7, 0xeb, 0x27, 0x0c, 0x23, 0xe8, 0xfe,
	0xb3, 0x41, 0x76, 0x4c, 0xf5, 0xcb, 0xaf, 0xea, 0x67, 0xa4, 0x73, 0xcd, 0x1f, 0xb3, 0xca, 0x6a,
	0x5e, 0xfe, 0x7b, 0xa5, 0xda, 0x09, 0x0c, 0x66, 0x4b, 0xd1, 0x5f, 0x57, 0xab, 0xa8, 0x79, 0x62,
	0xbd, 0xca, 0xf5, 0xca, 0x6c, 0x56, 0x2d, 0xba, 0xbf, 0xac, 0xe4, 0x92, 0x79, 0xdf, 0xbf, 0x5c,
	0x3d, 0x7f, 0x5c, 0xbc, 0x2c, 0xec, 0x7e, 0x4a, 0x3a, 0x9e, 0x5a, 0x06, 0xfc, 0x82, 0x2f, 0xef,
	0xfc, 0x00, 0xb2, 0x24, 0x7b, 0xf0, 0xf6, 0x18, 0x7c, 0x02, 0x72, 0xe7, 0x07, 0xa6, 0xbc, 0xc0,
	0xa7, 0xcb, 0x48, 0xd7, 0x9b, 0x47, 0x8f, 0x99, 0x1a, 0x54, 0xa1, 0x0b, 0xbe, 0xb4, 0x33, 0x36,
	0xa7, 0xe9, 0x6b, 0x6d, 0x4f, 0xb7, 0x91, 0xe2, 0xb5, 0x69, 0x2d, 0x89, 0xab, 0xb8, 0x7f, 0x20,
	0x07, 0xe5, 0x89, 0xc3, 0xa4, 0xc1, 0xd3, 0x67, 0xb6, 0xcf, 0x09, 0xd1, 0x10, 0x4e, 0x5d, 0x6b,
	0x13, 0xc2, 0x12, 0x76, 0xff, 0xde, 0x26, 0x5d, 0xe8, 0xc4, 0x79, 0x20, 0x77, 0x49, 0xeb, 0x16,
	0x1b, 0x2e, 0x9e, 0x02, 0xd4, 0xcc, 0xb7, 0xa4, 0xe7, 0x3d, 0xc4, 0x4f, 0x79, 0xd0, 0x97, 0xc4,
	0xc0, 0x2b, 0x8f, 0x27, 0x89, 0x88, 0xa4, 0x1e, 0x6e, 0xd7, 0x79, 0x55, 0x08, 0xd3, 0x5f, 0xe0,
	0x84, 0x13, 0x81, 0x63, 0x7a, 0xd2, 0x5a, 0xa3, 0x6b, 0x4b, 0x43, 0x3d, 0xc9, 0xc6, 0xca, 0x64,
	0x01, 0x12, 0x58, 0x7f, 0xf5, 0xe5, 0xaf, 0xe1, 0xd8, 0x73, 0xab, 0x46, 0xb1, 0xbc, 0x3f, 0x6d,
	0x6e, 0xd5, 0x0a, 0xf4, 0xa2, 0xee, 0x1e, 0x63, 0x13, 0xed, 0x9c, 0x7c, 0xaf, 0x76, 0x70, 0xd5,
	0x22, 0xac, 0xee, 0xfa, 0xff, 0xb6, 0x3e, 0x1f, 0xf0, 0xbd, 0x6e, 0x3f, 0xa3, 0xea, 0x84, 0x58,
	0x7d, 0x2a, 0xd5, 0x4c, 0xaf, 0xed, 0xef, 0x64, 0x7a, 0x25, 0xff, 0xff, 0xf4, 0xea, 0x90, 0xe7,
	0x59, 0x5c, 0x75, 0x5b, 0xcb, 0x48, 0xfa, 0x53, 0xb2, 0x79, 0x7a, 0x02, 0x78, 0x77, 0x9d, 0x55,
	0x2d, 0x07, 0x33, 0xd3, 0xe9, 0x62, 0x11, 0x2c, 0xfb, 0x5c, 0xf9, 0xb7, 0x71, 0x60, 0x3a, 0x56,
	0x09, 0xa3, 0x9f, 0x91, 0x76, 0x7e, 0x63, 0xb1, 0x51, 0x75, 0x4e, 0x5e, 0x14, 0x86, 0xad, 0xbb,
	0xcc, 0x0a, 0xb9, 0xca, 0xfc, 0xbc, 0x5b, 0x9d, 0x9f, 0x81, 0x7f, 0xcd, 0x1f, 0xef, 0x78, 0x0c,
	0x09, 0x8b, 0x83, 0x45, 0x8f, 0x59, 0x08, 0xf0, 0x6f, 0x17, 0x13, 0x5f, 0x71, 0x4c, 0x3d, 0xaa,
	0xf9, 0x05, 0x02, 0x2d, 0x54, 0xbf, 0xb6, 0x93, 0x34, 0x50, 0x28, 0xb3, 0xaf, 0x5b, 0x68, 0x19,
	0x2d, 0x5a, 0xe8, 0x81, 0xd5, 0x42, 0xa1, 0x01, 0x5e, 0x85, 0x2a, 0x48, 0x4c, 0x15, 0xec, 0x0b,
	0x6d, 0xe2, 0x05, 0x9a, 0xa8, 0x63, 0xe1, 0x53, 0x81, 0xc7, 0x0f, 0x3c, 0xc6, 0xc7, 0xdd, 0x4b,
	0xf3, 0x54, 0xc8, 0x11, 0x13, 0x5a, 0x9c, 0x22, 0xf3, 0x0b, 0xfb, 0xea, 0x29, 0xa1, 0x2d, 0xa9,
	0x80, 0x19, 0x6d, 0xd4, 0x32, 0xe3, 0xac, 0x35, 0x53, 0x55, 0x81, 0xc2, 0x77, 0x3e, 0x9e, 0xcc,
	0xcd, 0x1e, 0x70, 0x6f, 0x1f, 0xe9, 0x27, 0x6e, 0x05, 0x76, 0xff, 0xd6, 0x24, 0x7b, 0xb7, 0x52,
	0x4c, 0x97, 0xe6, 0xdc, 0x16, 0x91, 0x4c, 0xa0, 0x1c, 0x76, 0xf5, 0x24, 0xae, 0x69, 0x33, 0xbe,
	0xbc, 0xa8, 0xcc, 0xfb, 0x9a, 0xc9, 0x4a, 0xa2, 0xf4, 0x27, 0x96, 0x3d, 0x28, 0x89, 0xb8, 0x78,
	0x13, 0x17, 0x5f, 0x65, 0xc0, 0x42, 0x76, 0xed, 0x34, 0xdd, 0xa7, 0x58, 0xc8, 0x66, 0xb2, 0x72,
	0x99, 0xfd, 0xbc, 0xfc, 0xd4, 0x35, 0x3f, 0x93, 0x2c, 0x55, 0x8b, 0xc9, 0xca, 0xaf, 0xe2, 0xfe,
	0x4a, 0xf7, 0x35, 0x3f, 0x91, 0x9c, 0x6a, 0xdb, 0xcc, 0x0d, 0x54, 0x15, 0xfe, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xc4, 0x39, 0x21, 0xe5, 0xee, 0x14, 0x00, 0x00,
}
